// packages/desktop/src/gpuix/components/AutocompletePopup.tsx
/**
 * Autocomplete popup — port of AutocompletePopup.vue onto a GPUIX anchored
 * overlay (paints above the virtual list, unlike an absolute div).
 */

import { useTheme } from '../theme-context'
import { Text } from './ui/Text'
import { RemoteImage } from './ui/RemoteImage'
import type { AutocompleteSuggestion } from '../hooks/use-autocomplete'

export function AutocompletePopup({
  suggestions,
  selectedIndex,
  mode,
  onSelect,
}: {
  suggestions: AutocompleteSuggestion[]
  selectedIndex: number
  mode: 'mention' | 'emote' | 'command' | null
  onSelect: (index: number) => void
}) {
  const theme = useTheme()
  if (!mode || suggestions.length === 0) return null

  return (
    <anchored
      deferred
      side="top"
      align="start"
      gap={6}
      style={{
        minWidth: 200,
        maxWidth: 340,
        maxHeight: 240,
        overflowY: 'scroll',
        backgroundColor: theme.surface2,
        borderWidth: 1,
        borderColor: theme.border,
        borderRadius: 8,
        padding: 4,
        display: 'flex',
        flexDirection: 'column',
        gap: 2,
        boxShadow: { offsetX: 0, offsetY: 4, blurRadius: 16, spreadRadius: 0, color: '#00000066' },
      }}
    >
      {suggestions.map((suggestion, i) => (
        <div
          key={
            suggestion.type === 'mention'
              ? `${suggestion.label}:${suggestion.insertLabel}`
              : suggestion.type === 'command'
                ? `${suggestion.label}:${suggestion.insertText}`
                : suggestion.label
          }
          onClick={() => onSelect(i)}
          style={{
            display: 'flex',
            flexDirection: 'row',
            alignItems: 'center',
            gap: 8,
            paddingTop: 6,
            paddingBottom: 6,
            paddingLeft: 8,
            paddingRight: 8,
            borderRadius: 4,
            cursor: 'pointer',
            backgroundColor: i === selectedIndex ? 'rgba(167, 139, 250, 0.15)' : undefined,
            hover: { backgroundColor: 'rgba(255, 255, 255, 0.05)' },
          }}
        >
          {suggestion.type === 'mention' ? (
            <>
              <div
                style={{
                  width: 12,
                  height: 12,
                  borderRadius: 6,
                  backgroundColor: suggestion.color || '#8b8b99',
                  flexShrink: 0,
                }}
              />
              <Text style={{ fontSize: 14, color: theme.text, flexShrink: 0 }}>
                {suggestion.label}
              </Text>
              <Text
                style={{
                  fontSize: 12,
                  color: theme.text2,
                  overflow: 'hidden',
                  textOverflow: 'ellipsis',
                  whiteSpace: 'nowrap',
                }}
              >
                {suggestion.insertLabel !== suggestion.label
                  ? `→ ${suggestion.insertLabel}`
                  : (suggestion.description ?? '')}
              </Text>
            </>
          ) : suggestion.type === 'emote' ? (
            <>
              <RemoteImage
                url={suggestion.imageUrl}
                objectFit="contain"
                style={{ width: 24, height: 24, flexShrink: 0 }}
              />
              <Text style={{ fontSize: 14, color: theme.text }}>{suggestion.label}</Text>
            </>
          ) : (
            <>
              <Text style={{ fontSize: 14, fontWeight: 600, color: theme.text }}>
                {suggestion.label}
              </Text>
              <Text style={{ fontSize: 12, color: theme.text2 }}>{suggestion.description}</Text>
            </>
          )}
        </div>
      ))}
    </anchored>
  )
}

// packages/desktop/src/views/main/components/AutocompletePopup.vue
<script setup lang="ts">
import type { AutocompleteSuggestion } from '../composables/useAutocomplete'

const props = defineProps<{
  suggestions: AutocompleteSuggestion[]
  selectedIndex: number
  mode: 'mention' | 'emote' | 'command' | null
}>()

const emit = defineEmits<{
  select: [index: number]
}>()
</script>

<template>
  <div v-if="mode && suggestions.length > 0" class="autocomplete-popup" @mousedown.prevent>
    <ul class="autocomplete-list">
      <li
        v-for="(suggestion, i) in suggestions"
        :key="
          suggestion.type === 'mention'
            ? `${suggestion.label}:${suggestion.insertLabel}`
            : suggestion.type === 'command'
              ? `${suggestion.label}:${suggestion.insertText}`
              : suggestion.label
        "
        class="autocomplete-item"
        :class="{ 'is-selected': i === selectedIndex }"
        @mousedown.prevent="emit('select', i)"
      >
        <template v-if="suggestion.type === 'mention'">
          <span
            class="mention-dot"
            :style="{ backgroundColor: suggestion.color || '#8b8b99' }"
          ></span>
          <span class="mention-label">{{ suggestion.label }}</span>
          <span class="suggestion-description">
            <template v-if="suggestion.insertLabel !== suggestion.label"
              >→ {{ suggestion.insertLabel }}</template
            >
            <template v-else-if="suggestion.description">{{ suggestion.description }}</template>
          </span>
        </template>

        <template v-else-if="suggestion.type === 'emote'">
          <img :src="suggestion.imageUrl" width="24" height="24" alt="" class="emote-image" />
          <span class="emote-label">{{ suggestion.label }}</span>
        </template>

        <template v-else>
          <span class="command-label">{{ suggestion.label }}</span>
          <span class="suggestion-description">{{ suggestion.description }}</span>
        </template>
      </li>
    </ul>
  </div>
</template>

<style scoped>
.autocomplete-popup {
  position: absolute;
  bottom: 100%;
  left: 0;
  right: 0;
  max-height: 240px;
  min-width: 200px;
  overflow-y: auto;
  background-color: var(--c-surface-2);
  border: 1px solid var(--c-border);
  border-radius: 8px;
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.2);
  z-index: 50;
  margin-bottom: 8px;
}

.autocomplete-list {
  list-style: none;
  margin: 0;
  padding: 4px;
  display: flex;
  flex-direction: column;
  gap: 2px;
}

.autocomplete-item {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 6px 8px;
  border-radius: 4px;
  cursor: pointer;
  color: var(--c-text);
  user-select: none;
}

.autocomplete-item:hover {
  background-color: rgba(255, 255, 255, 0.05);
}

.autocomplete-item.is-selected {
  background-color: rgba(167, 139, 250, 0.15);
}

.mention-dot {
  width: 12px;
  height: 12px;
  border-radius: 50%;
  flex-shrink: 0;
}

.mention-label,
.emote-label {
  font-size: 14px;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
  color: var(--c-text);
}

.suggestion-description {
  margin-left: auto;
  font-size: 12px;
  color: var(--c-text-2);
  white-space: nowrap;
}

.command-label {
  font-size: 14px;
  font-weight: 600;
  color: var(--c-text);
}

.emote-image {
  object-fit: contain;
  flex-shrink: 0;
}
</style>
