// packages/desktop/src/gpuix/components/StreamEditor.tsx
/**
 * Stream editor — port of StreamEditor.vue: shows the stream status of a
 * connected Twitch/Kick account and lets the user edit title + category.
 *
 * Status polling mirrors usePolling.ts semantics: an immediate first tick,
 * then a 60s interval, skipping ticks while the previous one is in flight.
 * The category dropdown is a GPUIX anchored overlay (paints above siblings).
 */

import { useEffect, useRef, useState } from 'react'
import type { CategorySearchResult } from '@twirchat/shared/protocol'

import { useBackend } from '../backend/context'
import { accent, withAlpha } from '../theme'
import { useTheme } from '../theme-context'
import { Icon } from './ui/Icon'
import { Text } from './ui/Text'
import { RemoteImage } from './ui/RemoteImage'

export interface StreamEditorProps {
  platform: 'twitch' | 'kick'
  /** The numeric broadcaster ID (Twitch) or channel slug (Kick) */
  channelId: string
}

export function StreamEditor({ platform, channelId }: StreamEditorProps) {
  const backend = useBackend()
  const theme = useTheme()

  // ── Stream status state ────────────────────────────────────────────────
  const [isLive, setIsLive] = useState(false)
  const [title, setTitle] = useState('')
  const [categoryId, setCategoryId] = useState<string | undefined>(undefined)
  const [categoryName, setCategoryName] = useState<string | undefined>(undefined)
  const [viewerCount, setViewerCount] = useState<number | undefined>(undefined)
  const [loadError, setLoadError] = useState<string | null>(null)
  const [loading, setLoading] = useState(false)

  // ── Edit state ─────────────────────────────────────────────────────────
  const [editing, setEditing] = useState(false)
  const [editTitle, setEditTitle] = useState('')
  const [editCategoryId, setEditCategoryId] = useState<string | undefined>(undefined)
  const [editCategoryName, setEditCategoryName] = useState<string | undefined>(undefined)
  const [saving, setSaving] = useState(false)
  const [saveError, setSaveError] = useState<string | null>(null)
  const [saveSuccess, setSaveSuccess] = useState(false)

  // ── Category search ────────────────────────────────────────────────────
  const [categoryQuery, setCategoryQuery] = useState('')
  const [categoryResults, setCategoryResults] = useState<CategorySearchResult[]>([])
  const [searchLoading, setSearchLoading] = useState(false)
  const [focusedField, setFocusedField] = useState<'title' | 'category' | null>(null)
  const searchTimer = useRef<ReturnType<typeof setTimeout> | null>(null)
  const saveTimer = useRef<ReturnType<typeof setTimeout> | null>(null)

  // Poll every 60 seconds (immediate first tick + overlap guard, like usePolling).
  useEffect(() => {
    let cancelled = false
    let running = false

    const tick = async () => {
      if (cancelled || running) return
      running = true
      setLoading(true)
      setLoadError(null)
      try {
        const s = await backend.api.getStreamStatus({ channelId, platform })
        if (cancelled) return
        setIsLive(s.isLive)
        setTitle(s.title)
        setCategoryId(s.categoryId)
        setCategoryName(s.categoryName)
        setViewerCount(s.viewerCount)
      } catch (error) {
        if (!cancelled) setLoadError(String(error))
      } finally {
        running = false
        if (!cancelled) setLoading(false)
      }
    }

    void tick()
    const timer = setInterval(() => void tick(), 60_000)
    return () => {
      cancelled = true
      clearInterval(timer)
    }
  }, [backend, platform, channelId])

  // Clear pending debounce / success timers on unmount.
  useEffect(() => {
    return () => {
      if (searchTimer.current) clearTimeout(searchTimer.current)
      if (saveTimer.current) clearTimeout(saveTimer.current)
    }
  }, [])

  function onCategoryInput(value: string) {
    setCategoryQuery(value)
    if (searchTimer.current) clearTimeout(searchTimer.current)
    if (!value.trim()) {
      setCategoryResults([])
      return
    }
    searchTimer.current = setTimeout(async () => {
      setSearchLoading(true)
      try {
        const res = await backend.api.searchCategories({ platform, query: value })
        setCategoryResults(res.categories)
      } catch {
        setCategoryResults([])
      } finally {
        setSearchLoading(false)
      }
    }, 350)
  }

  function selectCategory(cat: CategorySearchResult) {
    setEditCategoryId(cat.id)
    setEditCategoryName(cat.name)
    setCategoryQuery(cat.name)
    setCategoryResults([])
  }

  // ── Edit / Save ────────────────────────────────────────────────────────

  function startEdit() {
    setEditTitle(title)
    setEditCategoryId(categoryId)
    setEditCategoryName(categoryName)
    setCategoryQuery(categoryName ?? '')
    setCategoryResults([])
    setSaveError(null)
    setSaveSuccess(false)
    setEditing(true)
  }

  async function save() {
    setSaving(true)
    setSaveError(null)
    try {
      await backend.api.updateStream({
        categoryId: editCategoryId,
        channelId,
        platform,
        title: editTitle,
      })
      // Reflect changes locally immediately
      setTitle(editTitle)
      setCategoryId(editCategoryId)
      setCategoryName(editCategoryName)
      setSaveSuccess(true)
      saveTimer.current = setTimeout(() => {
        setSaveSuccess(false)
        setEditing(false)
      }, 1500)
    } catch (error) {
      setSaveError(String(error))
    } finally {
      setSaving(false)
    }
  }

  // ── Shared styles ──────────────────────────────────────────────────────

  const placeholderColor = withAlpha(theme.text2, 0.6)
  const inputStyle = (focused: boolean) => ({
    backgroundColor: theme.surface2,
    borderWidth: 1,
    borderColor: focused ? accent.primary : theme.border,
    borderRadius: 7,
    color: theme.text,
    fontSize: 13,
    paddingTop: 7,
    paddingBottom: 7,
    paddingLeft: 10,
    paddingRight: 10,
  })
  const labelStyle = {
    fontSize: 11,
    fontWeight: 700,
    color: theme.text2,
    marginTop: 4,
  }

  return (
    <div
      style={{
        paddingTop: 12,
        paddingBottom: 14,
        paddingLeft: 20,
        paddingRight: 20,
        borderTopWidth: 1,
        borderColor: theme.border,
        display: 'flex',
        flexDirection: 'column',
        gap: 6,
      }}
    >
      {/* Loading / error */}
      {loading && !title ? (
        <Text style={{ fontSize: 12, color: theme.text2 }}>Loading stream info…</Text>
      ) : loadError ? (
        <Text style={{ fontSize: 12, color: '#ef4444' }}>{loadError}</Text>
      ) : !editing ? (
        /* Status display (not editing) */
        <>
          <div style={{ display: 'flex', flexDirection: 'row', alignItems: 'center', gap: 8 }}>
            <div
              style={{
                paddingTop: 2,
                paddingBottom: 2,
                paddingLeft: 7,
                paddingRight: 7,
                borderRadius: 4,
                borderWidth: 1,
                ...(isLive
                  ? {
                      backgroundColor: 'rgba(239, 68, 68, 0.15)',
                      borderColor: 'rgba(239, 68, 68, 0.35)',
                    }
                  : { backgroundColor: theme.surface2, borderColor: theme.border }),
              }}
            >
              <Text
                style={{ fontSize: 10, fontWeight: 800, color: isLive ? '#ef4444' : theme.text2 }}
              >
                {isLive ? 'LIVE' : 'OFFLINE'}
              </Text>
            </div>
            {isLive && viewerCount !== undefined ? (
              <Text style={{ fontSize: 12, color: theme.text2 }}>
                {`${viewerCount.toLocaleString()} viewers`}
              </Text>
            ) : null}
            <div style={{ flexGrow: 1 }} />
            <div
              testId="stream-edit"
              onClick={startEdit}
              style={{
                display: 'flex',
                flexDirection: 'row',
                alignItems: 'center',
                gap: 5,
                backgroundColor: accent.tint10,
                borderWidth: 1,
                borderColor: accent.tint20,
                borderRadius: 6,
                paddingTop: 3,
                paddingBottom: 3,
                paddingLeft: 10,
                paddingRight: 10,
                cursor: 'pointer',
                hover: { backgroundColor: accent.tint20 },
              }}
            >
              <Icon name="edit" size={14} color={accent.primary} />
              <Text style={{ fontSize: 12, fontWeight: 600, color: accent.primary }}>Edit</Text>
            </div>
          </div>
          {title ? (
            <Text
              style={{
                fontSize: 13,
                fontWeight: 600,
                color: theme.text,
                overflow: 'hidden',
                textOverflow: 'ellipsis',
                whiteSpace: 'nowrap',
              }}
            >
              {title}
            </Text>
          ) : null}
          {categoryName ? (
            <Text style={{ fontSize: 12, color: theme.text2 }}>{categoryName}</Text>
          ) : null}
        </>
      ) : (
        /* Edit form */
        <div style={{ display: 'flex', flexDirection: 'column', gap: 6 }}>
          <Text style={labelStyle}>{'Title'.toUpperCase()}</Text>
          <input
            value={editTitle}
            placeholder="Stream title…"
            onChange={(event) => setEditTitle((event.value ?? '').slice(0, 140))}
            onFocus={() => setFocusedField('title')}
            onBlur={() => setFocusedField((field) => (field === 'title' ? null : field))}
            theme={{ caret: accent.primary, textMuted: placeholderColor }}
            style={inputStyle(focusedField === 'title')}
          />

          <Text style={labelStyle}>{'Category / Game'.toUpperCase()}</Text>
          <div style={{ position: 'relative', display: 'flex', flexDirection: 'column' }}>
            <input
              value={categoryQuery}
              placeholder="Search categories…"
              onChange={(event) => onCategoryInput(event.value ?? '')}
              onFocus={() => setFocusedField('category')}
              onBlur={() => setFocusedField((field) => (field === 'category' ? null : field))}
              theme={{ caret: accent.primary, textMuted: placeholderColor }}
              style={inputStyle(focusedField === 'category')}
            />
            {!searchLoading && categoryResults.length > 0 ? (
              <anchored
                deferred
                side="bottom"
                align="start"
                gap={4}
                onMouseDownOutside={() => setCategoryResults([])}
                style={{
                  width: '100%',
                  maxHeight: 200,
                  overflowY: 'scroll',
                  backgroundColor: theme.surface,
                  borderWidth: 1,
                  borderColor: theme.border,
                  borderRadius: 8,
                  padding: 4,
                  display: 'flex',
                  flexDirection: 'column',
                  boxShadow: {
                    offsetX: 0,
                    offsetY: 8,
                    blurRadius: 24,
                    spreadRadius: 0,
                    color: 'rgba(0, 0, 0, 0.4)',
                  },
                }}
              >
                {categoryResults.map((cat) => (
                  <div
                    key={cat.id}
                    onClick={() => selectCategory(cat)}
                    style={{
                      display: 'flex',
                      flexDirection: 'row',
                      alignItems: 'center',
                      gap: 8,
                      paddingTop: 7,
                      paddingBottom: 7,
                      paddingLeft: 10,
                      paddingRight: 10,
                      borderRadius: 6,
                      cursor: 'pointer',
                      hover: { backgroundColor: accent.tint12 },
                    }}
                  >
                    {cat.thumbnailUrl ? (
                      <RemoteImage
                        url={cat.thumbnailUrl}
                        objectFit="cover"
                        style={{ width: 26, height: 36, borderRadius: 3, flexShrink: 0 }}
                      />
                    ) : null}
                    <Text style={{ fontSize: 13, color: theme.text }}>{cat.name}</Text>
                  </div>
                ))}
              </anchored>
            ) : null}
          </div>
          {searchLoading ? (
            <Text style={{ fontSize: 12, color: theme.text2, paddingTop: 4, paddingLeft: 2 }}>
              Searching…
            </Text>
          ) : null}

          {saveError ? <Text style={{ fontSize: 12, color: '#ef4444' }}>{saveError}</Text> : null}

          <div
            style={{
              display: 'flex',
              flexDirection: 'row',
              gap: 8,
              justifyContent: 'flex-end',
              marginTop: 4,
            }}
          >
            <div
              testId="stream-cancel"
              onClick={saving ? undefined : () => setEditing(false)}
              style={{
                backgroundColor: 'rgba(255, 255, 255, 0.06)',
                borderWidth: 1,
                borderColor: theme.border,
                borderRadius: 7,
                paddingTop: 6,
                paddingBottom: 6,
                paddingLeft: 16,
                paddingRight: 16,
                cursor: saving ? 'not-allowed' : 'pointer',
                opacity: saving ? 0.45 : 1,
                hover: saving ? undefined : { backgroundColor: 'rgba(255, 255, 255, 0.1)' },
              }}
            >
              <Text style={{ fontSize: 13, fontWeight: 600, color: theme.text2 }}>Cancel</Text>
            </div>
            <div
              testId="stream-save"
              onClick={saving ? undefined : () => void save()}
              style={{
                display: 'flex',
                flexDirection: 'row',
                alignItems: 'center',
                gap: 5,
                backgroundColor: accent.primary,
                borderRadius: 7,
                paddingTop: 6,
                paddingBottom: 6,
                paddingLeft: 16,
                paddingRight: 16,
                cursor: saving ? 'not-allowed' : 'pointer',
                opacity: saving ? 0.45 : 1,
                hover: saving ? undefined : { opacity: 0.88 },
              }}
            >
              {saveSuccess ? <Icon name="check" size={13} color="#ffffff" /> : null}
              <Text style={{ fontSize: 13, fontWeight: 600, color: '#ffffff' }}>
                {saveSuccess ? 'Saved!' : saving ? 'Saving…' : 'Save'}
              </Text>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}

// packages/desktop/src/views/main/components/StreamEditor.vue
<script setup lang="ts">
/**
 * StreamEditor — shows stream status and lets the user edit title + category
 * for a connected Twitch or Kick account.
 *
 * Props:
 *   platform  — "twitch" | "kick"
 *   channelId — the numeric broadcaster ID (Twitch) or channel slug (Kick)
 *
 * On mount it polls for the current status. The user can then edit and save.
 */
import { ref, onMounted, onUnmounted } from "vue";
import type { CategorySearchResult } from "@twirchat/shared/protocol";
import { rpc } from "../main";

const props = defineProps<{
  platform: "twitch" | "kick";
  channelId: string;
}>();

// ---------------------------------------------------------------
// Stream status state
// ---------------------------------------------------------------
const isLive = ref(false);
const title = ref("");
const categoryId = ref<string | undefined>(undefined);
const categoryName = ref<string | undefined>(undefined);
const viewerCount = ref<number | undefined>(undefined);
const loadError = ref<string | null>(null);
const loading = ref(false);

// ---------------------------------------------------------------
// Edit state
// ---------------------------------------------------------------
const editing = ref(false);
const editTitle = ref("");
const editCategoryId = ref<string | undefined>(undefined);
const editCategoryName = ref<string | undefined>(undefined);
const saving = ref(false);
const saveError = ref<string | null>(null);
const saveSuccess = ref(false);

// ---------------------------------------------------------------
// Category search
// ---------------------------------------------------------------
const categoryQuery = ref("");
const categoryResults = ref<CategorySearchResult[]>([]);
const searchLoading = ref(false);
let searchTimer: ReturnType<typeof setTimeout> | null = null;

function onCategoryInput() {
  if (searchTimer) clearTimeout(searchTimer);
  if (!categoryQuery.value.trim()) {
    categoryResults.value = [];
    return;
  }
  searchTimer = setTimeout(async () => {
    searchLoading.value = true;
    try {
      const res = await rpc.request.searchCategories({
        platform: props.platform,
        query: categoryQuery.value,
      });
      categoryResults.value = res.categories;
    } catch {
      categoryResults.value = [];
    } finally {
      searchLoading.value = false;
    }
  }, 350);
}

function selectCategory(cat: CategorySearchResult) {
  editCategoryId.value = cat.id;
  editCategoryName.value = cat.name;
  categoryQuery.value = cat.name;
  categoryResults.value = [];
}

// ---------------------------------------------------------------
// Load current status
// ---------------------------------------------------------------
async function loadStatus() {
  loading.value = true;
  loadError.value = null;
  try {
    const s = await rpc.request.getStreamStatus({
      platform: props.platform,
      channelId: props.channelId,
    });
    isLive.value = s.isLive;
    title.value = s.title;
    categoryId.value = s.categoryId;
    categoryName.value = s.categoryName;
    viewerCount.value = s.viewerCount;
  } catch (e) {
    loadError.value = String(e);
  } finally {
    loading.value = false;
  }
}

// Poll every 60 seconds
let pollTimer: ReturnType<typeof setInterval> | null = null;

onMounted(() => {
  void loadStatus();
  pollTimer = setInterval(() => void loadStatus(), 60_000);
});

onUnmounted(() => {
  if (pollTimer) clearInterval(pollTimer);
  if (searchTimer) clearTimeout(searchTimer);
});

// ---------------------------------------------------------------
// Edit / Save
// ---------------------------------------------------------------
function startEdit() {
  editTitle.value = title.value;
  editCategoryId.value = categoryId.value;
  editCategoryName.value = categoryName.value;
  categoryQuery.value = categoryName.value ?? "";
  categoryResults.value = [];
  saveError.value = null;
  saveSuccess.value = false;
  editing.value = true;
}

function cancelEdit() {
  editing.value = false;
}

async function save() {
  saving.value = true;
  saveError.value = null;
  try {
    await rpc.request.updateStream({
      platform: props.platform,
      channelId: props.channelId,
      title: editTitle.value,
      categoryId: editCategoryId.value,
    });
    // Reflect changes locally immediately
    title.value = editTitle.value;
    categoryId.value = editCategoryId.value;
    categoryName.value = editCategoryName.value;
    saveSuccess.value = true;
    setTimeout(() => {
      saveSuccess.value = false;
      editing.value = false;
    }, 1500);
  } catch (e) {
    saveError.value = String(e);
  } finally {
    saving.value = false;
  }
}
</script>

<template>
  <div class="stream-editor">
    <!-- Loading / error -->
    <div v-if="loading && !title" class="se-placeholder">Loading stream info…</div>
    <div v-else-if="loadError" class="se-placeholder se-error">{{ loadError }}</div>

    <!-- Status display (not editing) -->
    <template v-else-if="!editing">
      <div class="se-status-row">
        <span class="se-live-badge" :class="{ live: isLive }">
          {{ isLive ? 'LIVE' : 'OFFLINE' }}
        </span>
        <span v-if="isLive && viewerCount !== undefined" class="se-viewers">
          {{ viewerCount.toLocaleString() }} viewers
        </span>
        <button class="se-edit-btn" title="Edit stream info" @click="startEdit">
          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
            <path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"/>
            <path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"/>
          </svg>
          Edit
        </button>
      </div>
      <div v-if="title" class="se-title">{{ title }}</div>
      <div v-if="categoryName" class="se-category">{{ categoryName }}</div>
    </template>

    <!-- Edit form -->
    <template v-else>
      <div class="se-form">
        <label class="se-label">Title</label>
        <input
          v-model="editTitle"
          class="se-input"
          maxlength="140"
          placeholder="Stream title…"
        />

        <label class="se-label">Category / Game</label>
        <div class="se-search-wrap">
          <input
            v-model="categoryQuery"
            class="se-input"
            placeholder="Search categories…"
            @input="onCategoryInput"
          />
          <div v-if="searchLoading" class="se-search-hint">Searching…</div>
          <ul v-else-if="categoryResults.length > 0" class="se-dropdown">
            <li
              v-for="cat in categoryResults"
              :key="cat.id"
              class="se-dropdown-item"
              @mousedown.prevent="selectCategory(cat)"
            >
              <img
                v-if="cat.thumbnailUrl"
                class="se-cat-thumb"
                :src="cat.thumbnailUrl"
                :alt="cat.name"
              />
              <span>{{ cat.name }}</span>
            </li>
          </ul>
        </div>

        <div v-if="saveError" class="se-save-error">{{ saveError }}</div>

        <div class="se-actions">
          <button class="se-btn se-btn-ghost" :disabled="saving" @click="cancelEdit">
            Cancel
          </button>
          <button class="se-btn se-btn-primary" :disabled="saving" @click="save">
            <svg v-if="saveSuccess" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round" stroke-linejoin="round">
              <polyline points="20 6 9 17 4 12"/>
            </svg>
            {{ saveSuccess ? 'Saved!' : saving ? 'Saving…' : 'Save' }}
          </button>
        </div>
      </div>
    </template>
  </div>
</template>

<style scoped>
.stream-editor {
  padding: 12px 20px 14px;
  border-top: 1px solid var(--c-border, #2a2a33);
  display: flex;
  flex-direction: column;
  gap: 6px;
}

.se-placeholder {
  font-size: 12px;
  color: var(--c-text-2, #8b8b99);
}

.se-error {
  color: #ef4444;
}

/* Status row */
.se-status-row {
  display: flex;
  align-items: center;
  gap: 8px;
}

.se-live-badge {
  font-size: 10px;
  font-weight: 800;
  letter-spacing: 0.08em;
  padding: 2px 7px;
  border-radius: 4px;
  background: var(--c-surface-2, #1f1f24);
  color: var(--c-text-2, #8b8b99);
  border: 1px solid var(--c-border, #2a2a33);
}

.se-live-badge.live {
  background: rgba(239, 68, 68, 0.15);
  color: #ef4444;
  border-color: rgba(239, 68, 68, 0.35);
}

.se-viewers {
  font-size: 12px;
  color: var(--c-text-2, #8b8b99);
}

.se-edit-btn {
  margin-left: auto;
  background: rgba(167, 139, 250, 0.1);
  color: #a78bfa;
  border: 1px solid rgba(167, 139, 250, 0.2);
  border-radius: 6px;
  font-size: 12px;
  font-weight: 600;
  padding: 3px 10px;
  cursor: pointer;
  display: flex;
  align-items: center;
  gap: 5px;
  font-family: inherit;
  transition: background 0.15s;
}
.se-edit-btn:hover {
  background: rgba(167, 139, 250, 0.2);
}

.se-title {
  font-size: 13px;
  font-weight: 600;
  color: var(--c-text, #e2e2e8);
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.se-category {
  font-size: 12px;
  color: var(--c-text-2, #8b8b99);
}

/* Edit form */
.se-form {
  display: flex;
  flex-direction: column;
  gap: 6px;
}

.se-label {
  font-size: 11px;
  font-weight: 700;
  text-transform: uppercase;
  letter-spacing: 0.06em;
  color: var(--c-text-2, #8b8b99);
  margin-top: 4px;
}

.se-input {
  background: var(--c-surface-2, #1f1f24);
  border: 1px solid var(--c-border, #2a2a33);
  border-radius: 7px;
  color: var(--c-text, #e2e2e8);
  font-size: 13px;
  padding: 7px 10px;
  outline: none;
  font-family: inherit;
  width: 100%;
  transition: border-color 0.15s;
}
.se-input:focus {
  border-color: #a78bfa;
}

/* Category search */
.se-search-wrap {
  position: relative;
}

.se-search-hint {
  font-size: 12px;
  color: var(--c-text-2, #8b8b99);
  padding: 4px 2px;
}

.se-dropdown {
  position: absolute;
  top: calc(100% + 4px);
  left: 0;
  right: 0;
  background: var(--c-surface, #18181b);
  border: 1px solid var(--c-border, #2a2a33);
  border-radius: 8px;
  max-height: 200px;
  overflow-y: auto;
  z-index: 100;
  list-style: none;
  padding: 4px;
  box-shadow: 0 8px 24px rgba(0, 0, 0, 0.4);
}

.se-dropdown-item {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 7px 10px;
  border-radius: 6px;
  font-size: 13px;
  color: var(--c-text, #e2e2e8);
  cursor: pointer;
  transition: background 0.12s;
}
.se-dropdown-item:hover {
  background: rgba(167, 139, 250, 0.12);
}

.se-cat-thumb {
  width: 26px;
  height: 36px;
  object-fit: cover;
  border-radius: 3px;
  flex-shrink: 0;
}

/* Save error */
.se-save-error {
  font-size: 12px;
  color: #ef4444;
}

/* Actions */
.se-actions {
  display: flex;
  gap: 8px;
  justify-content: flex-end;
  margin-top: 4px;
}

.se-btn {
  border: none;
  border-radius: 7px;
  font-size: 13px;
  font-weight: 600;
  padding: 6px 16px;
  cursor: pointer;
  font-family: inherit;
  display: flex;
  align-items: center;
  gap: 5px;
  transition: opacity 0.15s, background 0.15s;
}
.se-btn:disabled {
  opacity: 0.45;
  cursor: not-allowed;
}

.se-btn-primary {
  background: #a78bfa;
  color: #fff;
}
.se-btn-primary:not(:disabled):hover {
  opacity: 0.88;
}

.se-btn-ghost {
  background: rgba(255, 255, 255, 0.06);
  color: var(--c-text-2, #8b8b99);
  border: 1px solid var(--c-border, #2a2a33);
}
.se-btn-ghost:hover {
  background: rgba(255, 255, 255, 0.1);
}
</style>
