// packages/desktop/src/views/main/components/ChannelTabBar.vue
<script setup lang="ts">
import type { PlatformStatusInfo, WatchedChannel } from '@twirchat/shared/types'
import { ref } from 'vue'
import { platformColor } from '../../shared/utils/platform'
import TwitchIcon from '../../../assets/icons/platforms/twitch.svg'
import YoutubeIcon from '../../../assets/icons/platforms/youtube.svg'
import KickIcon from '../../../assets/icons/platforms/kick.svg'

export type WatchedLiveStatus = {
  isLive: boolean
  viewerCount?: number
}

const props = defineProps<{
  watchedChannels: WatchedChannel[]
  activeTabId: string // "home" or a WatchedChannel.id
  watchedStatuses: Map<string, PlatformStatusInfo>
  /** ChannelId → live status info (from shared stream status store) */
  watchedLiveStatuses: Map<string, WatchedLiveStatus>
  /** Total viewers across own live channels, shown on the "My channels" tab */
  homeViewerCount?: number
  tabChannelNames?: Map<string, string[]>
}>()

const emit = defineEmits<{
  'select-tab': [id: string]
  'add-channel': []
  'remove-channel': [id: string]
  reorder: [fromId: string, toId: string]
}>()

function isLive(id: string): boolean {
  return props.watchedLiveStatuses.get(id)?.isLive === true
}

function viewerCount(id: string): number | undefined {
  const s = props.watchedLiveStatuses.get(id)
  return s?.isLive ? s.viewerCount : undefined
}

function formatViewers(n: number): string {
  if (n >= 1_000_000) return `${(n / 1_000_000).toFixed(1)}M`
  if (n >= 1000) return `${(n / 1_000).toFixed(1)}K`
  return String(n)
}

// ---- Drag-and-drop reordering ----
const dragOverId = ref<string | null>(null)
let dragSourceId: string | null = null

function onDragStart(e: DragEvent, id: string) {
  dragSourceId = id
  if (e.dataTransfer) {
    e.dataTransfer.effectAllowed = 'move'
    e.dataTransfer.setData('text/plain', id)
  }
}

function onDragOver(e: DragEvent, id: string) {
  if (!dragSourceId || dragSourceId === id) return
  e.preventDefault()
  if (e.dataTransfer) e.dataTransfer.dropEffect = 'move'
  dragOverId.value = id
}

function onDragLeave(id: string) {
  if (dragOverId.value === id) dragOverId.value = null
}

function onDrop(e: DragEvent, toId: string) {
  e.preventDefault()
  dragOverId.value = null
  if (!dragSourceId || dragSourceId === toId) return
  emit('reorder', dragSourceId, toId)
  dragSourceId = null
}

function onDragEnd() {
  dragOverId.value = null
  dragSourceId = null
}
</script>

<template>
  <div class="tab-bar">
    <!-- Home tab -->
    <button
      class="tab"
      :class="{ active: activeTabId === 'home' }"
      @click="emit('select-tab', 'home')"
      title="My Channels"
    >
      <svg
        width="13"
        height="13"
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        stroke-width="2.2"
        stroke-linecap="round"
        stroke-linejoin="round"
      >
        <path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z" />
        <polyline points="9 22 9 12 15 12 15 22" />
      </svg>
      <span class="tab-label">My channels</span>
      <span v-if="homeViewerCount !== undefined" class="tab-viewers">
        {{ formatViewers(homeViewerCount) }}
      </span>
    </button>

    <!-- Watched channel tabs -->
    <div
      v-for="ch in watchedChannels"
      :key="ch.id"
      class="tab-wrapper"
      :class="{ 'drag-over': dragOverId === ch.id }"
      draggable="true"
      @dragstart="onDragStart($event, ch.id)"
      @dragover="onDragOver($event, ch.id)"
      @dragleave="onDragLeave(ch.id)"
      @drop="onDrop($event, ch.id)"
      @dragend="onDragEnd"
    >
      <button
        class="tab"
        :class="{ active: activeTabId === ch.id }"
        :style="activeTabId === ch.id ? { '--tab-color': platformColor(ch.platform) } : {}"
        @click="emit('select-tab', ch.id)"
        :title="`${ch.platform}: ${ch.displayName}`"
      >
        <!-- Live dot: only shown when stream is live -->
        <span
          v-if="isLive(ch.id)"
          class="live-dot"
          :style="{ '--dot-color': platformColor(ch.platform) }"
        />

        <!-- Platform icon -->
        <component
          :is="
            ch.platform === 'twitch' ? TwitchIcon : ch.platform === 'kick' ? KickIcon : YoutubeIcon
          "
          width="12"
          height="12"
          fill="currentColor"
        />
        <span class="tab-label">
          {{
            (props.tabChannelNames?.get(ch.id) ?? []).length > 0
              ? props.tabChannelNames!.get(ch.id)!.join(', ')
              : ch.displayName
          }}
        </span>
        <span v-if="viewerCount(ch.id) !== undefined" class="tab-viewers">
          {{ formatViewers(viewerCount(ch.id)!) }}
        </span>
      </button>

      <!-- Close button — only show when this tab is hovered -->
      <button
        class="tab-close"
        :title="`Remove ${ch.displayName}`"
        @click.stop="emit('remove-channel', ch.id)"
      >
        <svg
          width="10"
          height="10"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          stroke-width="2.5"
          stroke-linecap="round"
        >
          <line x1="18" y1="6" x2="6" y2="18" />
          <line x1="6" y1="6" x2="18" y2="18" />
        </svg>
      </button>
    </div>

    <!-- Add button -->
    <button class="tab tab-add" @click="emit('add-channel')" title="Add channel">
      <svg
        width="14"
        height="14"
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        stroke-width="2.5"
        stroke-linecep="round"
      >
        <line x1="12" y1="5" x2="12" y2="19" />
        <line x1="5" y1="12" x2="19" y2="12" />
      </svg>
    </button>
  </div>
</template>

<style scoped>
.tab-bar {
  display: flex;
  align-items: center;
  gap: 2px;
  padding: 6px 8px 0;
  border-bottom: 1px solid var(--c-border, #2a2a33);
  background: var(--c-nav-bg, #111114);
  flex-shrink: 0;
  overflow-x: auto;
  scrollbar-width: none;
}
.tab-bar::-webkit-scrollbar {
  display: none;
}

.tab-wrapper {
  position: relative;
  display: flex;
  align-items: center;
}

.tab-wrapper:hover .tab-close {
  opacity: 1;
  pointer-events: auto;
}

.tab {
  display: inline-flex;
  align-items: center;
  gap: 5px;
  padding: 5px 10px 6px;
  border: none;
  background: none;
  color: var(--c-text-2, #8b8b99);
  font-size: 12px;
  font-weight: 500;
  font-family: inherit;
  cursor: pointer;
  border-radius: 6px 6px 0 0;
  transition:
    color 0.15s,
    background 0.15s;
  white-space: nowrap;
  position: relative;
  bottom: -1px;
  border-bottom: 2px solid transparent;
  flex-shrink: 0;
}

.tab:hover {
  background: rgba(255, 255, 255, 0.05);
  color: var(--c-text, #e2e2e8);
}

.tab.active {
  color: var(--tab-color, #a78bfa);
  border-bottom-color: var(--tab-color, #a78bfa);
  background: rgba(167, 139, 250, 0.06);
}

.tab-label {
  max-width: 100px;
  overflow: hidden;
  text-overflow: ellipsis;
}

/* Live indicator dot */
.live-dot {
  width: 6px;
  height: 6px;
  border-radius: 50%;
  background: var(--dot-color, #22c55e);
  flex-shrink: 0;
}

.tab-viewers {
  font-size: 10px;
  opacity: 0.7;
  font-variant-numeric: tabular-nums;
  flex-shrink: 0;
}

.tab-close {
  position: absolute;
  right: -2px;
  top: 2px;
  width: 16px;
  height: 16px;
  border-radius: 4px;
  border: none;
  background: var(--c-surface-2, #1f1f24);
  color: var(--c-text-2, #8b8b99);
  display: flex;
  align-items: center;
  justify-content: center;
  cursor: pointer;
  opacity: 0;
  pointer-events: none;
  transition:
    opacity 0.15s,
    background 0.15s,
    color 0.15s;
  z-index: 1;
}

.tab-close:hover {
  background: #ef4444;
  color: #fff;
}

.tab-add {
  padding: 5px 8px 6px;
  opacity: 0.5;
  flex-shrink: 0;
}

.tab-add:hover {
  opacity: 1;
}

.tab-wrapper.drag-over {
  border-left: 2px solid var(--c-text-2, #8b8b99);
}
</style>

// packages/desktop/src/gpuix/components/ChannelTabBar.tsx
/**
 * Channel tab bar — port of ChannelTabBar.vue.
 * GPUIX delta: HTML5 drag-reorder is not available, so tab reordering is
 * omitted (see MIGRATION notes).
 */

import { useState } from 'react'
import type { PlatformStatusInfo, WatchedChannel } from '@twirchat/shared/types'

import { platformColor } from '../theme'
import { useTheme } from '../theme-context'
import { Icon, PlatformIcon } from './ui/Icon'
import { Text } from './ui/Text'

export interface WatchedLiveStatus {
  isLive: boolean
  viewerCount?: number
}

function formatViewers(n: number): string {
  if (n >= 1_000_000) return `${(n / 1_000_000).toFixed(1)}M`
  if (n >= 1000) return `${(n / 1000).toFixed(1)}K`
  return String(n)
}

export function ChannelTabBar({
  watchedChannels,
  activeTabId,
  watchedLiveStatuses,
  homeViewerCount,
  tabChannelNames,
  onSelectTab,
  onAddChannel,
  onRemoveChannel,
}: {
  watchedChannels: WatchedChannel[]
  activeTabId: string
  watchedStatuses: Map<string, PlatformStatusInfo>
  watchedLiveStatuses: Map<string, WatchedLiveStatus>
  homeViewerCount?: number
  tabChannelNames?: Map<string, string[]>
  onSelectTab: (id: string) => void
  onAddChannel: () => void
  onRemoveChannel: (id: string) => void
}) {
  const theme = useTheme()

  return (
    <div
      style={{
        display: 'flex',
        flexDirection: 'row',
        alignItems: 'center',
        gap: 2,
        paddingTop: 6,
        paddingLeft: 8,
        paddingRight: 8,
        borderBottomWidth: 1,
        borderColor: theme.border,
        backgroundColor: theme.navBg,
        flexShrink: 0,
        overflowX: 'scroll',
        userSelect: 'none',
      }}
    >
      {/* Home tab */}
      <Tab
        testId="tab-home"
        label="My channels"
        icon={
          <Icon name="home" size={13} color={activeTabId === 'home' ? theme.text : theme.text2} />
        }
        active={activeTabId === 'home'}
        activeColor={theme.text}
        viewers={homeViewerCount}
        onClick={() => onSelectTab('home')}
      />

      {watchedChannels.map((ch) => {
        const live = watchedLiveStatuses.get(ch.id)
        const names = tabChannelNames?.get(ch.id)
        const label = names && names.length > 0 ? names.join(', ') : ch.displayName
        const active = activeTabId === ch.id
        const color = platformColor(ch.platform)
        return (
          <WatchedTab
            key={ch.id}
            testId={`tab-${ch.id}`}
            label={label}
            platform={ch.platform}
            active={active}
            live={live?.isLive === true}
            viewers={live?.isLive ? live.viewerCount : undefined}
            color={color}
            onClick={() => onSelectTab(ch.id)}
            onClose={() => onRemoveChannel(ch.id)}
          />
        )
      })}

      {/* Add button */}
      <div
        testId="tab-add"
        onClick={onAddChannel}
        style={{
          paddingTop: 5,
          paddingBottom: 6,
          paddingLeft: 8,
          paddingRight: 8,
          cursor: 'pointer',
          opacity: 0.5,
          flexShrink: 0,
          display: 'flex',
          hover: { opacity: 1 },
        }}
      >
        <Icon name="plus" size={14} color={theme.text2} />
      </div>
    </div>
  )
}

function Tab({
  label,
  icon,
  active,
  activeColor,
  viewers,
  onClick,
  testId,
}: {
  label: string
  icon?: React.ReactNode
  active: boolean
  activeColor: string
  viewers?: number
  onClick: () => void
  testId?: string
}) {
  const theme = useTheme()
  const [hovered, setHovered] = useState(false)
  return (
    <div
      testId={testId}
      onClick={onClick}
      onMouseEnter={() => setHovered(true)}
      onMouseLeave={() => setHovered(false)}
      style={{
        display: 'flex',
        flexDirection: 'row',
        alignItems: 'center',
        gap: 5,
        paddingTop: 5,
        paddingBottom: 6,
        paddingLeft: 10,
        paddingRight: 10,
        cursor: 'pointer',
        borderTopLeftRadius: 6,
        borderTopRightRadius: 6,
        borderBottomWidth: 2,
        borderColor: active ? activeColor : 'transparent',
        backgroundColor: active
          ? 'rgba(167, 139, 250, 0.06)'
          : hovered
            ? 'rgba(255, 255, 255, 0.05)'
            : undefined,
        flexShrink: 0,
        position: 'relative',
        marginBottom: -1,
      }}
    >
      {icon}
      <Text
        style={{
          fontSize: 12,
          fontWeight: 500,
          color: active ? activeColor : hovered ? theme.text : theme.text2,
          maxWidth: 100,
          overflow: 'hidden',
          textOverflow: 'ellipsis',
          whiteSpace: 'nowrap',
        }}
      >
        {label}
      </Text>
      {viewers !== undefined ? (
        <Text style={{ fontSize: 10, color: active ? activeColor : theme.text2, opacity: 0.7 }}>
          {formatViewers(viewers)}
        </Text>
      ) : null}
    </div>
  )
}

function WatchedTab({
  label,
  platform,
  active,
  live,
  viewers,
  color,
  onClick,
  onClose,
  testId,
}: {
  label: string
  platform: string
  active: boolean
  live: boolean
  viewers?: number
  color: string
  onClick: () => void
  onClose: () => void
  testId?: string
}) {
  const [hovered, setHovered] = useState(false)
  const [closeHovered, setCloseHovered] = useState(false)

  return (
    <div
      onMouseEnter={() => setHovered(true)}
      onMouseLeave={() => setHovered(false)}
      style={{ position: 'relative', display: 'flex', alignItems: 'center' }}
    >
      <Tab
        testId={testId}
        label={label}
        active={active}
        activeColor={color}
        viewers={viewers}
        onClick={onClick}
        icon={
          <>
            {live ? (
              <div
                style={{
                  width: 6,
                  height: 6,
                  borderRadius: 3,
                  backgroundColor: color,
                  flexShrink: 0,
                }}
              />
            ) : null}
            <PlatformIcon platform={platform} size={12} color={active ? color : '#8b8b99'} />
          </>
        }
      />
      {hovered ? (
        <div
          onClick={(event) => {
            void event
            onClose()
          }}
          onMouseEnter={() => setCloseHovered(true)}
          onMouseLeave={() => setCloseHovered(false)}
          style={{
            position: 'absolute',
            right: -2,
            top: 2,
            width: 16,
            height: 16,
            borderRadius: 4,
            backgroundColor: closeHovered ? '#ef4444' : '#1f1f24',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            cursor: 'pointer',
          }}
        >
          <Icon name="close" size={10} color={closeHovered ? '#ffffff' : '#8b8b99'} />
        </div>
      ) : null}
    </div>
  )
}
