// packages/desktop/src/views/main/components/ChatInput.vue
<script setup lang="ts">
import { computed, nextTick, ref, watch } from 'vue'
import type {
  Account,
  AppSettings,
  NormalizedChatMessage,
  PlatformStatusInfo,
  WatchedChannel,
} from '@twirchat/shared/types'
import { platformColor } from '../../shared/utils/platform'
import TwitchIcon from '../../../assets/icons/platforms/twitch.svg'
import YoutubeIcon from '../../../assets/icons/platforms/youtube.svg'
import KickIcon from '../../../assets/icons/platforms/kick.svg'
import { parseToken, replaceToken, useAutocomplete } from '../composables/useAutocomplete'
import { useAliasStore } from '../stores/useAliasStore'
import { resolveUserCardCommand, type UserCardTarget } from '../utils/chatCommands'
import { createChatMessageTargets, ownChatSendTargets } from '../utils/chat-send-targets'
import { textareaHeight } from '../utils/chat-textarea'
import AutocompletePopup from './AutocompletePopup.vue'
import { PopoverContent, PopoverRoot, PopoverTrigger } from 'reka-ui'
import EmotePicker from './EmotePicker.vue'

const props = defineProps<{
  accounts: Account[]
  settings: AppSettings
  statuses: Map<string, PlatformStatusInfo>
  /** When set, input is scoped to this watched channel */
  watchedChannel?: WatchedChannel | null
  /** Connection status for the watched channel */
  watchedChannelStatus?: PlatformStatusInfo | null
  replyTarget?: NormalizedChatMessage | null
  messages?: NormalizedChatMessage[]
}>()

const emit = defineEmits<{
  send: [
    payload: { platform: string; channelLogin: string; text: string; replyToMessageId?: string }[],
  ]
  'send-watched': [payload: { text: string; channelId: string; replyToMessageId?: string }]
  'open-user-card': [target: UserCardTarget]
  'cancel-reply': []
}>()

const text = ref('')
const textareaEl = ref<HTMLTextAreaElement | null>(null)
const aliasStore = useAliasStore()
const commandError = ref('')

const showEmotePicker = ref(false)
const emotePickerRef = ref<InstanceType<typeof EmotePicker> | null>(null)

const { suggestions, isOpen, selectedIndex, mode, selectSuggestion, moveUp, moveDown, close } =
  useAutocomplete({
    text,
    messages: computed(() => props.messages ?? []),
    watchedChannel: computed(() => props.watchedChannel ?? null),
    statuses: computed(() => props.statuses),
    aliasMap: computed(() => aliasStore.aliasMap),
  })

const currentChannelInfo = computed((): { platform: string; channelId: string } | null => {
  if (props.watchedChannel) {
    return { platform: props.watchedChannel.platform, channelId: props.watchedChannel.channelSlug }
  }
  const target = ownChatSendTargets(props.accounts)[0]
  return target ? { platform: target.platform, channelId: target.channelLogin } : null
})

watch(showEmotePicker, async (isPickerOpen) => {
  if (isPickerOpen) {
    await nextTick()
    emotePickerRef.value?.focus()
  }
})

function onEmoteSelect(alias: string): void {
  // Branch 1: active :token at end of text → use replaceToken
  const token = parseToken(text.value)
  if (token.mode === 'emote') {
    text.value = replaceToken(text.value, {
      type: 'emote',
      label: alias,
      imageUrl: '',
      animated: false,
    })
  } else {
    // Branch 2: no active :token → insert at cursor position (or append)
    const el = textareaEl.value
    const pos = el?.selectionStart ?? text.value.length
    const insertion = alias + ' '
    text.value = text.value.slice(0, pos) + insertion + text.value.slice(pos)
    // Restore cursor after insertion
    void nextTick(() => {
      if (el) {
        const newPos = pos + insertion.length
        el.focus()
        el.setSelectionRange(newPos, newPos)
      }
    })
  }
  // Close picker after selection
  showEmotePicker.value = false
  // Refocus textarea
  void nextTick(() => textareaEl.value?.focus())
}

function resizeTextarea(): void {
  const el = textareaEl.value
  if (!el) {
    return
  }
  el.style.height = '0px'
  el.style.height = `${textareaHeight(el.scrollHeight)}px`
}

watch(text, () => void nextTick(resizeTextarea))

watch(text, () => {
  commandError.value = ''
})

// ---- Normal (home tab) mode ----

const connectedPlatforms = computed(() => {
  if (props.watchedChannel) {
    return []
  }
  return ownChatSendTargets(props.accounts).map((target) => {
    const exactStatus = [...props.statuses.values()].find(
      (info) =>
        info.platform === target.platform &&
        info.channelLogin?.toLowerCase() === target.channelLogin.toLowerCase(),
    )
    return {
      platform: target.platform,
      channelLogin: target.channelLogin,
      status: exactStatus?.status ?? 'connected',
      mode: exactStatus?.mode ?? 'authenticated',
    }
  })
})

const sendablePlatforms = computed(() =>
  connectedPlatforms.value.filter((p) => p.mode === 'authenticated'),
)

const hasAnything = computed(() => {
  if (props.watchedChannel) {
    return true
  }
  return connectedPlatforms.value.length > 0
})

const isDisabled = computed(() => {
  if (props.watchedChannel) {
    // Can send if authenticated, or even anon for watched we allow read-only still
    return props.watchedChannelStatus?.mode !== 'authenticated'
  }
  return sendablePlatforms.value.length === 0
})

const enabled = ref<Record<string, boolean>>({})

function isEnabled(platform: string): boolean {
  const info = connectedPlatforms.value.find((p) => p.platform === platform)
  if (!info || info.mode !== 'authenticated') {
    return false
  }
  return enabled.value[platform] !== false
}

function toggle(platform: string) {
  const info = connectedPlatforms.value.find((p) => p.platform === platform)
  if (!info || info.mode !== 'authenticated') {
    return
  }
  enabled.value = { ...enabled.value, [platform]: !isEnabled(platform) }
}

const canSend = computed(() => {
  if (!text.value.trim()) {
    return false
  }
  if (props.watchedChannel) {
    return !isDisabled.value
  }
  return (
    createChatMessageTargets(sendablePlatforms.value, text.value, isEnabled, props.replyTarget)
      .length > 0
  )
})

function send() {
  const trimmed = text.value.trim()
  if (!trimmed) {
    return
  }

  const userCardCommand = resolveUserCardCommand(trimmed, props.messages ?? [], aliasStore.aliasMap)
  if (userCardCommand) {
    if (!userCardCommand.ok) {
      commandError.value =
        userCardCommand.error === 'missing-query'
          ? 'Usage: /user @nickname'
          : userCardCommand.error === 'ambiguous'
            ? 'Multiple users match that nickname.'
            : 'No user found for that nickname.'
      return
    }

    emit('open-user-card', userCardCommand.target)
    commandError.value = ''
    text.value = ''
    nextTick(() => {
      if (textareaEl.value) {
        textareaEl.value.style.height = 'auto'
      }
    })
    return
  }

  if (props.watchedChannel) {
    emit('send-watched', {
      text: trimmed,
      channelId: props.watchedChannel.id,
      replyToMessageId: props.replyTarget?.id,
    })
  } else {
    const targets = createChatMessageTargets(
      sendablePlatforms.value,
      trimmed,
      isEnabled,
      props.replyTarget,
    )
    if (targets.length === 0) {
      return
    }
    emit('send', targets)
  }

  commandError.value = ''
  text.value = ''
  nextTick(() => {
    if (textareaEl.value) {
      textareaEl.value.style.height = 'auto'
    }
  })
}

// Focus textarea when a reply target is set
watch(
  () => props.replyTarget,
  (newVal) => {
    if (newVal) {
      void nextTick(() => textareaEl.value?.focus())
    }
  },
)

function onKeydown(e: KeyboardEvent) {
  if (isOpen.value) {
    if (e.key === 'ArrowUp') {
      e.preventDefault()
      moveUp()
      return
    }
    if (e.key === 'ArrowDown') {
      e.preventDefault()
      moveDown()
      return
    }
    if (e.key === 'Enter' || e.key === 'Tab') {
      e.preventDefault()
      selectSuggestion(selectedIndex.value)
      return
    }
    if (e.key === 'Escape') {
      e.preventDefault()
      close()
      return
    }
  }
  if (e.key === 'Enter' && !e.shiftKey) {
    e.preventDefault()
    send()
  }
}

function placeholderText(): string {
  if (props.watchedChannel) {
    if (props.watchedChannelStatus?.mode !== 'authenticated') {
      return 'Log in to send messages…'
    }
    return `Message ${props.watchedChannel.displayName}…`
  }
  if (!hasAnything.value) {
    return 'Connect a channel to send messages…'
  }
  if (isDisabled.value) {
    return 'Log in to send messages…'
  }
  return 'Send a message… (Enter ↵ to send, Shift+Enter for newline)'
}
</script>

<template>
  <div class="chat-input-bar">
    <div v-if="replyTarget" class="reply-bar">
      <span class="reply-bar-icon">↩</span>
      <span class="reply-bar-body">
        Replying to <strong>{{ replyTarget.author.displayName }}</strong
        >:
        {{ replyTarget.text.length > 80 ? replyTarget.text.slice(0, 80) + '…' : replyTarget.text }}
      </span>
      <button class="reply-bar-dismiss" title="Cancel reply" @click="emit('cancel-reply')">
        <svg
          xmlns="http://www.w3.org/2000/svg"
          width="16"
          height="16"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          stroke-width="2.5"
          stroke-linecap="round"
          stroke-linejoin="round"
        >
          <line x1="18" y1="6" x2="6" y2="18"></line>
          <line x1="6" y1="6" x2="18" y2="18"></line>
        </svg>
      </button>
    </div>

    <!-- Watched channel: single fixed chip -->
    <div v-if="settings.showChannelLabel && watchedChannel" class="input-targets">
      <div
        class="target-btn"
        :class="{
          active: watchedChannelStatus?.mode === 'authenticated',
          anon: watchedChannelStatus?.mode !== 'authenticated',
        }"
        :style="{ '--p-color': platformColor(watchedChannel.platform) }"
      >
        <component
          :is="
            watchedChannel.platform === 'twitch'
              ? TwitchIcon
              : watchedChannel.platform === 'kick'
                ? KickIcon
                : YoutubeIcon
          "
          width="13"
          height="13"
          fill="currentColor"
        />
        <span class="target-name">{{ watchedChannel.displayName }}</span>
        <svg
          v-if="watchedChannelStatus?.mode !== 'authenticated'"
          class="anon-lock"
          width="10"
          height="10"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          stroke-width="2.5"
          stroke-linecap="round"
          stroke-linejoin="round"
        >
          <rect x="3" y="11" width="18" height="11" rx="2" ry="2" />
          <path d="M7 11V7a5 5 0 0 1 10 0v4" />
        </svg>
      </div>
    </div>

    <!-- Home tab: per-platform chips -->
    <div
      v-else-if="settings.showChannelLabel && connectedPlatforms.length > 0"
      class="input-targets"
    >
      <button
        v-for="p in connectedPlatforms"
        :key="p.platform"
        class="target-btn"
        :class="{
          active: isEnabled(p.platform),
          anon: p.mode !== 'authenticated',
        }"
        :style="{ '--p-color': platformColor(p.platform) }"
        :title="
          p.mode !== 'authenticated'
            ? `${p.platform} — anonymous (log in to send)`
            : isEnabled(p.platform)
              ? `Disable ${p.platform}`
              : `Enable ${p.platform}`
        "
        @click="toggle(p.platform)"
      >
        <component
          v-if="p.platform === 'twitch' || p.platform === 'kick' || p.platform === 'youtube'"
          :is="
            p.platform === 'twitch' ? TwitchIcon : p.platform === 'kick' ? KickIcon : YoutubeIcon
          "
          width="13"
          height="13"
          fill="currentColor"
        />
        <span v-else class="target-letter">{{
          (p.platform as string).charAt(0).toUpperCase()
        }}</span>

        <span class="target-name">{{ p.channelLogin }}</span>

        <svg
          v-if="p.mode !== 'authenticated'"
          class="anon-lock"
          width="10"
          height="10"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          stroke-width="2.5"
          stroke-linecap="round"
          stroke-linejoin="round"
        >
          <rect x="3" y="11" width="18" height="11" rx="2" ry="2" />
          <path d="M7 11V7a5 5 0 0 1 10 0v4" />
        </svg>
      </button>
    </div>

    <!-- Textarea + send -->
    <AutocompletePopup
      v-if="isOpen"
      :suggestions="suggestions"
      :selected-index="selectedIndex"
      :mode="mode"
      @select="selectSuggestion"
    />
    <div v-if="commandError" class="command-error">{{ commandError }}</div>
    <div class="input-row">
      <textarea
        ref="textareaEl"
        v-model="text"
        class="chat-textarea"
        :placeholder="placeholderText()"
        :disabled="isDisabled"
        rows="1"
        @keydown="onKeydown"
      />
      <PopoverRoot v-model:open="showEmotePicker">
        <PopoverTrigger as-child>
          <button
            class="emote-btn"
            :class="{ 'is-open': showEmotePicker }"
            title="Emotes"
            :disabled="isDisabled"
          >
            <svg
              width="16"
              height="16"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              stroke-width="2"
              stroke-linecap="round"
              stroke-linejoin="round"
            >
              <circle cx="12" cy="12" r="10" />
              <path d="M8 13s1.5 2 4 2 4-2 4-2" />
              <line x1="9" y1="9" x2="9.01" y2="9" />
              <line x1="15" y1="9" x2="15.01" y2="9" />
            </svg>
          </button>
        </PopoverTrigger>
        <PopoverContent
          side="top"
          :side-offset="8"
          align="end"
          :avoid-collisions="true"
          class="emote-picker-popover"
        >
          <EmotePicker
            v-if="currentChannelInfo"
            ref="emotePickerRef"
            :platform="currentChannelInfo.platform"
            :channel-id="currentChannelInfo.channelId"
            @select="onEmoteSelect"
          />
        </PopoverContent>
      </PopoverRoot>
      <button class="send-btn" :disabled="!canSend" @click="send" title="Send">
        <svg
          width="16"
          height="16"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          stroke-width="2.2"
          stroke-linecap="round"
          stroke-linejoin="round"
        >
          <line x1="22" y1="2" x2="11" y2="13" />
          <polygon points="22 2 15 22 11 13 2 9 22 2" />
        </svg>
      </button>
    </div>
  </div>
</template>

<style scoped>
.chat-input-bar {
  position: relative;
  flex-shrink: 0;
  border-top: 1px solid var(--c-border, #2a2a33);
  padding: 8px 12px 10px;
  display: flex;
  flex-direction: column;
  gap: 7px;
  background: var(--c-surface, #18181b);
}

.reply-bar {
  display: flex;
  align-items: center;
  gap: 8px;
  background: rgba(255, 255, 255, 0.04);
  border-radius: 8px;
  padding: 5px 10px;
  border-left: 2px solid rgba(167, 139, 250, 0.5);
  font-size: 12px;
  color: var(--c-text-2, #8b8b99);
}

.reply-bar-icon {
  flex-shrink: 0;
  opacity: 0.7;
}

.reply-bar-body {
  flex: 1;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.reply-bar-body strong {
  color: var(--c-text, #e2e2e8);
}

.reply-bar-dismiss {
  width: 20px;
  height: 20px;
  display: flex;
  align-items: center;
  justify-content: center;
  background: none;
  border: none;
  cursor: pointer;
  color: var(--c-text-2, #8b8b99);
  padding: 0;
  border-radius: 4px;
}

.reply-bar-dismiss:hover {
  color: var(--c-text, #e2e2e8);
  background: rgba(255, 255, 255, 0.1);
}

/* ---- platform toggles ---- */
.input-targets {
  display: flex;
  gap: 6px;
  flex-wrap: wrap;
}

.target-btn {
  display: inline-flex;
  align-items: center;
  gap: 5px;
  padding: 3px 9px 3px 7px;
  border-radius: 20px;
  border: 1px solid rgba(255, 255, 255, 0.1);
  background: rgba(255, 255, 255, 0.04);
  color: var(--c-text-2, #8b8b99);
  font-size: 12px;
  font-weight: 500;
  font-family: inherit;
  cursor: pointer;
  transition:
    background 0.15s,
    border-color 0.15s,
    color 0.15s,
    opacity 0.15s;
  user-select: none;
}
.target-btn.active {
  background: color-mix(in srgb, var(--p-color) 15%, transparent);
  border-color: color-mix(in srgb, var(--p-color) 45%, transparent);
  color: var(--p-color);
}
.target-btn:not(.active):not(.anon) {
  opacity: 0.4;
}
.target-btn.anon {
  opacity: 0.35;
  cursor: default;
}
.target-btn:not(.anon):hover {
  opacity: 1;
  background: color-mix(in srgb, var(--p-color) 20%, transparent);
  border-color: color-mix(in srgb, var(--p-color) 55%, transparent);
  color: var(--p-color);
}

.target-letter {
  font-size: 11px;
  font-weight: 700;
}
.target-name {
  max-width: 80px;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
.anon-lock {
  opacity: 0.5;
  flex-shrink: 0;
}

/* ---- input row ---- */
.input-row {
  display: flex;
  align-items: flex-end;
  gap: 8px;
}

.command-error {
  font-size: 12px;
  color: #fca5a5;
  padding: 0 2px;
}

.chat-textarea {
  box-sizing: border-box;
  flex: 1;
  min-height: 36px;
  resize: none;
  background: var(--c-surface-2, #1f1f24);
  border: 1px solid var(--c-border, #2a2a33);
  border-radius: 10px;
  color: var(--c-text, #e2e2e8);
  font-family: inherit;
  font-size: 13px;
  line-height: 1.5;
  padding: 8px 12px;
  max-height: 120px;
  overflow-y: auto;
  outline: none;
  transition: border-color 0.15s;
  scrollbar-width: thin;
}
.chat-textarea:focus {
  border-color: rgba(167, 139, 250, 0.5);
}
.chat-textarea::placeholder {
  color: var(--c-text-2, #8b8b99);
  opacity: 0.6;
}
.chat-textarea:disabled {
  opacity: 0.4;
  cursor: not-allowed;
}

.send-btn {
  flex-shrink: 0;
  width: 36px;
  height: 36px;
  border-radius: 10px;
  border: none;
  background: #7c3aed;
  color: #fff;
  display: flex;
  align-items: center;
  justify-content: center;
  cursor: pointer;
  transition:
    background 0.15s,
    opacity 0.15s;
}
.send-btn:hover:not(:disabled) {
  background: #6d28d9;
}
.send-btn:disabled {
  opacity: 0.35;
  cursor: default;
}

.emote-btn {
  flex-shrink: 0;
  width: 36px;
  height: 36px;
  border-radius: 8px;
  border: none;
  background: transparent;
  color: var(--c-text-2, #8b8b99);
  display: flex;
  align-items: center;
  justify-content: center;
  cursor: pointer;
  transition:
    background 0.15s,
    color 0.15s;
}
.emote-btn:hover:not(:disabled) {
  background: rgba(255, 255, 255, 0.08);
  color: var(--c-text, #e2e2e8);
}
.emote-btn:disabled {
  opacity: 0.3;
  cursor: default;
}
.emote-btn.is-open {
  background: rgba(167, 139, 250, 0.15);
  color: #a78bfa;
}
</style>

<style>
/* Global styles — PopoverContent is portalled outside the component tree */
.emote-picker-popover {
  background: var(--c-surface-2, #1f1f24);
  border: 1px solid var(--c-border, #2a2a33);
  border-radius: 12px;
  padding: 0;
  box-shadow: 0 8px 32px rgba(0, 0, 0, 0.4);
  z-index: 200;
  overflow: hidden;
}
</style>

// packages/desktop/src/gpuix/components/ChatInput.tsx
/**
 * Message composer — port of ChatInput.vue.
 *
 * Native <textarea> (auto-growing, Enter submits). Autocomplete keyboard
 * navigation intercepts keys via onKeyDown; while the popup is open the
 * textarea's onSubmit is removed, otherwise GPUI's Enter→submit action would
 * consume the key before the popup sees it.
 */

import { useMemo, useState } from 'react'

import { trackTextInputFocus } from '../state/focus'
import type {
  Account,
  AppSettings,
  NormalizedChatMessage,
  PlatformStatusInfo,
  WatchedChannel,
} from '@twirchat/shared/types'

import { platformColor, withAlpha } from '../theme'
import { useTheme } from '../theme-context'
import { aliasesStore } from '../state/app'
import { useStore } from '../state/create-store'
import { useAutocomplete, parseToken, replaceToken } from '../hooks/use-autocomplete'
import { AutocompletePopup } from './AutocompletePopup'
import { Icon, PlatformIcon } from './ui/Icon'
import { Text } from './ui/Text'
import { resolveUserCardCommand, type UserCardTarget } from '../../views/main/utils/chatCommands'
import {
  createChatMessageTargets,
  ownChatSendTargets,
} from '../../views/main/utils/chat-send-targets'
import { EmotePicker } from './EmotePicker'

export interface ChatInputProps {
  accounts: Account[]
  settings: AppSettings
  statuses: Partial<Record<import('@twirchat/shared/types').Platform, PlatformStatusInfo>>
  watchedChannel?: WatchedChannel | null
  watchedChannelStatus?: PlatformStatusInfo | null
  replyTarget?: NormalizedChatMessage | null
  messages?: NormalizedChatMessage[]
  onSend: (
    targets: { platform: string; channelLogin: string; text: string; replyToMessageId?: string }[],
  ) => void
  onSendWatched: (payload: { text: string; channelId: string; replyToMessageId?: string }) => void
  onOpenUserCard: (target: UserCardTarget) => void
  onCancelReply: () => void
}

function connectionStatusText(status: string | undefined, channel: string, error?: string): string {
  switch (status) {
    case 'connecting':
      return `Connecting to ${channel}…`
    case 'disconnected':
      return `${channel} disconnected`
    case 'error':
      return error || `Could not connect to ${channel}`
    default:
      return ''
  }
}

export function ChatInput(props: ChatInputProps) {
  const theme = useTheme()
  const aliases = useStore(aliasesStore)
  const [text, setText] = useState('')
  const [commandError, setCommandError] = useState('')
  const [emotePickerOpen, setEmotePickerOpen] = useState(false)

  const aliasMap = useMemo(() => {
    const map = new Map<import('@twirchat/shared/types').Platform, Map<string, string>>()
    for (const alias of aliases) {
      let inner = map.get(alias.platform)
      if (!inner) {
        inner = new Map()
        map.set(alias.platform, inner)
      }
      inner.set(alias.platformUserId, alias.alias)
    }
    return map
  }, [aliases])

  const autocomplete = useAutocomplete({
    text,
    setText: (next) => {
      setText(next)
      setCommandError('')
    },
    messages: props.messages ?? [],
    watchedChannel: props.watchedChannel,
    statuses: props.statuses,
    aliasMap,
  })

  // ── Target chips (home tab: one per own platform) ────────────────────────

  const connectedPlatforms = useMemo(() => {
    if (props.watchedChannel) return []
    return ownChatSendTargets(props.accounts).map((target) => {
      const exactStatus = Object.values(props.statuses).find(
        (info) =>
          info?.platform === target.platform &&
          info.channelLogin?.toLowerCase() === target.channelLogin.toLowerCase(),
      )
      return {
        platform: target.platform,
        channelLogin: target.channelLogin,
        status: exactStatus?.status ?? 'connected',
        mode: exactStatus?.mode ?? 'authenticated',
        error: exactStatus?.error,
      }
    })
  }, [props.accounts, props.statuses, props.watchedChannel])

  const homeConnectionStatuses = connectedPlatforms.filter((p) => p.status !== 'connected')
  const sendablePlatforms = connectedPlatforms.filter((p) => p.mode === 'authenticated')
  const hasAnything = props.watchedChannel ? true : connectedPlatforms.length > 0
  const isDisabled = props.watchedChannel
    ? props.watchedChannelStatus?.mode !== 'authenticated'
    : sendablePlatforms.length === 0

  const [enabledMap, setEnabledMap] = useState<Record<string, boolean>>({})
  const isEnabled = (platform: string): boolean => {
    const info = connectedPlatforms.find((p) => p.platform === platform)
    if (!info || info.mode !== 'authenticated') return false
    return enabledMap[platform] !== false
  }
  const toggle = (platform: string) => {
    const info = connectedPlatforms.find((p) => p.platform === platform)
    if (!info || info.mode !== 'authenticated') return
    setEnabledMap((current) => ({ ...current, [platform]: !isEnabled(platform) }))
  }

  const canSend = (() => {
    if (!text.trim()) return false
    if (props.watchedChannel) return !isDisabled
    return (
      createChatMessageTargets(sendablePlatforms, text, isEnabled, props.replyTarget).length > 0
    )
  })()

  function send() {
    const trimmed = text.trim()
    if (!trimmed) return

    const userCardCommand = resolveUserCardCommand(trimmed, props.messages ?? [], aliasMap)
    if (userCardCommand) {
      if (!userCardCommand.ok) {
        setCommandError(
          userCardCommand.error === 'missing-query'
            ? 'Usage: /user @nickname'
            : userCardCommand.error === 'ambiguous'
              ? 'Multiple users match that nickname.'
              : 'No user found for that nickname.',
        )
        return
      }
      props.onOpenUserCard(userCardCommand.target)
      setCommandError('')
      setText('')
      return
    }

    if (props.watchedChannel) {
      props.onSendWatched({
        text: trimmed,
        channelId: props.watchedChannel.id,
        replyToMessageId: props.replyTarget?.id,
      })
    } else {
      const targets = createChatMessageTargets(
        sendablePlatforms,
        trimmed,
        isEnabled,
        props.replyTarget,
      )
      if (targets.length === 0) return
      props.onSend(targets)
    }
    setCommandError('')
    setText('')
  }

  function placeholderText(): string {
    if (props.watchedChannel) {
      if (props.watchedChannelStatus?.mode !== 'authenticated') return 'Log in to send messages…'
      return `Message ${props.watchedChannel.displayName}…`
    }
    if (!hasAnything) return 'Connect a channel to send messages…'
    if (isDisabled) return 'Log in to send messages…'
    return 'Send a message… (Enter ↵ to send, Shift+Enter for newline)'
  }

  const currentChannelInfo = props.watchedChannel
    ? { platform: props.watchedChannel.platform, channelId: props.watchedChannel.channelSlug }
    : ownChatSendTargets(props.accounts)[0]
      ? {
          platform: ownChatSendTargets(props.accounts)[0]!.platform,
          channelId: ownChatSendTargets(props.accounts)[0]!.channelLogin,
        }
      : null

  return (
    <div
      style={{
        flexShrink: 0,
        borderTopWidth: 1,
        borderColor: theme.border,
        paddingTop: 8,
        paddingBottom: 10,
        paddingLeft: 12,
        paddingRight: 12,
        display: 'flex',
        flexDirection: 'column',
        gap: 7,
        backgroundColor: theme.surface,
      }}
    >
      {/* Reply bar */}
      {props.replyTarget ? (
        <div
          style={{
            display: 'flex',
            flexDirection: 'row',
            alignItems: 'center',
            gap: 8,
            backgroundColor: 'rgba(255, 255, 255, 0.04)',
            borderRadius: 8,
            paddingTop: 5,
            paddingBottom: 5,
            paddingLeft: 10,
            paddingRight: 10,
            borderLeftWidth: 2,
            borderColor: 'rgba(167, 139, 250, 0.5)',
          }}
        >
          <Text style={{ fontSize: 12, color: theme.text2, opacity: 0.7 }}>↩</Text>
          <Text
            style={{
              flexGrow: 1,
              fontSize: 12,
              color: theme.text2,
              overflow: 'hidden',
              textOverflow: 'ellipsis',
              whiteSpace: 'nowrap',
              minWidth: 0,
            }}
          >
            {`Replying to ${props.replyTarget.author.displayName}: ${
              props.replyTarget.text.length > 80
                ? `${props.replyTarget.text.slice(0, 80)}…`
                : props.replyTarget.text
            }`}
          </Text>
          <div
            testId="cancel-reply"
            onClick={props.onCancelReply}
            style={{
              width: 20,
              height: 20,
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              cursor: 'pointer',
              borderRadius: 4,
              flexShrink: 0,
              hover: { backgroundColor: 'rgba(255, 255, 255, 0.1)' },
            }}
          >
            <Icon name="close" size={16} color={theme.text2} />
          </div>
        </div>
      ) : null}

      {/* Connection state banners */}
      {props.watchedChannel &&
      props.watchedChannelStatus &&
      props.watchedChannelStatus.status !== 'connected' ? (
        <div
          style={{
            display: 'flex',
            flexDirection: 'row',
            alignItems: 'center',
            gap: 6,
            color: undefined,
          }}
        >
          <div
            style={{
              width: 6,
              height: 6,
              borderRadius: 3,
              backgroundColor:
                props.watchedChannelStatus.status === 'connecting'
                  ? '#fbbf24'
                  : props.watchedChannelStatus.status === 'error'
                    ? '#fca5a5'
                    : theme.text2,
            }}
          />
          <Text
            style={{
              fontSize: 12,
              color:
                props.watchedChannelStatus.status === 'connecting'
                  ? '#fbbf24'
                  : props.watchedChannelStatus.status === 'error'
                    ? '#fca5a5'
                    : theme.text2,
            }}
          >
            {connectionStatusText(
              props.watchedChannelStatus.status,
              props.watchedChannel.displayName,
              props.watchedChannelStatus.error,
            )}
          </Text>
        </div>
      ) : null}

      {!props.watchedChannel && homeConnectionStatuses.length > 0 ? (
        <div
          style={{
            display: 'flex',
            flexDirection: 'row',
            flexWrap: 'wrap',
            gap: 10,
          }}
        >
          {homeConnectionStatuses.map((p) => (
            <div
              key={p.platform}
              style={{
                display: 'flex',
                flexDirection: 'row',
                alignItems: 'center',
                gap: 6,
              }}
            >
              <div
                style={{
                  width: 6,
                  height: 6,
                  borderRadius: 3,
                  backgroundColor: p.status === 'connecting' ? '#fbbf24' : '#fca5a5',
                }}
              />
              <Text
                style={{
                  fontSize: 12,
                  color: p.status === 'connecting' ? '#fbbf24' : '#fca5a5',
                }}
              >
                {connectionStatusText(p.status, p.channelLogin, p.error)}
              </Text>
            </div>
          ))}
        </div>
      ) : null}

      {/* Target chips */}
      {props.settings.showChannelLabel && props.watchedChannel ? (
        <div style={{ display: 'flex', flexDirection: 'row', gap: 6, flexWrap: 'wrap' }}>
          <TargetChip
            platform={props.watchedChannel.platform}
            label={props.watchedChannel.displayName}
            active={props.watchedChannelStatus?.mode === 'authenticated'}
            anonymous={props.watchedChannelStatus?.mode !== 'authenticated'}
          />
        </div>
      ) : null}

      {props.settings.showChannelLabel && !props.watchedChannel && connectedPlatforms.length > 0 ? (
        <div style={{ display: 'flex', flexDirection: 'row', gap: 6, flexWrap: 'wrap' }}>
          {connectedPlatforms.map((p) => (
            <TargetChip
              key={p.platform}
              platform={p.platform}
              label={p.channelLogin}
              active={isEnabled(p.platform)}
              anonymous={p.mode !== 'authenticated'}
              onClick={() => toggle(p.platform)}
            />
          ))}
        </div>
      ) : null}

      {/* Autocomplete + input row */}
      <div style={{ position: 'relative', display: 'flex', flexDirection: 'column' }}>
        {autocomplete.isOpen ? (
          <AutocompletePopup
            suggestions={autocomplete.suggestions}
            selectedIndex={autocomplete.selectedIndex}
            mode={autocomplete.mode}
            onSelect={autocomplete.selectSuggestion}
          />
        ) : null}

        {commandError ? (
          <Text style={{ fontSize: 12, color: '#fca5a5', paddingLeft: 2, paddingBottom: 2 }}>
            {commandError}
          </Text>
        ) : null}

        <div
          style={{
            display: 'flex',
            flexDirection: 'row',
            alignItems: 'flex-end',
            gap: 8,
          }}
        >
          <div
            style={{
              flexGrow: 1,
              minWidth: 0,
              backgroundColor: theme.surface2,
              borderWidth: 1,
              borderColor: theme.border,
              borderRadius: 10,
              paddingLeft: 12,
              paddingRight: 12,
              paddingTop: 8,
              paddingBottom: 8,
            }}
          >
            <textarea
              testId="chat-input"
              value={text}
              placeholder={placeholderText()}
              minRows={1}
              maxRows={5}
              autoFocus
              onChange={(event) => {
                setText(event.value ?? '')
                setCommandError('')
              }}
              onFocus={() => trackTextInputFocus(true)}
              onBlur={() => trackTextInputFocus(false)}
              onSubmit={autocomplete.isOpen ? undefined : send}
              onKeyDown={(event) => {
                if (!autocomplete.isOpen) return
                if (event.key === 'up') {
                  autocomplete.moveUp()
                } else if (event.key === 'down') {
                  autocomplete.moveDown()
                } else if (event.key === 'enter' || event.key === 'tab') {
                  autocomplete.selectSuggestion(autocomplete.selectedIndex)
                } else if (event.key === 'escape') {
                  autocomplete.close()
                }
              }}
              theme={{ caret: '#a78bfa' }}
              style={{
                width: '100%',
                fontSize: 13,
                color: theme.text,
                lineHeight: 20,
                opacity: isDisabled ? 0.4 : 1,
              }}
            />
          </div>

          <div
            testId="emote-button"
            onClick={() => {
              if (!isDisabled) setEmotePickerOpen((open) => !open)
            }}
            style={{
              flexShrink: 0,
              width: 36,
              height: 36,
              borderRadius: 8,
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              cursor: isDisabled ? 'default' : 'pointer',
              opacity: isDisabled ? 0.3 : 1,
              backgroundColor: emotePickerOpen ? 'rgba(167, 139, 250, 0.15)' : undefined,
              hover: { backgroundColor: 'rgba(255, 255, 255, 0.08)' },
            }}
          >
            <Icon name="smile" size={16} color={emotePickerOpen ? '#a78bfa' : theme.text2} />
          </div>

          <div
            testId="send-button"
            onClick={() => {
              if (canSend) send()
            }}
            style={{
              flexShrink: 0,
              width: 36,
              height: 36,
              borderRadius: 10,
              backgroundColor: '#7c3aed',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              cursor: canSend ? 'pointer' : 'default',
              opacity: canSend ? 1 : 0.35,
              hover: { backgroundColor: canSend ? '#6d28d9' : '#7c3aed' },
            }}
          >
            <Icon name="send" size={16} color="#ffffff" />
          </div>
        </div>

        {/* Emote picker overlay */}
        {emotePickerOpen && currentChannelInfo ? (
          <EmotePicker
            platform={currentChannelInfo.platform}
            channelId={currentChannelInfo.channelId}
            useSessionCache={props.settings.emoteSessionCache}
            onSelect={(alias) => {
              // GPUIX's native textarea does not expose the caret position,
              // so emotes append at the end (the Vue build inserted at caret).
              setText((current) => {
                const token = parseToken(current)
                if (token.mode === 'emote') {
                  return replaceToken(current, {
                    type: 'emote',
                    label: alias,
                    imageUrl: '',
                    animated: false,
                  })
                }
                return `${current}${current.endsWith(' ') || current === '' ? '' : ' '}${alias} `
              })
              setEmotePickerOpen(false)
            }}
            onClose={() => setEmotePickerOpen(false)}
          />
        ) : null}
      </div>
    </div>
  )
}

function TargetChip({
  platform,
  label,
  active,
  anonymous,
  onClick,
}: {
  platform: string
  label: string
  active: boolean
  anonymous: boolean
  onClick?: () => void
}) {
  const color = platformColor(platform)
  const [hovered, setHovered] = useState(false)
  const effectiveHover = hovered && !anonymous && !active

  return (
    <div
      onClick={anonymous ? undefined : onClick}
      onMouseEnter={() => setHovered(true)}
      onMouseLeave={() => setHovered(false)}
      style={{
        display: 'flex',
        flexDirection: 'row',
        alignItems: 'center',
        gap: 5,
        paddingTop: 3,
        paddingBottom: 3,
        paddingLeft: 7,
        paddingRight: 9,
        borderRadius: 20,
        borderWidth: 1,
        borderColor: active
          ? withAlpha(color, 0.45)
          : effectiveHover
            ? withAlpha(color, 0.55)
            : 'rgba(255, 255, 255, 0.1)',
        backgroundColor: active
          ? withAlpha(color, 0.15)
          : effectiveHover
            ? withAlpha(color, 0.2)
            : 'rgba(255, 255, 255, 0.04)',
        cursor: anonymous ? 'default' : 'pointer',
        opacity: anonymous ? 0.35 : !active && !hovered ? 0.4 : 1,
        userSelect: 'none',
      }}
    >
      <PlatformIcon
        platform={platform}
        size={13}
        color={active || effectiveHover ? color : '#8b8b99'}
      />
      <Text
        style={{
          fontSize: 12,
          fontWeight: 500,
          color: active || effectiveHover ? color : '#8b8b99',
          maxWidth: 80,
          overflow: 'hidden',
          textOverflow: 'ellipsis',
          whiteSpace: 'nowrap',
        }}
      >
        {label}
      </Text>
      {anonymous ? <Icon name="lock" size={10} color="#8b8b99" /> : null}
    </div>
  )
}
