// packages/desktop/src/views/main/components/ChatMessage.vue
<script setup lang="ts">
import { computed, ref } from 'vue'
import type { Account, NormalizedChatMessage } from '@twirchat/shared/types'
import EmoteTooltip from './EmoteTooltip.vue'
import { platformColor } from '../../shared/utils/platform'
import TwitchIcon from '../../../assets/icons/platforms/twitch.svg'
import YoutubeIcon from '../../../assets/icons/platforms/youtube.svg'
import KickIcon from '../../../assets/icons/platforms/kick.svg'
import UserContextMenu from './UserContextMenu.vue'
import { useMessageParsing } from '../composables/useMessageParsing'
import { resolveBadgeImage } from '../utils/badge-image'
import { chatMessageStyle } from '../utils/chat-message-style'
import { openExternalUrl } from '../services/external-url'

const props = defineProps<{
  message: NormalizedChatMessage
  channelSlug?: string
  showPlatformColorStripe?: boolean
  showPlatformIcon?: boolean
  showTimestamp?: boolean
  showAvatar?: boolean
  showBadges?: boolean
  fontSize?: number
  chatTheme?: 'modern' | 'compact'
  accounts?: Account[]
  selfPingEnabled?: boolean
  selfPingColor?: string
  alias?: string
}>()

const emit = defineEmits<{
  reply: [message: NormalizedChatMessage]
}>()

const { messageParts, processText } = useMessageParsing(props.message)

function onReply() {
  emit('reply', props.message)
}

const isSystemMessage = computed(() => props.message.type === 'system')

const isSelfPing = computed((): boolean => {
  if (!props.selfPingEnabled || !props.accounts?.length) return false
  const myAccount = props.accounts.find((a) => a.platform === props.message.platform)
  if (!myAccount) return false
  const lower = props.message.text.toLowerCase()
  const username = myAccount.username.toLowerCase()
  const displayName = myAccount.displayName.toLowerCase()
  return lower.includes(`@${username}`) || lower.includes(`@${displayName}`)
})

const selfPingStyle = computed(() =>
  isSelfPing.value && props.selfPingColor ? { background: props.selfPingColor } : {},
)

const systemAction = computed<'added' | 'removed' | 'renamed'>(() => {
  const t = props.message.text
  if (t.includes(' added ')) {
    return 'added'
  }
  if (t.includes(' removed ')) {
    return 'removed'
  }
  return 'renamed'
})

const brokenBadges = ref(new Set<string>())

function onBadgeError(id: string): void {
  brokenBadges.value = new Set([...brokenBadges.value, id])
}

function badgeImage(imageUrl: string | undefined): string | undefined {
  return resolveBadgeImage(imageUrl)
}

function isSvgBadge(imageUrl: string | undefined): boolean {
  return badgeImage(imageUrl)?.startsWith('<svg') === true
}

function formatTime(ts: Date): string {
  return new Date(ts).toLocaleTimeString(undefined, {
    hour: '2-digit',
    minute: '2-digit',
    second: '2-digit',
    hour12: false,
  })
}

function initials(name: string): string {
  return name.slice(0, 1).toUpperCase()
}

function onMsgClick(e: MouseEvent): void {
  const target = e.target as HTMLElement
  const anchor = target.closest<HTMLAnchorElement>('a.msg-link')
  if (!anchor) {
    return
  }
  e.preventDefault()
  const url = anchor.dataset.href
  if (url) {
    void openExternalUrl(url).catch((error: unknown) => {
      console.error('Failed to open external URL', error)
    })
  }
}

// Copy functionality
const copySuccess = ref(false)

function copyMessage(): void {
  navigator.clipboard.writeText(props.message.text).then(() => {
    copySuccess.value = true
    setTimeout(() => {
      copySuccess.value = false
    }, 1500)
  })
}

/**
 * SVG badges from Kick/7TV embed linearGradient/clipPath with global IDs like
 * "paint0_linear_817_50667". When multiple messages in the virtual list render
 * the same badge, duplicate IDs cause browsers to reuse the first definition,
 * making subsequent badges invisible. We scope each SVG by replacing those IDs
 * with a unique prefix tied to the message+badge composite key.
 */
function scopeBadgeSvg(svgString: string, badgeId: string): string {
  const scope = `${props.message.id}-${badgeId}`.replace(/[^a-zA-Z0-9-]/g, '_')
  // Replace id="..." and url(#...) and xlink:href="#..." occurrences
  return svgString
    .replace(/\bid="([^"]+)"/g, `id="${scope}_$1"`)
    .replace(/url\(#([^)]+)\)/g, `url(#${scope}_$1)`)
    .replace(/xlink:href="#([^"]+)"/g, `xlink:href="#${scope}_$1"`)
}
</script>

<template>
  <!-- ── SYSTEM MESSAGE ────────────────────────────────────── -->
  <!-- NOTE: System message check MUST come before compact theme check.
       System message authors have no `badges` field, so the compact
       branch would crash with "badges.length of undefined". -->
  <div
    v-if="isSystemMessage"
    class="msg msg-system"
    :class="[`platform-${message.platform}`, `action-${systemAction}`]"
    :style="chatMessageStyle(props.fontSize)"
    @click="onMsgClick"
  >
    <!-- Action icon: +/−/~ colored pill -->
    <div class="system-action-icon" :class="`action-icon-${systemAction}`">
      {{ systemAction === 'added' ? '+' : systemAction === 'removed' ? '−' : '~' }}
    </div>

    <span class="msg-text system-text">
      <template v-for="(part, index) in messageParts" :key="index">
        <EmoteTooltip v-if="part.type === 'emote' && part.emote" :emote="part.emote">
          <img
            class="emote system-emote"
            :src="part.emote.imageUrl"
            :alt="part.emote.name"
            :title="part.emote.name"
          />
        </EmoteTooltip>
        <span v-else-if="part.type === 'text' && part.content" v-html="processText(part.content)" />
      </template>
    </span>

    <span v-if="props.showTimestamp" class="timestamp system-timestamp">{{
      formatTime(message.timestamp)
    }}</span>
  </div>

  <!-- ── COMPACT (single-line) ─────────────────────────────── -->
  <div
    v-else-if="props.chatTheme === 'compact'"
    class="msg msg-compact"
    :class="[
      `platform-${message.platform}`,
      {
        'delivery-pending': message.delivery?.state === 'pending',
        'delivery-failed': message.delivery?.state === 'failed',
        'self-ping': isSelfPing,
      },
    ]"
    :style="{ ...chatMessageStyle(props.fontSize), ...selfPingStyle }"
    @click="onMsgClick"
  >
    <span
      v-if="props.showPlatformColorStripe !== false"
      class="platform-stripe"
      :style="{ background: platformColor(message.platform) }"
    />

    <!-- Reply preview: sits above the message row as its own line -->
    <div v-if="message.reply" class="reply-preview compact-reply">
      <span class="reply-icon">↩</span>
      <span class="reply-author">{{ message.reply.parentAuthor.displayName }}</span
      >:
      <span class="reply-text">{{
        message.reply.parentMessageText.length > 80
          ? message.reply.parentMessageText.slice(0, 80) + '…'
          : message.reply.parentMessageText
      }}</span>
    </div>

    <!--
      Message row: inline content, wraps naturally.
      Buttons live outside this row as absolute children of .msg-compact.
    -->
    <div class="msg-compact-row">
      <!-- Timestamp -->
      <span v-if="props.showTimestamp" class="timestamp compact-time">{{
        formatTime(message.timestamp)
      }}</span>

      <!-- Platform icon -->
      <span
        v-if="props.showPlatformIcon"
        class="platform-icon compact-platform-icon"
        :title="message.platform"
      >
        <component
          :is="
            message.platform === 'twitch'
              ? TwitchIcon
              : message.platform === 'youtube'
                ? YoutubeIcon
                : KickIcon
          "
          :style="{ color: platformColor(message.platform) }"
          width="12"
          height="12"
        />
      </span>

      <!--
        Badges, author, colon and text are all inline.
        Wrapping: second line starts at the left edge of the container
        (no text-indent), which is the standard Twitch behaviour.
      -->
      <span
        v-if="props.showBadges !== false && message.author.badges.length"
        class="badges compact-badges"
      >
        <span
          v-for="badge in message.author.badges"
          :key="badge.id"
          class="badge"
          :title="badge.type"
        >
          <span
            v-if="isSvgBadge(badge.imageUrl)"
            class="badge-svg"
            v-html="scopeBadgeSvg(badgeImage(badge.imageUrl) ?? '', badge.id)"
          />
          <img
            v-else-if="badgeImage(badge.imageUrl) && !brokenBadges.has(badge.id)"
            :src="badgeImage(badge.imageUrl)"
            :alt="badge.text"
            @error="onBadgeError(badge.id)"
          />
          <span v-else class="badge-text">{{ badge.text }}</span>
        </span></span
      ><template v-if="isSystemMessage"
        ><span
          class="author"
          :style="message.author.color ? { color: message.author.color } : {}"
          >{{ message.author.displayName }}</span
        ></template
      ><UserContextMenu
        v-else
        :platform="message.platform"
        :platform-user-id="message.author.id"
        :channel-id="message.channelId"
        :channel-slug="props.channelSlug"
        :display-name="message.author.displayName"
        :username="message.author.username"
        :avatar-url="message.author.avatarUrl"
        :current-alias="props.alias"
      >
        <span class="author" :style="message.author.color ? { color: message.author.color } : {}">{{
          props.alias ?? message.author.displayName
        }}</span> </UserContextMenu
      ><span class="compact-sep">: </span
      ><span class="msg-text" :class="{ italic: message.type === 'action' }">
        <template v-for="(part, index) in messageParts" :key="index">
          <EmoteTooltip v-if="part.type === 'emote' && part.emote" :emote="part.emote">
            <img
              class="emote"
              :src="part.emote.imageUrl"
              :alt="part.emote.name"
              :title="part.emote.name"
            />
          </EmoteTooltip>
          <span
            v-else-if="part.type === 'text' && part.content"
            v-html="processText(part.content)"
          />
        </template>
      </span>
      <span
        v-if="message.delivery?.state === 'failed'"
        class="delivery-error"
        :title="message.delivery.error"
      >
        Not sent: {{ message.delivery.error }}
      </span>
    </div>

    <div style="position: absolute; right: 0; top: 0">
      <button class="reply-btn compact-reply-btn" title="Reply to message" @click.stop="onReply">
        <svg
          xmlns="http://www.w3.org/2000/svg"
          width="14"
          height="14"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          stroke-width="2"
          stroke-linecap="round"
          stroke-linejoin="round"
        >
          <polyline points="9 17 4 12 9 7"></polyline>
          <path d="M20 18v-2a4 4 0 0 0-4-4H4"></path>
        </svg>
      </button>

      <!-- Copy button: always in DOM, absolute on .msg-compact, opacity:0 → 1 on hover -->
      <button
        class="copy-btn compact-copy-btn"
        :class="{ success: copySuccess }"
        title="Copy message"
        @click.stop="copyMessage"
      >
        <svg
          v-if="!copySuccess"
          xmlns="http://www.w3.org/2000/svg"
          width="14"
          height="14"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          stroke-width="2"
          stroke-linecap="round"
          stroke-linejoin="round"
        >
          <rect x="9" y="9" width="13" height="13" rx="2" ry="2"></rect>
          <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path>
        </svg>
        <svg
          v-else
          xmlns="http://www.w3.org/2000/svg"
          width="14"
          height="14"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          stroke-width="2"
          stroke-linecap="round"
          stroke-linejoin="round"
        >
          <polyline points="20 6 9 17 4 12"></polyline>
        </svg>
      </button>
    </div>
  </div>

  <div
    v-else
    class="msg"
    :class="[
      `platform-${message.platform}`,
      message.type === 'action' ? 'is-action' : '',
      {
        'delivery-pending': message.delivery?.state === 'pending',
        'delivery-failed': message.delivery?.state === 'failed',
        'self-ping': isSelfPing,
      },
    ]"
    :style="{ ...chatMessageStyle(props.fontSize), ...selfPingStyle }"
    @click="onMsgClick"
  >
    <!-- Platform colour stripe -->
    <span
      v-if="props.showPlatformColorStripe !== false"
      class="platform-stripe"
      :style="{ background: platformColor(message.platform) }"
      :title="message.platform"
    />

    <!-- Platform icon -->
    <span v-if="props.showPlatformIcon" class="platform-icon" :title="message.platform">
      <component
        :is="
          message.platform === 'twitch'
            ? TwitchIcon
            : message.platform === 'youtube'
              ? YoutubeIcon
              : KickIcon
        "
        :style="{ color: platformColor(message.platform) }"
        width="12"
        height="12"
      />
    </span>

    <!-- Avatar -->
    <div v-if="props.showAvatar !== false" class="avatar-wrap">
      <img
        v-if="message.author.avatarUrl"
        class="avatar"
        :src="message.author.avatarUrl"
        :alt="message.author.displayName"
      />
      <div
        v-else
        class="avatar avatar-fallback"
        :style="{ background: message.author.color ?? '#444' }"
      >
        {{ initials(message.author.displayName) }}
      </div>
    </div>

    <!-- Body -->
    <div class="msg-body">
      <!-- Reply Preview -->
      <div v-if="message.reply" class="reply-preview">
        <span class="reply-icon">↩</span>
        <span class="reply-author">{{ message.reply.parentAuthor.displayName }}</span
        >:
        <span class="reply-text">{{
          message.reply.parentMessageText.length > 80
            ? message.reply.parentMessageText.slice(0, 80) + '…'
            : message.reply.parentMessageText
        }}</span>
      </div>

      <div class="msg-meta">
        <!-- Badges -->
        <span v-if="props.showBadges !== false && message.author.badges.length" class="badges">
          <span
            v-for="badge in message.author.badges"
            :key="badge.id"
            class="badge"
            :title="badge.type"
          >
            <span
              v-if="isSvgBadge(badge.imageUrl)"
              class="badge-svg"
              v-html="scopeBadgeSvg(badgeImage(badge.imageUrl) ?? '', badge.id)"
            />
            <img
              v-else-if="badgeImage(badge.imageUrl) && !brokenBadges.has(badge.id)"
              :src="badgeImage(badge.imageUrl)"
              :alt="badge.text"
              @error="onBadgeError(badge.id)"
            />
            <span v-else class="badge-text">{{ badge.text }}</span>
          </span>
        </span>

        <template v-if="isSystemMessage">
          <span
            class="author"
            :style="message.author.color ? { color: message.author.color } : {}"
            >{{ message.author.displayName }}</span
          >
        </template>
        <UserContextMenu
          v-else
          :platform="message.platform"
          :platform-user-id="message.author.id"
          :channel-id="message.channelId"
          :channel-slug="props.channelSlug"
          :display-name="message.author.displayName"
          :username="message.author.username"
          :avatar-url="message.author.avatarUrl"
          :current-alias="props.alias"
        >
          <span
            class="author"
            :style="message.author.color ? { color: message.author.color } : {}"
            >{{ props.alias ?? message.author.displayName }}</span
          >
        </UserContextMenu>

        <span v-if="props.showTimestamp" class="timestamp">{{
          formatTime(message.timestamp)
        }}</span>
      </div>

      <!-- Message text -->
      <span class="msg-text" :class="{ italic: message.type === 'action' }">
        <template v-for="(part, index) in messageParts" :key="index">
          <EmoteTooltip v-if="part.type === 'emote' && part.emote" :emote="part.emote">
            <img
              class="emote"
              :src="part.emote.imageUrl"
              :alt="part.emote.name"
              :title="part.emote.name"
            />
          </EmoteTooltip>
          <span
            v-else-if="part.type === 'text' && part.content"
            v-html="processText(part.content)"
          />
        </template>
      </span>
      <span
        v-if="message.delivery?.state === 'failed'"
        class="delivery-error"
        :title="message.delivery.error"
      >
        Not sent: {{ message.delivery.error }}
      </span>
    </div>

    <!-- Reply button: always in DOM, shown via CSS hover on .msg -->
    <button class="reply-btn" title="Reply to message" @click.stop="onReply">
      <svg
        xmlns="http://www.w3.org/2000/svg"
        width="14"
        height="14"
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        stroke-width="2"
        stroke-linecap="round"
        stroke-linejoin="round"
      >
        <polyline points="9 17 4 12 9 7"></polyline>
        <path d="M20 18v-2a4 4 0 0 0-4-4H4"></path>
      </svg>
    </button>

    <!-- Copy button: always in DOM, shown via CSS hover on .msg -->
    <button
      class="copy-btn"
      :class="{ success: copySuccess }"
      title="Copy message"
      @click.stop="copyMessage"
    >
      <svg
        v-if="!copySuccess"
        xmlns="http://www.w3.org/2000/svg"
        width="14"
        height="14"
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        stroke-width="2"
        stroke-linecap="round"
        stroke-linejoin="round"
      >
        <rect x="9" y="9" width="13" height="13" rx="2" ry="2"></rect>
        <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path>
      </svg>
      <svg
        v-else
        xmlns="http://www.w3.org/2000/svg"
        width="14"
        height="14"
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        stroke-width="2"
        stroke-linecap="round"
        stroke-linejoin="round"
      >
        <polyline points="20 6 9 17 4 12"></polyline>
      </svg>
    </button>
  </div>
</template>

<style scoped>
.msg {
  display: flex;
  align-items: flex-start;
  gap: 10px;
  padding: 6px 14px;
  font-size: var(--font-size, 14px);
  line-height: 1.45;
  word-break: break-word;
  transition: background 0.1s;
  position: relative;
}

.msg:hover {
  background: rgba(255, 255, 255, 0.025);
}

.msg.self-ping:hover {
  filter: brightness(1.08);
}

.delivery-pending {
  opacity: 0.52;
}

.delivery-failed {
  border-left: 2px solid #ef4444;
  background: rgba(239, 68, 68, 0.08);
}

.delivery-error {
  display: block;
  color: #f87171;
  font-size: 0.82em;
  margin-top: 2px;
}

/* Platform stripe on left edge */
.platform-stripe {
  position: absolute;
  left: 0;
  top: 6px;
  bottom: 6px;
  width: 2px;
  border-radius: 2px;
  opacity: 0.7;
}

/* Platform icon (inline SVG, coloured) */
.platform-icon {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: var(--platform-icon-size, 12px);
  height: var(--platform-icon-size, 12px);
  flex-shrink: 0;
  opacity: 0.85;
  line-height: 1;
}

.platform-icon :deep(svg) {
  width: 100%;
  height: 100%;
}

.msg-compact .platform-icon {
  margin-right: 1px;
  align-self: center;
}

.msg:not(.msg-compact) .platform-icon {
  margin-top: 6px;
}

.compact-time {
  flex-shrink: 0;
  font-size: 10px;
  color: var(--c-text-2, #8b8b99);
  opacity: 0.8;
}

.avatar-wrap {
  flex-shrink: 0;
  margin-top: 1px;
}

.avatar {
  width: 28px;
  height: 28px;
  border-radius: 50%;
  object-fit: cover;
  display: block;
}

.avatar-fallback {
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 11px;
  font-weight: 700;
  color: rgba(255, 255, 255, 0.9);
}

.msg-body {
  flex: 1;
  min-width: 0;
  display: flex;
  flex-direction: column;
  gap: 2px;
}

.msg-meta {
  display: flex;
  align-items: center;
  gap: 5px;
  flex-wrap: wrap;
}

.badges {
  display: flex;
  align-items: center;
  gap: 3px;
  line-height: 1;
}

.badge {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  height: var(--badge-size, 16px);
  line-height: 1;
  vertical-align: middle;
}

.badge img {
  display: block;
  width: auto;
  max-width: 4em;
  height: var(--badge-size, 16px);
  object-fit: contain;
}

.badge-svg {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: var(--badge-size, 16px);
  height: var(--badge-size, 16px);
}

.badge-svg :deep(svg) {
  width: 100%;
  height: 100%;
}

.badge-text {
  display: inline-flex;
  align-items: center;
  min-height: var(--badge-size, 16px);
  font-size: calc(var(--badge-size, 16px) - 4px);
  padding: 0.08em 0.35em;
  background: rgba(255, 255, 255, 0.1);
  border-radius: 3px;
  line-height: 1;
}

.author {
  font-weight: 700;
  font-size: 0.9em;
  cursor: pointer;
}

.timestamp {
  font-size: 10px;
  color: var(--c-text-2, #8b8b99);
  margin-left: 2px;
}

.msg-text {
  color: var(--c-text, #e2e2e8);
}

:deep(.msg-link) {
  color: #a78bfa;
  text-decoration: underline;
  text-underline-offset: 2px;
  cursor: pointer;
  word-break: break-all;
}

:deep(.msg-link:hover) {
  color: #c4b5fd;
}

.msg-text.italic {
  font-style: italic;
  opacity: 0.85;
}

.emote {
  height: 24px;
  width: auto;
  max-width: 72px;
  vertical-align: middle;
  display: inline-block;
  object-fit: contain;
  cursor: pointer;
}

:deep(.mention) {
  cursor: pointer;
}

:deep(.mention:hover) {
  text-decoration: underline;
  text-underline-offset: 2px;
}

/* Reply Preview */
.reply-preview {
  font-size: 0.8em;
  color: var(--c-text-2, #8b8b99);
  display: flex;
  align-items: center;
  gap: 4px;
  overflow: hidden;
  white-space: nowrap;
}

.reply-author {
  color: var(--c-text, #e2e2e8);
  font-weight: 600;
}

.reply-text {
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
  max-width: 80ch;
}

.reply-icon {
  opacity: 0.7;
  font-size: 1.1em;
}

/* Reply button */
.reply-btn {
  position: absolute;
  right: 34px;
  top: 50%;
  transform: translateY(-50%);
  background: rgba(255, 255, 255, 0.1);
  border: none;
  border-radius: 4px;
  padding: 4px 6px;
  cursor: pointer;
  color: var(--c-text-2, #8b8b99);
  opacity: 0;
  transition:
    opacity 0.15s,
    background 0.15s,
    color 0.15s;
  display: flex;
  align-items: center;
  justify-content: center;
}

.msg:hover .reply-btn,
.msg-compact:hover .reply-btn {
  opacity: 1;
}

.reply-btn:hover {
  background: rgba(255, 255, 255, 0.15);
  color: var(--c-text, #e2e2e8);
}

/* Copy button */
.copy-btn {
  position: absolute;
  right: 8px;
  top: 50%;
  transform: translateY(-50%);
  background: rgba(255, 255, 255, 0.1);
  border: none;
  border-radius: 4px;
  padding: 4px 6px;
  cursor: pointer;
  color: var(--c-text-2, #8b8b99);
  opacity: 0;
  transition:
    opacity 0.15s,
    background 0.15s,
    color 0.15s;
  display: flex;
  align-items: center;
  justify-content: center;
}

.msg:hover .copy-btn,
.msg-compact:hover .copy-btn {
  opacity: 1;
}

.copy-btn:hover {
  background: rgba(255, 255, 255, 0.15);
  color: var(--c-text, #e2e2e8);
}

.copy-btn.success {
  background: rgba(74, 222, 128, 0.2);
  color: #4ade80;
  opacity: 1;
}

/* ── Compact (single-line) ──────────────────────────────── */
.msg-compact {
  display: flex;
  flex-direction: column;
  padding: 2px 14px;
  font-size: var(--font-size, 14px);
  line-height: 1.5;
  position: relative;
  gap: 2px;
}
.msg-compact:hover {
  background: rgba(255, 255, 255, 0.025);
}
.msg-compact .platform-stripe {
  position: absolute;
  left: 0;
  top: 2px;
  bottom: 2px;
  width: 2px;
  border-radius: 2px;
  opacity: 0.7;
}

/* Reply preview row — sits above the message row */
.compact-reply {
  width: 100%;
  margin-bottom: 0;
}

/*
  The message row uses display:block so all inline children wrap naturally.
  This is the key to Twitch-style line wrapping: when text overflows, the
  next line starts at the left edge of the container — not under the author.
*/
.msg-compact-row {
  display: block;
  word-break: break-word;
  overflow-wrap: break-word;
  line-height: 1.5;
  position: relative;
}

/* Compact-specific button overrides: position relative to the text row */
.compact-reply-btn {
  top: 50%;
  bottom: auto;
  right: 30px;
  transform: translateY(-50%);
}

.compact-copy-btn {
  top: 50%;
  bottom: auto;
  right: 2px;
  transform: translateY(-50%);
}

.msg-compact .compact-platform-icon {
  margin-right: 3px;
  line-height: 1;
  display: inline-flex;
  align-items: center;
  vertical-align: middle;
}

.msg-compact .compact-time {
  margin-right: 4px;
  margin-left: 0;
}

.msg-compact .author {
  font-weight: 700;
  font-size: 0.9em;
}

.compact-sep {
  color: var(--c-text-2, #8b8b99);
}

.msg-compact .msg-text {
  overflow-wrap: break-word;
  word-break: break-word;
}

/* Badges in compact mode: inline-flex so they sit on the text baseline */
.compact-badges {
  display: inline-flex;
  align-items: center;
  gap: 3px;
  line-height: 1;
  vertical-align: middle;
  margin-right: 3px;
}

/* ── System Messages ────────────────────────────────────── */
.msg-system {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 3px 14px;
  font-size: var(--font-size, 14px);
  line-height: 1.45;
  border-left: 2px solid transparent;
  position: relative;
}

/* Action-based colour theming */
.msg-system.action-added {
  background: rgba(74, 222, 128, 0.04);
  border-left-color: #4ade80;
}
.msg-system.action-added:hover {
  background: rgba(74, 222, 128, 0.07);
}

.msg-system.action-removed {
  background: rgba(255, 80, 80, 0.05);
  border-left-color: #ff5050;
}
.msg-system.action-removed:hover {
  background: rgba(255, 80, 80, 0.09);
}

.msg-system.action-renamed {
  background: rgba(129, 140, 248, 0.06);
  border-left-color: #818cf8;
}
.msg-system.action-renamed:hover {
  background: rgba(129, 140, 248, 0.1);
}

/* Action icon: small coloured circle with +/−/~ */
.system-action-icon {
  width: 17px;
  height: 17px;
  border-radius: 50%;
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 12px;
  font-weight: 800;
  flex-shrink: 0;
  line-height: 1;
  user-select: none;
}
.action-icon-added {
  background: rgba(74, 222, 128, 0.15);
  color: #4ade80;
}
.action-icon-removed {
  background: rgba(255, 80, 80, 0.18);
  color: #ff6060;
}
.action-icon-renamed {
  background: rgba(129, 140, 248, 0.18);
  color: #818cf8;
}

.system-text {
  color: var(--c-text-2, #8b8b99);
  font-size: 0.88em;
  flex: 1;
  min-width: 0;
}

.system-emote {
  height: 20px;
  vertical-align: middle;
}

.system-timestamp {
  font-size: 10px;
  color: var(--c-text-2, #8b8b99);
  flex-shrink: 0;
  margin-left: auto;
  opacity: 0.7;
}
</style>

// packages/desktop/src/gpuix/components/ChatMessage.tsx
/**
 * One chat message row — port of ChatMessage.vue with its three layouts
 * (modern / compact / system) plus hover actions, delivery states,
 * moderation outcomes and the self-ping highlight.
 *
 * GPUIX deltas: no italics (action messages use opacity only), no
 * strikethrough (tombstones dim instead), hover actions are JS-state driven
 * because parent `hover` styles do not reach children.
 */

import { memo, useEffect, useState } from 'react'
import type { Account, NormalizedChatMessage } from '@twirchat/shared/types'

import { useBackend } from '../backend/context'
import { avatarRevisionStore, avatarUrlFor, ensureAvatar } from '../state/caches'
import { useStore } from '../state/create-store'
import type { ResolvedModerationOutcome } from '../state/app'
import { platformColor, semantic } from '../theme'
import { useFont, useTheme } from '../theme-context'
import { resolveBadgeImage } from '../../views/main/utils/badge-image'
import type { UserCardTarget } from '../../views/main/utils/chatCommands'
import { Icon, PlatformIcon } from './ui/Icon'
import { RemoteImage } from './ui/RemoteImage'
import { Text } from './ui/Text'
import { MessageText, MessageTokens } from './MessageText'

const DEFAULT_FONT_SIZE = 14

function badgeSize(fontSize: number): number {
  return Math.max(12, Math.round(fontSize * 1.15))
}

function platformIconSize(fontSize: number): number {
  return Math.max(9, Math.round(fontSize * 0.85))
}

export function formatMessageTime(ts: Date): string {
  return new Date(ts).toLocaleTimeString(undefined, {
    hour: '2-digit',
    minute: '2-digit',
    second: '2-digit',
    hour12: false,
  })
}

// ── Avatar (fallback circle with the image layered on top once decoded) ─────

export function Avatar({ message, size }: { message: NormalizedChatMessage; size: number }) {
  useStore(avatarRevisionStore)
  useEffect(() => ensureAvatar(message), [message])
  const url = avatarUrlFor(message)

  return (
    <div style={{ position: 'relative', width: size, height: size, flexShrink: 0 }}>
      <div
        style={{
          position: 'absolute',
          top: 0,
          left: 0,
          width: size,
          height: size,
          borderRadius: size / 2,
          backgroundColor: message.author.color ?? '#444444',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
        }}
      >
        <Text
          style={{
            fontSize: size >= 24 ? 11 : 8,
            fontWeight: 700,
            color: 'rgba(255, 255, 255, 0.9)',
          }}
        >
          {message.author.displayName.slice(0, 1).toUpperCase()}
        </Text>
      </div>
      {url ? (
        <RemoteImage
          url={url}
          objectFit="cover"
          style={{
            position: 'absolute',
            top: 0,
            left: 0,
            width: size,
            height: size,
            borderRadius: size / 2,
          }}
        />
      ) : null}
    </div>
  )
}

// ── Badges ──────────────────────────────────────────────────────────────────

function badgeDataUrl(svg: string): string {
  return `data:image/svg+xml;base64,${Buffer.from(svg).toString('base64')}`
}

function Badge({ imageUrl, text, size }: { imageUrl?: string; text: string; size: number }) {
  const resolved = resolveBadgeImage(imageUrl)
  if (resolved?.startsWith('<svg')) {
    // Embedded Kick badge SVG: render full-colour through <img> (the <svg>
    // element is monochrome and would lose the brand colors).
    return (
      <img
        src={badgeDataUrl(resolved)}
        objectFit="contain"
        style={{ width: size, height: size, flexShrink: 0 }}
      />
    )
  }
  if (resolved) {
    return (
      <RemoteImage
        url={resolved}
        objectFit="contain"
        style={{ height: size, width: size * 2, maxWidth: 64, flexShrink: 0 }}
      />
    )
  }
  return (
    <div
      style={{
        minHeight: size,
        paddingLeft: Math.round(size * 0.35),
        paddingRight: Math.round(size * 0.35),
        paddingTop: 1,
        backgroundColor: 'rgba(255, 255, 255, 0.1)',
        borderRadius: 3,
        display: 'flex',
        alignItems: 'center',
      }}
    >
      <Text style={{ fontSize: size - 4, color: '#e2e2e8', lineHeight: size - 2 }}>{text}</Text>
    </div>
  )
}

export function BadgeList({
  badges,
  size,
}: {
  badges: NormalizedChatMessage['author']['badges']
  size: number
}) {
  if (badges.length === 0) return null
  return (
    <div style={{ display: 'flex', flexDirection: 'row', alignItems: 'center', gap: 3 }}>
      {badges.map((badge) => (
        <Badge key={badge.id} imageUrl={badge.imageUrl} text={badge.text} size={size} />
      ))}
    </div>
  )
}

// ── Reply preview ───────────────────────────────────────────────────────────

function ReplyPreview({ message, fontSize }: { message: NormalizedChatMessage; fontSize: number }) {
  const theme = useTheme()
  const reply = message.reply
  if (!reply) return null
  const text =
    reply.parentMessageText.length > 80
      ? `${reply.parentMessageText.slice(0, 80)}…`
      : reply.parentMessageText
  return (
    <div
      style={{
        display: 'flex',
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
        overflow: 'hidden',
      }}
    >
      <Text
        style={{ fontSize: Math.round(fontSize * 0.8 * 1.1), color: theme.text2, opacity: 0.7 }}
      >
        ↩
      </Text>
      <Text
        style={{
          fontSize: Math.round(fontSize * 0.8),
          color: theme.text,
          fontWeight: 600,
          whiteSpace: 'nowrap',
        }}
      >
        {reply.parentAuthor.displayName}
      </Text>
      <Text
        style={{ fontSize: Math.round(fontSize * 0.8), color: theme.text2, whiteSpace: 'nowrap' }}
      >
        :
      </Text>
      <Text
        style={{
          fontSize: Math.round(fontSize * 0.8),
          color: theme.text2,
          whiteSpace: 'nowrap',
          textOverflow: 'ellipsis',
          overflow: 'hidden',
          flexShrink: 1,
          minWidth: 0,
        }}
      >
        {text}
      </Text>
    </div>
  )
}

// ── Hover action buttons ────────────────────────────────────────────────────

function HoverActions({
  onReply,
  onCopy,
  copySuccess,
}: {
  onReply: () => void
  onCopy: () => void
  copySuccess: boolean
}) {
  const theme = useTheme()
  return (
    <div
      style={{
        position: 'absolute',
        right: 8,
        top: 0,
        bottom: 0,
        display: 'flex',
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
        userSelect: 'none',
      }}
    >
      <div
        testId="msg-reply"
        onClick={onReply}
        style={{
          backgroundColor: 'rgba(255, 255, 255, 0.1)',
          borderRadius: 4,
          paddingTop: 4,
          paddingBottom: 4,
          paddingLeft: 6,
          paddingRight: 6,
          cursor: 'pointer',
          display: 'flex',
          hover: { backgroundColor: 'rgba(255, 255, 255, 0.15)' },
        }}
      >
        <Icon name="reply" size={14} color={theme.text2} />
      </div>
      <div
        testId="msg-copy"
        onClick={onCopy}
        style={{
          backgroundColor: copySuccess ? 'rgba(74, 222, 128, 0.2)' : 'rgba(255, 255, 255, 0.1)',
          borderRadius: 4,
          paddingTop: 4,
          paddingBottom: 4,
          paddingLeft: 6,
          paddingRight: 6,
          cursor: 'pointer',
          display: 'flex',
          hover: { backgroundColor: 'rgba(255, 255, 255, 0.15)' },
        }}
      >
        <Icon
          name={copySuccess ? 'check' : 'copy'}
          size={14}
          color={copySuccess ? semantic.successSoft : theme.text2}
        />
      </div>
    </div>
  )
}

// ── Main component ──────────────────────────────────────────────────────────

export interface ChatMessageProps {
  message: NormalizedChatMessage
  channelSlug?: string
  showPlatformColorStripe?: boolean
  showPlatformIcon?: boolean
  showTimestamp?: boolean
  showAvatar?: boolean
  showBadges?: boolean
  fontSize?: number
  chatTheme?: 'modern' | 'compact'
  accounts?: Account[]
  selfPingEnabled?: boolean
  selfPingColor?: string
  alias?: string
  moderationOutcome?: ResolvedModerationOutcome
  /** Moderation drag rail, rendered over the row's left edge. */
  moderationRail?: import('react').ReactNode
  onOpenUserCard?: (target: UserCardTarget) => void
  onReply?: (message: NormalizedChatMessage) => void
}

export const ChatMessage = memo(function ChatMessage(props: ChatMessageProps) {
  const { message } = props
  const theme = useTheme()
  const font = useFont()
  const backend = useBackend()
  const [hovered, setHovered] = useState(false)
  const [copySuccess, setCopySuccess] = useState(false)

  const fontSize = props.fontSize ?? DEFAULT_FONT_SIZE
  const isSystem = message.type === 'system'
  const isAction = message.type === 'action'
  const isTombstone = props.moderationOutcome?.isTombstone === true

  const isSelfPing = (() => {
    if (!props.selfPingEnabled || !props.accounts?.length) return false
    const myAccount = props.accounts.find((a) => a.platform === message.platform)
    if (!myAccount) return false
    const lower = message.text.toLowerCase()
    return (
      lower.includes(`@${myAccount.username.toLowerCase()}`) ||
      lower.includes(`@${myAccount.displayName.toLowerCase()}`)
    )
  })()

  const copyMessage = () => {
    void backend.api
      .copyText({ text: message.text })
      .then(() => {
        setCopySuccess(true)
        setTimeout(() => setCopySuccess(false), 1500)
      })
      .catch(() => undefined)
  }

  const openUserCard = () => {
    props.onOpenUserCard?.({
      platform: message.platform,
      platformUserId: message.author.id,
      messageId: message.id,
      channelId: message.channelId,
      channelSlug: props.channelSlug,
      displayName: message.author.displayName,
      username: message.author.username,
      avatarUrl: avatarUrlFor(message),
      currentAlias: props.alias,
    })
  }

  const authorColor = message.author.color ?? theme.text
  const authorName = props.alias ?? message.author.displayName

  // ── System message ────────────────────────────────────────────────────────
  if (isSystem) {
    const t = message.text
    const action = t.includes(' added ') ? 'added' : t.includes(' removed ') ? 'removed' : 'renamed'
    const palette =
      action === 'added'
        ? {
            border: '#4ade80',
            bg: 'rgba(74, 222, 128, 0.04)',
            iconBg: 'rgba(74, 222, 128, 0.15)',
            iconColor: '#4ade80',
            glyph: '+',
          }
        : action === 'removed'
          ? {
              border: '#ff5050',
              bg: 'rgba(255, 80, 80, 0.05)',
              iconBg: 'rgba(255, 80, 80, 0.18)',
              iconColor: '#ff6060',
              glyph: '−',
            }
          : {
              border: '#818cf8',
              bg: 'rgba(129, 140, 248, 0.06)',
              iconBg: 'rgba(129, 140, 248, 0.18)',
              iconColor: '#818cf8',
              glyph: '~',
            }

    return (
      <div
        style={{
          display: 'flex',
          flexDirection: 'row',
          alignItems: 'center',
          gap: 8,
          paddingTop: 3,
          paddingBottom: 3,
          paddingLeft: 14,
          paddingRight: 14,
          borderLeftWidth: 2,
          borderColor: palette.border,
          backgroundColor: palette.bg,
          position: 'relative',
        }}
      >
        <div
          style={{
            width: 17,
            height: 17,
            borderRadius: 9,
            backgroundColor: palette.iconBg,
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            flexShrink: 0,
            userSelect: 'none',
          }}
        >
          <Text style={{ fontSize: 12, fontWeight: 800, color: palette.iconColor, lineHeight: 12 }}>
            {palette.glyph}
          </Text>
        </div>
        <div style={{ flexGrow: 1, minWidth: 0 }}>
          <MessageText message={message} fontSize={Math.round(fontSize * 0.88)} isSystem />
        </div>
        {props.showTimestamp ? (
          <Text style={{ fontSize: 10, color: theme.text2, opacity: 0.7, flexShrink: 0 }}>
            {formatMessageTime(message.timestamp)}
          </Text>
        ) : null}
      </div>
    )
  }

  // ── Compact (single wrapping line) ────────────────────────────────────────
  if (props.chatTheme === 'compact') {
    return (
      <div
        onMouseEnter={() => setHovered(true)}
        onMouseLeave={() => setHovered(false)}
        style={{
          display: 'flex',
          flexDirection: 'column',
          paddingTop: 2,
          paddingBottom: 2,
          paddingLeft: 14,
          paddingRight: 14,
          position: 'relative',
          gap: 2,
          opacity:
            message.delivery?.state === 'pending' ? 0.52 : props.moderationOutcome ? 0.48 : 1,
          backgroundColor: isSelfPing
            ? (props.selfPingColor ?? 'rgba(167, 139, 250, 0.15)')
            : message.delivery?.state === 'failed'
              ? 'rgba(239, 68, 68, 0.08)'
              : undefined,
          borderLeftWidth: message.delivery?.state === 'failed' ? 2 : 0,
          borderColor: semantic.error,
          hover: { backgroundColor: isSelfPing ? undefined : 'rgba(255, 255, 255, 0.025)' },
        }}
      >
        {props.showPlatformColorStripe !== false ? (
          <div
            style={{
              position: 'absolute',
              left: 0,
              top: 2,
              bottom: 2,
              width: 2,
              borderRadius: 2,
              opacity: 0.7,
              backgroundColor: platformColor(message.platform),
            }}
          />
        ) : null}

        {message.reply && !isTombstone ? (
          <ReplyPreview message={message} fontSize={fontSize} />
        ) : null}

        <div
          style={{
            display: 'flex',
            flexDirection: 'row',
            flexWrap: 'wrap',
            alignItems: 'center',
            columnGap: 4,
            rowGap: 1,
          }}
        >
          {props.showTimestamp ? (
            <Text
              style={{
                fontSize: 10,
                color: theme.text2,
                opacity: 0.8,
                whiteSpace: 'nowrap',
                width: 56,
                flexShrink: 0,
              }}
            >
              {formatMessageTime(message.timestamp)}
            </Text>
          ) : null}
          {props.showAvatar !== false ? <Avatar message={message} size={18} /> : null}
          {props.showPlatformIcon ? (
            <PlatformIcon platform={message.platform} size={platformIconSize(fontSize)} />
          ) : null}
          {props.showBadges !== false ? (
            <BadgeList badges={message.author.badges ?? []} size={badgeSize(fontSize)} />
          ) : null}
          <Text
            onClick={openUserCard}
            style={{
              fontWeight: 700,
              fontSize: Math.round(fontSize * 0.9),
              color: authorColor,
              cursor: 'pointer',
              fontFamily: font,
            }}
          >
            {authorName}
          </Text>
          <Text style={{ color: theme.text2, fontSize, fontFamily: font }}>{': '}</Text>
          <MessageTokens
            message={message}
            fontSize={fontSize}
            deleted={isTombstone}
            isAction={isAction}
          />
          {message.delivery?.state === 'failed' ? (
            <Text style={{ fontSize: Math.round(fontSize * 0.82), color: semantic.errorText }}>
              {`Not sent: ${message.delivery.error ?? ''}`}
            </Text>
          ) : null}
          {props.moderationOutcome ? (
            <Text style={{ fontSize: Math.round(fontSize * 0.82), color: theme.text2 }}>
              {props.moderationOutcome.label}
            </Text>
          ) : null}
        </div>

        {hovered && !isTombstone ? (
          <HoverActions
            onReply={() => props.onReply?.(message)}
            onCopy={copyMessage}
            copySuccess={copySuccess}
          />
        ) : null}

        {/* Paint order = document order: the rail sits last so its fill and
            preview draw above the row content. */}
        {props.moderationRail}
      </div>
    )
  }

  // ── Modern (default) ──────────────────────────────────────────────────────
  return (
    <div
      onMouseEnter={() => setHovered(true)}
      onMouseLeave={() => setHovered(false)}
      style={{
        display: 'flex',
        flexDirection: 'row',
        alignItems: 'flex-start',
        gap: 10,
        paddingTop: 6,
        paddingBottom: 6,
        paddingLeft: 14,
        paddingRight: 14,
        position: 'relative',
        opacity: message.delivery?.state === 'pending' ? 0.52 : props.moderationOutcome ? 0.48 : 1,
        backgroundColor: isSelfPing
          ? (props.selfPingColor ?? 'rgba(167, 139, 250, 0.15)')
          : message.delivery?.state === 'failed'
            ? 'rgba(239, 68, 68, 0.08)'
            : undefined,
        borderLeftWidth: message.delivery?.state === 'failed' ? 2 : 0,
        borderColor: semantic.error,
        hover: { backgroundColor: 'rgba(255, 255, 255, 0.025)' },
      }}
    >
      {props.showPlatformColorStripe !== false ? (
        <div
          style={{
            position: 'absolute',
            left: 0,
            top: 6,
            bottom: 6,
            width: 2,
            borderRadius: 2,
            opacity: 0.7,
            backgroundColor: platformColor(message.platform),
          }}
        />
      ) : null}

      {props.showPlatformIcon ? (
        <div style={{ marginTop: 6, flexShrink: 0, opacity: 0.85, display: 'flex' }}>
          <PlatformIcon platform={message.platform} size={platformIconSize(fontSize)} />
        </div>
      ) : null}

      {props.showAvatar !== false ? (
        <div style={{ marginTop: 1, flexShrink: 0 }}>
          <Avatar message={message} size={28} />
        </div>
      ) : null}

      <div
        style={{
          flexGrow: 1,
          minWidth: 0,
          display: 'flex',
          flexDirection: 'column',
          gap: 2,
        }}
      >
        {message.reply && !isTombstone ? (
          <ReplyPreview message={message} fontSize={fontSize} />
        ) : null}

        <div
          style={{
            display: 'flex',
            flexDirection: 'row',
            alignItems: 'center',
            gap: 5,
            flexWrap: 'wrap',
          }}
        >
          {props.showBadges !== false ? (
            <BadgeList badges={message.author.badges ?? []} size={badgeSize(fontSize)} />
          ) : null}
          <Text
            onClick={openUserCard}
            style={{
              fontWeight: 700,
              fontSize: Math.round(fontSize * 0.9),
              color: authorColor,
              cursor: 'pointer',
              fontFamily: font,
            }}
          >
            {authorName}
          </Text>
          {props.showTimestamp ? (
            <Text style={{ fontSize: 10, color: theme.text2, marginLeft: 2 }}>
              {formatMessageTime(message.timestamp)}
            </Text>
          ) : null}
        </div>

        <MessageText
          message={message}
          fontSize={fontSize}
          deleted={isTombstone}
          isAction={isAction}
        />

        {message.delivery?.state === 'failed' ? (
          <Text
            style={{
              fontSize: Math.round(fontSize * 0.82),
              color: semantic.errorText,
              marginTop: 2,
            }}
          >
            {`Not sent: ${message.delivery.error ?? ''}`}
          </Text>
        ) : null}
        {props.moderationOutcome ? (
          <Text
            style={{ fontSize: Math.round(fontSize * 0.82), color: theme.text2, marginLeft: 4 }}
          >
            {props.moderationOutcome.label}
          </Text>
        ) : null}
      </div>

      {hovered && !isTombstone ? (
        <HoverActions
          onReply={() => props.onReply?.(message)}
          onCopy={copyMessage}
          copySuccess={copySuccess}
        />
      ) : null}

      {/* Paint order = document order: the rail sits last so its fill and
          preview draw above the row content. */}
      {props.moderationRail}
    </div>
  )
})
