// packages/desktop/src/views/main/components/ChattersDialog.vue
<script setup lang="ts">
import { computed, ref } from 'vue'
import { DialogContent, DialogOverlay, DialogPortal, DialogRoot, DialogTitle } from 'reka-ui'

import KickIcon from '../../../assets/icons/platforms/kick.svg'
import TwitchIcon from '../../../assets/icons/platforms/twitch.svg'
import { platformColor } from '../../shared/utils/platform'
import { useChannelChatters } from '../composables/useChannelChatters'
import type { ChannelChatters, ChattersTarget, ChatterUser } from '../services/desktop-api'
import { chatterRoleLabel } from '../utils/chatters'

interface Props {
  targets: ChattersTarget[]
}

const props = defineProps<Props>()
const open = defineModel<boolean>('open', { required: true })

const targets = computed(() => props.targets)
const { chatters, loading, error, query, visibleResults, reload } = useChannelChatters(
  open,
  targets,
)

const hasQuery = computed(() => query.value.trim().length > 0)
const totalChatting = computed(() =>
  (chatters.value?.results ?? []).reduce((sum, channel) => sum + channel.total, 0),
)

const searchInput = ref<HTMLInputElement | null>(null)

function focusSearch(): void {
  searchInput.value?.focus()
}

function platformIcon(platform: ChannelChatters['platform']) {
  return platform === 'kick' ? KickIcon : TwitchIcon
}

function channelKey(channel: ChannelChatters): string {
  return `${channel.platform}:${channel.channelSlug}`
}

function chatterInitial(user: ChatterUser): string {
  const name = user.displayName || user.username
  return name.charAt(0).toUpperCase()
}

function showLogin(user: ChatterUser): boolean {
  return Boolean(user.username) && user.username.toLowerCase() !== user.displayName.toLowerCase()
}
</script>

<template>
  <DialogRoot v-model:open="open">
    <DialogPortal>
      <DialogOverlay class="dialog-overlay" />
      <DialogContent class="dialog-content" @open-auto-focus="focusSearch">
        <div class="chatters-header">
          <div class="chatters-header-main">
            <DialogTitle class="dialog-title">Chatters</DialogTitle>
            <p v-if="chatters" class="chatters-subtitle">
              <span class="chatters-total">{{ totalChatting }} chatting</span>
              across {{ chatters.results.length }}
              {{ chatters.results.length === 1 ? 'channel' : 'channels' }}
            </p>
          </div>
        </div>

        <input
          id="chatters-search-input"
          ref="searchInput"
          v-model="query"
          class="dialog-input chatters-search"
          type="search"
          placeholder="Search chatters…"
          @keydown.escape.prevent="open = false"
        />

        <div class="chatters-body">
          <div v-if="loading" class="chatters-state">Loading chatters…</div>

          <div v-else-if="error" class="chatters-state chatters-state-error">
            <span>{{ error }}</span>
            <button class="chatters-retry-btn" @click="void reload()">Retry</button>
          </div>

          <template v-else-if="chatters">
            <div v-if="visibleResults.length === 0" class="chatters-state">
              No active chatters right now.
            </div>

            <section
              v-for="channel in visibleResults"
              :key="channelKey(channel)"
              class="chatters-channel"
              :style="{ '--platform-color': platformColor(channel.platform) }"
            >
              <header class="chatters-channel-header">
                <component :is="platformIcon(channel.platform)" class="chatters-platform-icon" />
                <span class="chatters-channel-slug">{{ channel.channelSlug }}</span>
                <span class="chatters-channel-total">· {{ channel.total }} chatting</span>
              </header>

              <div v-if="channel.error" class="chatters-state chatters-state-error">
                <span>{{ channel.error }}</span>
                <button class="chatters-retry-btn" @click="void reload()">Retry</button>
              </div>

              <div v-else-if="channel.groups.length === 0" class="chatters-state">
                {{ hasQuery ? 'No chatters match your search.' : 'No active chatters right now.' }}
              </div>

              <div v-else class="chatters-groups">
                <section v-for="group in channel.groups" :key="group.role" class="chatters-group">
                  <h4 class="chatters-group-title">
                    {{ chatterRoleLabel(group.role) }}
                    <span class="chatters-group-count">{{ group.users.length }}</span>
                  </h4>
                  <ul class="chatters-user-list">
                    <li
                      v-for="user in group.users"
                      :key="user.userId ?? user.username"
                      class="chatters-user"
                    >
                      <img
                        v-if="user.avatarUrl"
                        :src="user.avatarUrl"
                        :alt="user.displayName"
                        class="chatters-avatar"
                        referrerpolicy="no-referrer"
                      />
                      <span v-else class="chatters-avatar chatters-avatar-fallback">
                        {{ chatterInitial(user) }}
                      </span>
                      <span class="chatters-user-name">{{ user.displayName }}</span>
                      <span v-if="showLogin(user)" class="chatters-user-login">
                        @{{ user.username }}
                      </span>
                    </li>
                  </ul>
                </section>
              </div>
            </section>
          </template>
        </div>
      </DialogContent>
    </DialogPortal>
  </DialogRoot>
</template>

<style scoped>
.dialog-overlay {
  background: rgba(0, 0, 0, 0.6);
  position: fixed;
  inset: 0;
  z-index: 2000;
}

.dialog-content {
  background: var(--c-bg-2, #2a2a35);
  border: 1px solid var(--c-border, #3a3a45);
  border-radius: 8px;
  box-shadow: 0 8px 24px rgba(0, 0, 0, 0.5);
  position: fixed;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  width: 90vw;
  max-width: 480px;
  padding: 20px;
  z-index: 2001;
  max-height: min(85vh, 720px);
  display: flex;
  flex-direction: column;
}

.dialog-title {
  margin: 0;
  font-size: 1.35em;
  color: var(--c-text, #e2e2e8);
}

.chatters-header {
  display: flex;
  align-items: center;
  gap: 12px;
  margin: -20px -20px 16px;
  padding: 16px 20px;
  background: linear-gradient(135deg, #23232e 0%, #1a1a22 100%);
  border-bottom: 1px solid rgba(255, 255, 255, 0.08);
}

.chatters-header-main {
  min-width: 0;
  display: flex;
  flex-direction: column;
  gap: 2px;
}

.chatters-subtitle {
  margin: 0;
  font-size: 0.9em;
  color: rgba(255, 255, 255, 0.75);
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.chatters-total {
  font-weight: 600;
}

.dialog-input {
  width: 100%;
  box-sizing: border-box;
  padding: 8px 12px;
  background: var(--c-bg, #1e1e24);
  border: 1px solid var(--c-border, #3a3a45);
  color: var(--c-text, #e2e2e8);
  border-radius: 4px;
  font-size: 0.95em;
}

.dialog-input:focus {
  outline: none;
  border-color: var(--c-accent, #9147ff);
}

.chatters-search {
  flex-shrink: 0;
  margin-bottom: 12px;
}

.chatters-body {
  flex: 1;
  min-height: 160px;
  overflow-y: auto;
  display: flex;
  flex-direction: column;
  gap: 16px;
}

.chatters-state {
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 10px;
  min-height: 160px;
  padding: 16px;
  text-align: center;
  font-size: 13px;
  color: var(--c-text-2, #8b8b99);
  border: 1px solid rgba(255, 255, 255, 0.06);
  border-radius: 10px;
  background: rgba(0, 0, 0, 0.16);
}

.chatters-channel .chatters-state {
  min-height: 56px;
}

.chatters-state-error {
  color: #fca5a5;
  flex-direction: column;
}

.chatters-retry-btn {
  border: none;
  border-radius: 6px;
  background: rgba(255, 255, 255, 0.08);
  color: var(--c-text, #e2e2e8);
  cursor: pointer;
  font: inherit;
  padding: 6px 10px;
  font-size: 12px;
}

.chatters-retry-btn:hover {
  background: rgba(255, 255, 255, 0.14);
}

.chatters-channel {
  display: flex;
  flex-direction: column;
}

.chatters-channel-header {
  display: flex;
  align-items: center;
  gap: 8px;
  margin-bottom: 8px;
  padding-bottom: 6px;
  border-bottom: 1px solid rgba(255, 255, 255, 0.08);
}

.chatters-platform-icon {
  width: 16px;
  height: 16px;
  color: var(--platform-color, #9146ff);
  flex-shrink: 0;
}

.chatters-channel-slug {
  font-size: 13px;
  font-weight: 600;
  color: var(--c-text, #e2e2e8);
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.chatters-channel-total {
  font-size: 12px;
  font-weight: 600;
  color: var(--c-text-2, #8b8b99);
  font-variant-numeric: tabular-nums;
  flex-shrink: 0;
}

.chatters-groups {
  display: flex;
  flex-direction: column;
  gap: 14px;
}

.chatters-group-title {
  margin: 0 0 6px;
  display: flex;
  align-items: center;
  gap: 8px;
  font-size: 11px;
  font-weight: 700;
  color: var(--c-text-2, #8b8b99);
  text-transform: uppercase;
  letter-spacing: 0.04em;
}

.chatters-group-count {
  font-variant-numeric: tabular-nums;
  background: rgba(255, 255, 255, 0.07);
  border-radius: 999px;
  padding: 1px 8px;
}

.chatters-user-list {
  list-style: none;
  margin: 0;
  padding: 0;
  display: flex;
  flex-direction: column;
  gap: 2px;
}

.chatters-user {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 4px 6px;
  border-radius: 6px;
}

.chatters-user:hover {
  background: rgba(255, 255, 255, 0.05);
}

.chatters-avatar {
  width: 24px;
  height: 24px;
  border-radius: 50%;
  object-fit: cover;
  background: rgba(255, 255, 255, 0.08);
  flex-shrink: 0;
}

.chatters-avatar-fallback {
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 11px;
  font-weight: 700;
  color: #fff;
  background: var(--platform-color, #9146ff);
}

.chatters-user-name {
  font-size: 13px;
  color: var(--c-text, #e2e2e8);
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.chatters-user-login {
  font-size: 11px;
  color: var(--c-text-2, #8b8b99);
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
</style>

// packages/desktop/src/gpuix/components/ChattersDialog.tsx
/**
 * Chatters dialog — port of ChattersDialog.vue onto GPUIX.
 *
 * Loads the active chatters for the given twitch/kick targets, groups them
 * per channel and role, with a client-side search filter.
 *
 * GPUIX deviations:
 * - Dialog width is a fixed 480px (Vue used 90vw capped at 480px).
 * - Esc closes via a focusable wrapper + the search input's key handler;
 *   reka-ui's global dialog Escape handling does not exist here.
 */

import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import type { ChannelChatters, ChattersTarget, ChatterUser } from '../backend/api'
import { chatterRoleLabel, filterChatterGroups } from '../../views/main/utils/chatters'
import { platformColor } from '../theme'
import { useTheme } from '../theme-context'
import { useBackend } from '../backend/context'
import { Text } from './ui/Text'
import { RemoteImage } from './ui/RemoteImage'
import { Modal } from './ui/Modal'
import { PlatformIcon } from './ui/Icon'

interface ChattersResponse {
  results: ChannelChatters[]
}

function serializeTargets(targets: readonly ChattersTarget[]): string {
  return targets.map((target) => `${target.platform}:${target.channelSlug.toLowerCase()}`).join('|')
}

function channelKey(channel: ChannelChatters): string {
  return `${channel.platform}:${channel.channelSlug}`
}

function chatterInitial(user: ChatterUser): string {
  const name = user.displayName || user.username
  return name.charAt(0).toUpperCase()
}

function showLogin(user: ChatterUser): boolean {
  return Boolean(user.username) && user.username.toLowerCase() !== user.displayName.toLowerCase()
}

export function ChattersDialog({
  targets,
  onClose,
}: {
  targets: ChattersTarget[]
  onClose: () => void
}) {
  const theme = useTheme()
  const backend = useBackend()

  const [chatters, setChatters] = useState<ChattersResponse | null>(null)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [query, setQuery] = useState('')
  const generationRef = useRef(0)

  const targetsKey = serializeTargets(targets)

  const reload = useCallback(async (): Promise<void> => {
    if (targets.length === 0) return

    const generation = generationRef.current + 1
    generationRef.current = generation
    setLoading(true)
    setError(null)

    try {
      const response = await backend.api.getChatters({ targets })
      if (generation !== generationRef.current) return
      setChatters(response)
    } catch (loadError) {
      if (generation !== generationRef.current) return
      setChatters(null)
      setError(loadError instanceof Error ? loadError.message : String(loadError))
    } finally {
      if (generation === generationRef.current) {
        setLoading(false)
      }
    }
  }, [backend, targets])

  // Reset + load on mount / when the target set changes (port of
  // useChannelChatters; the dialog only exists while open).
  useEffect(() => {
    generationRef.current += 1
    setChatters(null)
    setError(null)
    setLoading(false)
    setQuery('')
    if (targetsKey.length > 0) void reload()
  }, [reload, targetsKey])

  const visibleResults = useMemo(
    () =>
      (chatters?.results ?? []).map((channel) => ({
        platform: channel.platform,
        channelSlug: channel.channelSlug,
        total: channel.total,
        groups: filterChatterGroups(channel.groups, query),
        error: channel.error,
      })),
    [chatters, query],
  )

  const hasQuery = query.trim().length > 0
  const totalChatting = (chatters?.results ?? []).reduce((sum, channel) => sum + channel.total, 0)

  return (
    <Modal width={480} onClose={onClose}>
      <div
        tabIndex={-1}
        onKeyDown={(event) => {
          if (event.key === 'escape') onClose()
        }}
        style={{
          display: 'flex',
          flexDirection: 'column',
          flexGrow: 1,
          minHeight: 0,
        }}
      >
        {/* Header (full-bleed: the Vue version used negative margins) */}
        <div
          style={{
            display: 'flex',
            flexDirection: 'row',
            alignItems: 'center',
            gap: 12,
            paddingTop: 16,
            paddingBottom: 16,
            paddingLeft: 20,
            paddingRight: 20,
            marginBottom: 16,
            background: {
              type: 'linear-gradient',
              angle: 135,
              stops: [
                { color: '#23232e', position: 0 },
                { color: '#1a1a22', position: 1 },
              ],
            },
            borderBottomWidth: 1,
            borderColor: 'rgba(255, 255, 255, 0.08)',
          }}
        >
          <div style={{ minWidth: 0, display: 'flex', flexDirection: 'column', gap: 2 }}>
            <Text style={{ fontSize: 18, fontWeight: 700, color: theme.text }}>Chatters</Text>
            {chatters ? (
              <div style={{ display: 'flex', flexDirection: 'row', gap: 4 }}>
                <Text
                  style={{
                    fontSize: 13,
                    fontWeight: 600,
                    color: 'rgba(255, 255, 255, 0.75)',
                  }}
                >
                  {`${totalChatting} chatting`}
                </Text>
                <Text style={{ fontSize: 13, color: 'rgba(255, 255, 255, 0.75)' }}>
                  {`across ${chatters.results.length} ${
                    chatters.results.length === 1 ? 'channel' : 'channels'
                  }`}
                </Text>
              </div>
            ) : null}
          </div>
        </div>

        <div
          style={{
            display: 'flex',
            flexDirection: 'column',
            flexGrow: 1,
            minHeight: 0,
            paddingLeft: 20,
            paddingRight: 20,
            paddingBottom: 20,
          }}
        >
          <input
            autoFocus
            value={query}
            placeholder="Search chatters…"
            onChange={(event) => setQuery(event.value ?? '')}
            onKeyDown={(event) => {
              if (event.key === 'escape') onClose()
            }}
            theme={{ caret: '#a78bfa' }}
            style={{
              flexShrink: 0,
              marginBottom: 12,
              paddingTop: 8,
              paddingBottom: 8,
              paddingLeft: 12,
              paddingRight: 12,
              backgroundColor: '#1e1e24',
              borderWidth: 1,
              borderColor: '#3a3a45',
              borderRadius: 4,
              fontSize: 13,
              color: theme.text,
            }}
          />

          <div
            style={{
              flexGrow: 1,
              minHeight: 160,
              overflowY: 'scroll',
              display: 'flex',
              flexDirection: 'column',
              gap: 16,
            }}
          >
            {loading ? (
              <ChattersState>
                <Text style={{ fontSize: 13, color: theme.text2 }}>Loading chatters…</Text>
              </ChattersState>
            ) : error ? (
              <ChattersState error>
                <Text style={{ fontSize: 13, color: '#fca5a5' }}>{error}</Text>
                <RetryButton onClick={() => void reload()} />
              </ChattersState>
            ) : chatters ? (
              visibleResults.length === 0 ? (
                <ChattersState>
                  <Text style={{ fontSize: 13, color: theme.text2 }}>
                    No active chatters right now.
                  </Text>
                </ChattersState>
              ) : (
                visibleResults.map((channel) => (
                  <div
                    key={channelKey(channel)}
                    style={{ display: 'flex', flexDirection: 'column' }}
                  >
                    <div
                      style={{
                        display: 'flex',
                        flexDirection: 'row',
                        alignItems: 'center',
                        gap: 8,
                        marginBottom: 8,
                        paddingBottom: 6,
                        borderBottomWidth: 1,
                        borderColor: 'rgba(255, 255, 255, 0.08)',
                      }}
                    >
                      <PlatformIcon platform={channel.platform} size={16} />
                      <Text
                        style={{
                          fontSize: 13,
                          fontWeight: 600,
                          color: theme.text,
                          whiteSpace: 'nowrap',
                          textOverflow: 'ellipsis',
                          overflow: 'hidden',
                        }}
                      >
                        {channel.channelSlug}
                      </Text>
                      <Text
                        style={{
                          fontSize: 12,
                          fontWeight: 600,
                          color: theme.text2,
                          flexShrink: 0,
                        }}
                      >
                        {`· ${channel.total} chatting`}
                      </Text>
                    </div>

                    {channel.error ? (
                      <ChattersState small error>
                        <Text style={{ fontSize: 13, color: '#fca5a5' }}>{channel.error}</Text>
                        <RetryButton onClick={() => void reload()} />
                      </ChattersState>
                    ) : channel.groups.length === 0 ? (
                      <ChattersState small>
                        <Text style={{ fontSize: 13, color: theme.text2 }}>
                          {hasQuery
                            ? 'No chatters match your search.'
                            : 'No active chatters right now.'}
                        </Text>
                      </ChattersState>
                    ) : (
                      <div style={{ display: 'flex', flexDirection: 'column', gap: 14 }}>
                        {channel.groups.map((group) => (
                          <div
                            key={group.role}
                            style={{ display: 'flex', flexDirection: 'column' }}
                          >
                            <div
                              style={{
                                display: 'flex',
                                flexDirection: 'row',
                                alignItems: 'center',
                                gap: 8,
                                marginBottom: 6,
                              }}
                            >
                              <Text
                                style={{
                                  fontSize: 11,
                                  fontWeight: 700,
                                  color: theme.text2,
                                }}
                              >
                                {chatterRoleLabel(group.role).toUpperCase()}
                              </Text>
                              <div
                                style={{
                                  backgroundColor: 'rgba(255, 255, 255, 0.07)',
                                  borderRadius: 999,
                                  paddingTop: 1,
                                  paddingBottom: 1,
                                  paddingLeft: 8,
                                  paddingRight: 8,
                                }}
                              >
                                <Text style={{ fontSize: 11, color: theme.text2 }}>
                                  {`${group.users.length}`}
                                </Text>
                              </div>
                            </div>

                            <div style={{ display: 'flex', flexDirection: 'column', gap: 2 }}>
                              {group.users.map((user) => (
                                <div
                                  key={user.userId ?? user.username}
                                  style={{
                                    display: 'flex',
                                    flexDirection: 'row',
                                    alignItems: 'center',
                                    gap: 8,
                                    paddingTop: 4,
                                    paddingBottom: 4,
                                    paddingLeft: 6,
                                    paddingRight: 6,
                                    borderRadius: 6,
                                    hover: { backgroundColor: 'rgba(255, 255, 255, 0.05)' },
                                  }}
                                >
                                  {user.avatarUrl ? (
                                    <RemoteImage
                                      url={user.avatarUrl}
                                      objectFit="cover"
                                      style={{
                                        width: 24,
                                        height: 24,
                                        borderRadius: 12,
                                        backgroundColor: 'rgba(255, 255, 255, 0.08)',
                                        flexShrink: 0,
                                      }}
                                    />
                                  ) : (
                                    <div
                                      style={{
                                        width: 24,
                                        height: 24,
                                        borderRadius: 12,
                                        backgroundColor: platformColor(channel.platform),
                                        flexShrink: 0,
                                        display: 'flex',
                                        alignItems: 'center',
                                        justifyContent: 'center',
                                      }}
                                    >
                                      <Text
                                        style={{
                                          fontSize: 11,
                                          fontWeight: 700,
                                          color: '#ffffff',
                                        }}
                                      >
                                        {chatterInitial(user)}
                                      </Text>
                                    </div>
                                  )}
                                  <Text
                                    style={{
                                      fontSize: 13,
                                      color: theme.text,
                                      whiteSpace: 'nowrap',
                                      textOverflow: 'ellipsis',
                                      overflow: 'hidden',
                                    }}
                                  >
                                    {user.displayName}
                                  </Text>
                                  {showLogin(user) ? (
                                    <Text
                                      style={{
                                        fontSize: 11,
                                        color: theme.text2,
                                        whiteSpace: 'nowrap',
                                        textOverflow: 'ellipsis',
                                        overflow: 'hidden',
                                      }}
                                    >
                                      {`@${user.username}`}
                                    </Text>
                                  ) : null}
                                </div>
                              ))}
                            </div>
                          </div>
                        ))}
                      </div>
                    )}
                  </div>
                ))
              )
            ) : null}
          </div>
        </div>
      </div>
    </Modal>
  )
}

// ── Local styled bits ───────────────────────────────────────────────────────

function ChattersState({
  small,
  error,
  children,
}: {
  small?: boolean
  error?: boolean
  children: React.ReactNode
}) {
  return (
    <div
      style={{
        display: 'flex',
        flexDirection: error ? 'column' : 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 10,
        minHeight: small ? 56 : 160,
        padding: 16,
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.06)',
        borderRadius: 10,
        backgroundColor: 'rgba(0, 0, 0, 0.16)',
      }}
    >
      {children}
    </div>
  )
}

function RetryButton({ onClick }: { onClick: () => void }) {
  const theme = useTheme()
  return (
    <div
      onClick={onClick}
      style={{
        borderRadius: 6,
        backgroundColor: 'rgba(255, 255, 255, 0.08)',
        paddingTop: 6,
        paddingBottom: 6,
        paddingLeft: 10,
        paddingRight: 10,
        cursor: 'pointer',
        hover: { backgroundColor: 'rgba(255, 255, 255, 0.14)' },
      }}
    >
      <Text style={{ fontSize: 12, color: theme.text }}>Retry</Text>
    </div>
  )
}
