// packages/desktop/src/views/main/components/EventsFeed.vue
<script setup lang="ts">
import type { NormalizedEvent } from '@twirchat/shared/types'
import { platformColor } from '../../shared/utils/platform'

const props = defineProps<{
  events: NormalizedEvent[]
}>()

function eventIcon(type: NormalizedEvent['type']): string {
  switch (type) {
    case 'follow': {
      return 'follow'
    }
    case 'sub': {
      return 'sub'
    }
    case 'resub': {
      return 'sub'
    }
    case 'gift_sub': {
      return 'gift'
    }
    case 'raid': {
      return 'raid'
    }
    case 'host': {
      return 'host'
    }
    case 'bits': {
      return 'bits'
    }
    case 'superchat': {
      return 'superchat'
    }
    case 'membership': {
      return 'sub'
    }
    default: {
      return 'bell'
    }
  }
}

function eventLabel(type: NormalizedEvent['type']): string {
  switch (type) {
    case 'follow': {
      return 'Follow'
    }
    case 'sub': {
      return 'Subscription'
    }
    case 'resub': {
      return 'Re-subscription'
    }
    case 'gift_sub': {
      return 'Gift sub'
    }
    case 'raid': {
      return 'Raid'
    }
    case 'host': {
      return 'Host'
    }
    case 'bits': {
      return 'Bits'
    }
    case 'superchat': {
      return 'Super Chat'
    }
    case 'membership': {
      return 'Membership'
    }
    default: {
      return type
    }
  }
}

function eventColor(type: NormalizedEvent['type']): string {
  switch (type) {
    case 'follow': {
      return '#22c55e'
    }
    case 'sub': {
      return '#a78bfa'
    }
    case 'resub': {
      return '#a78bfa'
    }
    case 'gift_sub': {
      return '#f59e0b'
    }
    case 'raid': {
      return '#3b82f6'
    }
    case 'host': {
      return '#06b6d4'
    }
    case 'bits': {
      return '#f59e0b'
    }
    case 'superchat': {
      return '#ef4444'
    }
    case 'membership': {
      return '#a78bfa'
    }
    default: {
      return '#8b8b99'
    }
  }
}

function formatTime(ts: Date): string {
  const d = new Date(ts)
  return d.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
}

function eventDetail(ev: NormalizedEvent): string {
  const d = ev.data as Record<string, unknown>
  switch (ev.type) {
    case 'resub': {
      return d.months ? `${d.months} months` : ''
    }
    case 'raid': {
      return d.viewers ? `${d.viewers} viewers` : ''
    }
    case 'bits': {
      return d.amount ? `${d.amount} bits` : ''
    }
    case 'gift_sub': {
      return d.count ? `×${d.count}` : ''
    }
    case 'superchat': {
      return d.amount ? String(d.amount) : ''
    }
    default: {
      return ''
    }
  }
}
</script>

<template>
  <div class="events-panel">
    <div class="panel-header">
      <h2 class="panel-title">Events</h2>
      <span class="event-count" v-if="events.length > 0">{{ events.length }}</span>
    </div>

    <div class="events-list">
      <div v-if="events.length === 0" class="empty-state">
        <div class="empty-icon">
          <svg
            width="48"
            height="48"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="1.2"
            stroke-linecap="round"
            stroke-linejoin="round"
            opacity=".35"
          >
            <path d="M18 8A6 6 0 0 0 6 8c0 7-3 9-3 9h18s-3-2-3-9" />
            <path d="M13.73 21a2 2 0 0 1-3.46 0" />
          </svg>
        </div>
        <p class="empty-title">No events yet</p>
        <p class="empty-hint">Follows, subs, raids and bits will appear here.</p>
      </div>

      <div v-for="ev in events" :key="ev.id" class="event-card">
        <!-- Event type icon -->
        <div
          class="event-type-icon"
          :style="{
            background: eventColor(ev.type) + '22',
            color: eventColor(ev.type),
          }"
        >
          <!-- Follow -->
          <svg
            v-if="eventIcon(ev.type) === 'follow'"
            width="16"
            height="16"
            viewBox="0 0 24 24"
            fill="currentColor"
          >
            <path
              d="M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 0 0 0-7.78z"
              fill="none"
              stroke="currentColor"
              stroke-width="2"
              stroke-linecap="round"
              stroke-linejoin="round"
            />
          </svg>
          <!-- Sub / Membership -->
          <svg
            v-else-if="eventIcon(ev.type) === 'sub'"
            width="16"
            height="16"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
            stroke-linecap="round"
            stroke-linejoin="round"
          >
            <polygon
              points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2"
            />
          </svg>
          <!-- Gift -->
          <svg
            v-else-if="eventIcon(ev.type) === 'gift'"
            width="16"
            height="16"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
            stroke-linecap="round"
            stroke-linejoin="round"
          >
            <polyline points="20 12 20 22 4 22 4 12" />
            <rect x="2" y="7" width="20" height="5" />
            <line x1="12" y1="22" x2="12" y2="7" />
            <path d="M12 7H7.5a2.5 2.5 0 0 1 0-5C11 2 12 7 12 7z" />
            <path d="M12 7h4.5a2.5 2.5 0 0 0 0-5C13 2 12 7 12 7z" />
          </svg>
          <!-- Raid -->
          <svg
            v-else-if="eventIcon(ev.type) === 'raid'"
            width="16"
            height="16"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
            stroke-linecap="round"
            stroke-linejoin="round"
          >
            <polygon points="13 2 3 14 12 14 11 22 21 10 12 10 13 2" />
          </svg>
          <!-- Host -->
          <svg
            v-else-if="eventIcon(ev.type) === 'host'"
            width="16"
            height="16"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
            stroke-linecap="round"
            stroke-linejoin="round"
          >
            <circle cx="12" cy="12" r="10" />
            <polygon points="10 8 16 12 10 16 10 8" />
          </svg>
          <!-- Bits / Superchat -->
          <svg
            v-else-if="eventIcon(ev.type) === 'bits' || eventIcon(ev.type) === 'superchat'"
            width="16"
            height="16"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
            stroke-linecap="round"
            stroke-linejoin="round"
          >
            <line x1="12" y1="1" x2="12" y2="23" />
            <path d="M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6" />
          </svg>
          <!-- Fallback bell -->
          <svg
            v-else
            width="16"
            height="16"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
            stroke-linecap="round"
            stroke-linejoin="round"
          >
            <path d="M18 8A6 6 0 0 0 6 8c0 7-3 9-3 9h18s-3-2-3-9" />
            <path d="M13.73 21a2 2 0 0 1-3.46 0" />
          </svg>
        </div>

        <!-- Event info -->
        <div class="event-info">
          <div class="event-top">
            <span class="event-user">{{ ev.user.displayName }}</span>
            <span class="event-type-label" :style="{ color: eventColor(ev.type) }">{{
              eventLabel(ev.type)
            }}</span>
            <span v-if="eventDetail(ev)" class="event-detail">{{ eventDetail(ev) }}</span>
          </div>
          <div class="event-bottom">
            <span
              class="platform-chip"
              :style="{
                color: platformColor(ev.platform),
                borderColor: platformColor(ev.platform) + '44',
                background: platformColor(ev.platform) + '18',
              }"
              >{{ ev.platform }}</span
            >
            <span class="event-time">{{ formatTime(ev.timestamp) }}</span>
          </div>
        </div>

        <!-- Avatar -->
        <img
          v-if="ev.user.avatarUrl"
          class="event-avatar"
          :src="ev.user.avatarUrl"
          :alt="ev.user.displayName"
        />
        <div v-else class="event-avatar event-avatar-fallback">
          {{ ev.user.displayName[0] }}
        </div>
      </div>
    </div>
  </div>
</template>

<style scoped>
.events-panel {
  flex: 1;
  display: flex;
  flex-direction: column;
  overflow: hidden;
}

.panel-header {
  display: flex;
  align-items: center;
  gap: 10px;
  padding: 12px 20px;
  border-bottom: 1px solid var(--c-border, #2a2a33);
  flex-shrink: 0;
}

.panel-title {
  font-size: 13px;
  font-weight: 700;
  color: var(--c-text-2, #8b8b99);
  text-transform: uppercase;
  letter-spacing: 0.06em;
}

.event-count {
  font-size: 11px;
  background: rgba(167, 139, 250, 0.15);
  color: #a78bfa;
  border-radius: 10px;
  padding: 1px 7px;
  font-weight: 700;
}

.events-list {
  flex: 1;
  overflow-y: auto;
  padding: 8px 12px;
  display: flex;
  flex-direction: column;
  gap: 6px;
}

/* Empty */
.empty-state {
  flex: 1;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  gap: 10px;
  padding: 60px 32px;
  text-align: center;
}

.empty-icon {
  color: var(--c-text-2, #8b8b99);
  margin-bottom: 4px;
}
.empty-title {
  font-size: 15px;
  font-weight: 600;
  color: var(--c-text, #e2e2e8);
}
.empty-hint {
  font-size: 13px;
  color: var(--c-text-2, #8b8b99);
  max-width: 280px;
  line-height: 1.5;
}

/* Event card */
.event-card {
  display: flex;
  align-items: center;
  gap: 12px;
  background: var(--c-surface, #18181b);
  border: 1px solid var(--c-border, #2a2a33);
  border-radius: 10px;
  padding: 10px 14px;
  transition: background 0.1s;
}

.event-card:hover {
  background: var(--c-surface-2, #1f1f24);
}

.event-type-icon {
  width: 36px;
  height: 36px;
  border-radius: 8px;
  display: flex;
  align-items: center;
  justify-content: center;
  flex-shrink: 0;
}

.event-info {
  flex: 1;
  min-width: 0;
  display: flex;
  flex-direction: column;
  gap: 4px;
}

.event-top {
  display: flex;
  align-items: center;
  gap: 7px;
  flex-wrap: wrap;
}

.event-user {
  font-size: 14px;
  font-weight: 700;
  color: var(--c-text, #e2e2e8);
}

.event-type-label {
  font-size: 12px;
  font-weight: 600;
}

.event-detail {
  font-size: 12px;
  color: var(--c-text-2, #8b8b99);
}

.event-bottom {
  display: flex;
  align-items: center;
  gap: 8px;
}

.platform-chip {
  font-size: 10px;
  font-weight: 600;
  text-transform: capitalize;
  border: 1px solid;
  border-radius: 4px;
  padding: 1px 5px;
}

.event-time {
  font-size: 11px;
  color: var(--c-text-2, #8b8b99);
}

.event-avatar {
  width: 36px;
  height: 36px;
  border-radius: 50%;
  object-fit: cover;
  flex-shrink: 0;
}

.event-avatar-fallback {
  background: #2a2a33;
  color: var(--c-text-2, #8b8b99);
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 14px;
  font-weight: 700;
}
</style>

// packages/desktop/src/gpuix/components/EventsFeed.tsx
/**
 * Events feed — port of EventsFeed.vue: header with a count pill plus a
 * scrollable list of event cards (type icon, user, label, platform chip,
 * time, avatar). Events come from the shared eventsStore (newest last,
 * capped at 200) instead of a prop.
 */

import type { NormalizedEvent } from '@twirchat/shared/types'

import { useStore } from '../state/create-store'
import { eventsStore } from '../state/app'
import { accent, eventColors, platformColor, withAlpha } from '../theme'
import { useTheme } from '../theme-context'
import { Icon, type IconName } from './ui/Icon'
import { Text } from './ui/Text'
import { RemoteImage } from './ui/RemoteImage'

function eventIconName(type: NormalizedEvent['type']): IconName {
  switch (type) {
    case 'follow':
      return 'heart'
    case 'sub':
    case 'resub':
    case 'membership':
      return 'star'
    case 'gift_sub':
      return 'gift'
    case 'raid':
      return 'zap'
    case 'host':
      return 'playCircle'
    case 'bits':
    case 'superchat':
      return 'dollar'
    default:
      return 'bell'
  }
}

function eventLabel(type: NormalizedEvent['type']): string {
  switch (type) {
    case 'follow':
      return 'Follow'
    case 'sub':
      return 'Subscription'
    case 'resub':
      return 'Re-subscription'
    case 'gift_sub':
      return 'Gift sub'
    case 'raid':
      return 'Raid'
    case 'host':
      return 'Host'
    case 'bits':
      return 'Bits'
    case 'superchat':
      return 'Super Chat'
    case 'membership':
      return 'Membership'
    default:
      return type
  }
}

function eventColor(type: NormalizedEvent['type']): string {
  return eventColors[type] ?? '#8b8b99'
}

function formatTime(ts: Date): string {
  const d = new Date(ts)
  return d.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
}

function eventDetail(ev: NormalizedEvent): string {
  const d = ev.data as Record<string, unknown>
  switch (ev.type) {
    case 'resub':
      return d.months ? `${d.months} months` : ''
    case 'raid':
      return d.viewers ? `${d.viewers} viewers` : ''
    case 'bits':
      return d.amount ? `${d.amount} bits` : ''
    case 'gift_sub':
      return d.count ? `×${d.count}` : ''
    case 'superchat':
      return d.amount ? String(d.amount) : ''
    default:
      return ''
  }
}

function EventCard({ event: ev }: { event: NormalizedEvent }) {
  const theme = useTheme()
  const color = eventColor(ev.type)
  const pColor = platformColor(ev.platform)
  const detail = eventDetail(ev)

  return (
    <div
      style={{
        display: 'flex',
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
        backgroundColor: theme.surface,
        borderWidth: 1,
        borderColor: theme.border,
        borderRadius: 10,
        paddingTop: 10,
        paddingBottom: 10,
        paddingLeft: 14,
        paddingRight: 14,
        hover: { backgroundColor: theme.surface2 },
      }}
    >
      {/* Event type icon */}
      <div
        style={{
          width: 36,
          height: 36,
          borderRadius: 8,
          backgroundColor: withAlpha(color, 0.13),
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          flexShrink: 0,
        }}
      >
        <Icon name={eventIconName(ev.type)} size={16} color={color} />
      </div>

      {/* Event info */}
      <div style={{ flexGrow: 1, minWidth: 0, display: 'flex', flexDirection: 'column', gap: 4 }}>
        <div
          style={{
            display: 'flex',
            flexDirection: 'row',
            alignItems: 'center',
            gap: 7,
            flexWrap: 'wrap',
          }}
        >
          <Text style={{ fontSize: 14, fontWeight: 700, color: theme.text }}>
            {ev.user.displayName}
          </Text>
          <Text style={{ fontSize: 12, fontWeight: 600, color }}>{eventLabel(ev.type)}</Text>
          {detail ? <Text style={{ fontSize: 12, color: theme.text2 }}>{detail}</Text> : null}
        </div>
        <div style={{ display: 'flex', flexDirection: 'row', alignItems: 'center', gap: 8 }}>
          <div
            style={{
              borderWidth: 1,
              borderColor: withAlpha(pColor, 0.27),
              backgroundColor: withAlpha(pColor, 0.09),
              borderRadius: 4,
              paddingTop: 1,
              paddingBottom: 1,
              paddingLeft: 5,
              paddingRight: 5,
            }}
          >
            <Text style={{ fontSize: 10, fontWeight: 600, color: pColor }}>
              {ev.platform.toUpperCase()}
            </Text>
          </div>
          <Text style={{ fontSize: 11, color: theme.text2 }}>{formatTime(ev.timestamp)}</Text>
        </div>
      </div>

      {/* Avatar */}
      {ev.user.avatarUrl ? (
        <RemoteImage
          url={ev.user.avatarUrl}
          objectFit="cover"
          style={{ width: 36, height: 36, borderRadius: 18, flexShrink: 0 }}
        />
      ) : (
        <div
          style={{
            width: 36,
            height: 36,
            borderRadius: 18,
            backgroundColor: '#2a2a33',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            flexShrink: 0,
          }}
        >
          <Text style={{ fontSize: 14, fontWeight: 700, color: theme.text2 }}>
            {ev.user.displayName[0]}
          </Text>
        </div>
      )}
    </div>
  )
}

export function EventsFeed() {
  const theme = useTheme()
  const events = useStore(eventsStore)

  return (
    <div
      style={{
        flexGrow: 1,
        minHeight: 0,
        display: 'flex',
        flexDirection: 'column',
        overflow: 'hidden',
      }}
    >
      {/* Header */}
      <div
        style={{
          display: 'flex',
          flexDirection: 'row',
          alignItems: 'center',
          gap: 10,
          paddingTop: 12,
          paddingBottom: 12,
          paddingLeft: 20,
          paddingRight: 20,
          borderBottomWidth: 1,
          borderColor: theme.border,
          flexShrink: 0,
        }}
      >
        <Text style={{ fontSize: 13, fontWeight: 700, color: theme.text2 }}>
          {'Events'.toUpperCase()}
        </Text>
        {events.length > 0 ? (
          <div
            style={{
              backgroundColor: accent.tint15,
              borderRadius: 10,
              paddingTop: 1,
              paddingBottom: 1,
              paddingLeft: 7,
              paddingRight: 7,
            }}
          >
            <Text style={{ fontSize: 11, fontWeight: 700, color: accent.primary }}>
              {String(events.length)}
            </Text>
          </div>
        ) : null}
      </div>

      {/* List */}
      <div
        style={{
          flexGrow: 1,
          minHeight: 0,
          overflowY: 'scroll',
          paddingTop: 8,
          paddingBottom: 8,
          paddingLeft: 12,
          paddingRight: 12,
          display: 'flex',
          flexDirection: 'column',
          gap: 6,
        }}
      >
        {events.length === 0 ? (
          <div
            style={{
              flexGrow: 1,
              display: 'flex',
              flexDirection: 'column',
              alignItems: 'center',
              justifyContent: 'center',
              gap: 10,
              paddingTop: 60,
              paddingBottom: 60,
              paddingLeft: 32,
              paddingRight: 32,
            }}
          >
            <div style={{ opacity: 0.35, marginBottom: 4, display: 'flex' }}>
              <Icon name="bell" size={48} color={theme.text2} />
            </div>
            <Text style={{ fontSize: 15, fontWeight: 600, color: theme.text, textAlign: 'center' }}>
              No events yet
            </Text>
            <Text
              style={{
                fontSize: 13,
                color: theme.text2,
                maxWidth: 280,
                lineHeight: 1.5,
                textAlign: 'center',
              }}
            >
              Follows, subs, raids and bits will appear here.
            </Text>
          </div>
        ) : (
          events.map((ev) => <EventCard key={ev.id} event={ev} />)
        )}
      </div>
    </div>
  )
}
