// packages/desktop/src/views/main/components/UserCardDialog.vue
<script setup lang="ts">
import { computed, ref, toRef, watch } from 'vue'
import { DialogContent, DialogOverlay, DialogPortal, DialogRoot } from 'reka-ui'
import type { Platform } from '@twirchat/shared/types'

import KickIcon from '../../../assets/icons/platforms/kick.svg'
import TwitchIcon from '../../../assets/icons/platforms/twitch.svg'
import YoutubeIcon from '../../../assets/icons/platforms/youtube.svg'
import { platformColor } from '../../shared/utils/platform'
import { useModerationOutcomes } from '../composables/useModerationOutcomes'
import { desktopApi, type ModerationAction, type ModerationPlatform } from '../services/desktop-api'
import { useUserCardMetadata } from '../composables/useUserCardMetadata'
import { useAliasStore } from '../stores/useAliasStore'
import UserChatHistoryPanel from './UserChatHistoryPanel.vue'

interface Props {
  platform: Platform
  platformUserId: string
  messageId?: string
  channelId?: string
  channelSlug?: string
  displayName: string
  username?: string
  avatarUrl?: string
  currentAlias?: string
}

const props = defineProps<Props>()
const open = defineModel<boolean>('open', { required: true })

const aliasStore = useAliasStore()
const { apply: applyModerationOutcome } = useModerationOutcomes()
const aliasValue = ref('')
const aliasInput = ref<HTMLInputElement | null>(null)
const platformRef = toRef(props, 'platform')
const platformUserIdRef = toRef(props, 'platformUserId')
const usernameRef = toRef(props, 'username')
const channelIdRef = toRef(props, 'channelId')
const channelSlugRef = toRef(props, 'channelSlug')

const {
  metadata,
  loading,
  error: metadataError,
  reload,
  supportedByCard,
} = useUserCardMetadata(
  platformRef,
  platformUserIdRef,
  usernameRef,
  channelIdRef,
  channelSlugRef,
  open,
)

watch(
  open,
  (isOpen) => {
    if (isOpen) {
      aliasValue.value = props.currentAlias ?? ''
    }
  },
  { immediate: true },
)

const platformIcon = computed(() => {
  if (props.platform === 'twitch') return TwitchIcon
  if (props.platform === 'kick') return KickIcon
  return YoutubeIcon
})

const titleHandle = computed(() => props.username ?? props.platformUserId)

type UserModerationAction = Extract<ModerationAction, 'timeout' | 'ban'>

const moderationChecking = ref(false)
const moderationAllowed = ref<boolean | null>(null)
const moderationError = ref<string | null>(null)
const moderationAction = ref<UserModerationAction | null>(null)
const moderationFeedback = ref<{ kind: 'error' | 'success'; text: string } | null>(null)

const moderationPlatform = computed<ModerationPlatform | undefined>(() => {
  return props.platform === 'twitch' || props.platform === 'kick' ? props.platform : undefined
})

const moderationInputError = computed((): string | undefined => {
  if (!moderationPlatform.value) return 'Moderation is available for Twitch and Kick only.'
  if (!props.channelSlug) return 'No channel context is available for this user.'
  if (!props.messageId) return 'Open this card from a chat message to moderate this user.'
  return undefined
})

const moderationDisabledReason = computed((): string | undefined => {
  if (moderationInputError.value) return moderationInputError.value
  if (moderationChecking.value) return 'Checking moderation permissions…'
  if (moderationError.value) return moderationError.value
  if (moderationAllowed.value === false)
    return 'You do not have moderation permission in this channel.'
  return undefined
})

function moderationErrorText(cause: unknown): string {
  return cause instanceof Error ? cause.message : String(cause)
}

async function loadModerationCapabilities(): Promise<void> {
  const platform = moderationPlatform.value
  const channelSlug = props.channelSlug
  if (!open.value || !platform || !channelSlug || !props.messageId) return

  moderationChecking.value = true
  moderationError.value = null
  try {
    const capabilities = await desktopApi.request.getModerationCapabilities({
      channelSlug,
      platform,
    })
    moderationAllowed.value = capabilities.canModerate
  } catch (cause) {
    moderationAllowed.value = false
    moderationError.value = moderationErrorText(cause)
  } finally {
    moderationChecking.value = false
  }
}

async function moderateUser(action: UserModerationAction): Promise<void> {
  const platform = moderationPlatform.value
  const channelSlug = props.channelSlug
  const messageId = props.messageId
  if (!platform || !channelSlug || !messageId || moderationDisabledReason.value) return

  moderationAction.value = action
  moderationFeedback.value = null
  try {
    await desktopApi.request.moderateMessage({
      action,
      channelSlug,
      messageId,
      platform,
      targetUserId: props.platformUserId,
      ...(action === 'timeout' ? { durationSeconds: 600 } : {}),
    })
    applyModerationOutcome({
      action,
      channelId: props.channelId ?? channelSlug,
      platform,
      targetUserId: props.platformUserId,
      ...(action === 'timeout' ? { durationSeconds: 600 } : {}),
    })
    moderationFeedback.value = {
      kind: 'success',
      text: action === 'timeout' ? 'Timed out for 10 minutes.' : 'User banned.',
    }
  } catch (cause) {
    moderationFeedback.value = { kind: 'error', text: moderationErrorText(cause) }
  } finally {
    moderationAction.value = null
  }
}

watch(
  () => [open.value, props.platform, props.channelSlug, props.messageId],
  ([isOpen]) => {
    moderationAllowed.value = null
    moderationError.value = null
    moderationFeedback.value = null
    if (isOpen) void loadModerationCapabilities()
  },
  { immediate: true },
)

function formatAbsoluteDate(value: string | null | undefined): string | null {
  if (!value) return null

  const date = new Date(value)
  if (Number.isNaN(date.getTime())) {
    return null
  }

  return date.toLocaleDateString()
}

function addCalendarMonths(date: Date, months: number): Date {
  const result = new Date(date)
  const day = result.getDate()

  result.setDate(1)
  result.setMonth(result.getMonth() + months)

  const lastDayOfTargetMonth = new Date(result.getFullYear(), result.getMonth() + 1, 0).getDate()
  result.setDate(Math.min(day, lastDayOfTargetMonth))

  return result
}

function formatDurationPart(value: number, unit: string): string {
  return `${value} ${unit}${value === 1 ? '' : 's'}`
}

function formatElapsedDuration(value: string | null | undefined): string | null {
  if (!value) return null

  const start = new Date(value)
  if (Number.isNaN(start.getTime())) {
    return null
  }

  const end = new Date()
  if (start > end) {
    return '0 seconds'
  }

  const totalMonths = Math.max(
    0,
    (end.getFullYear() - start.getFullYear()) * 12 + end.getMonth() - start.getMonth(),
  )

  let monthsSinceStart = totalMonths
  while (monthsSinceStart > 0 && addCalendarMonths(start, monthsSinceStart) > end) {
    monthsSinceStart -= 1
  }

  const years = Math.floor(monthsSinceStart / 12)
  const months = monthsSinceStart % 12
  const afterMonths = addCalendarMonths(start, monthsSinceStart)

  let remainingMilliseconds = Math.max(0, end.getTime() - afterMonths.getTime())

  const dayInMs = 24 * 60 * 60 * 1000
  const hourInMs = 60 * 60 * 1000
  const minuteInMs = 60 * 1000
  const secondInMs = 1000

  const days = Math.floor(remainingMilliseconds / dayInMs)
  remainingMilliseconds -= days * dayInMs

  const hours = Math.floor(remainingMilliseconds / hourInMs)
  remainingMilliseconds -= hours * hourInMs

  const minutes = Math.floor(remainingMilliseconds / minuteInMs)
  remainingMilliseconds -= minutes * minuteInMs

  const seconds = Math.floor(remainingMilliseconds / secondInMs)

  const parts = [
    years > 0 ? formatDurationPart(years, 'year') : null,
    months > 0 ? formatDurationPart(months, 'month') : null,
    days > 0 ? formatDurationPart(days, 'day') : null,
    hours > 0 ? formatDurationPart(hours, 'hour') : null,
    minutes > 0 ? formatDurationPart(minutes, 'minute') : null,
    seconds > 0 ? formatDurationPart(seconds, 'second') : null,
  ].filter((part): part is string => part !== null)

  return parts.join(' ') || '0 seconds'
}

const accountAgeText = computed(() => {
  const field = metadata.value?.accountAge
  if (!field) return null

  if (field.status === 'available') {
    return `Created ${formatAbsoluteDate(field.createdAt) ?? field.createdAt}`
  }

  return field.message ?? 'Unavailable'
})

const followAgeText = computed(() => {
  const field = metadata.value?.followAge
  if (!field) return null

  if (field.status === 'available') {
    const absoluteDate = formatAbsoluteDate(field.followedAt) ?? field.followedAt
    const elapsedDuration = formatElapsedDuration(field.followedAt)

    return elapsedDuration
      ? `Following since ${absoluteDate} · ${elapsedDuration}`
      : `Following since ${absoluteDate}`
  }

  return field.message ?? 'Unavailable'
})

const subscriptionDurationText = computed(() => {
  const field = metadata.value?.subscriptionDuration
  if (!field) return null

  if (field.status === 'available') {
    if (field.currentlySubscribed === true) {
      const parts = ['Currently subscribed']

      if (field.tier) {
        parts.push(`Tier ${field.tier}`)
      }

      if (field.isGift) {
        parts.push(field.gifterDisplayName ? `Gifted by ${field.gifterDisplayName}` : 'Gifted sub')
      }

      if (field.message) {
        parts.push(field.message)
      }

      return parts.join(' · ')
    }

    return field.message ?? 'Not currently subscribed'
  }

  return field.message ?? 'Unavailable'
})

const subAgeText = computed(() => {
  const field = metadata.value?.subAge
  if (!field) return null

  if (field.status === 'available' && field.months !== null) {
    return `${field.months} month${field.months === 1 ? '' : 's'}`
  }

  return field.message ?? 'Unavailable'
})

function focusInput() {
  aliasInput.value?.focus()
}

async function handleSaveAlias() {
  const val = aliasValue.value.trim()
  if (!val) {
    await aliasStore.removeAlias(props.platform, props.platformUserId)
  } else {
    await aliasStore.setAlias(props.platform, props.platformUserId, val)
  }
  open.value = false
}

async function handleRemoveAlias() {
  await aliasStore.removeAlias(props.platform, props.platformUserId)
  aliasValue.value = ''
  open.value = false
}

function initials(name: string): string {
  return name.slice(0, 2).toUpperCase()
}
</script>

<template>
  <DialogRoot v-model:open="open">
    <DialogPortal>
      <DialogOverlay class="dialog-overlay" />
      <DialogContent class="dialog-content" @open-auto-focus="focusInput">
        <div class="user-card-header" :style="{ '--platform-color': platformColor(platform) }">
          <div class="user-card-avatar-wrap">
            <img
              v-if="avatarUrl"
              :src="avatarUrl"
              :alt="displayName"
              class="user-card-avatar"
              referrerpolicy="no-referrer"
            />
            <div v-else class="user-card-avatar user-card-avatar-fallback">
              {{ initials(displayName) }}
            </div>
          </div>

          <div class="user-card-header-main">
            <div class="user-card-title-row">
              <h3 class="dialog-title">{{ displayName }}</h3>
              <component :is="platformIcon" class="user-card-platform-icon" />
            </div>
            <p class="user-card-subtitle">{{ titleHandle }}</p>
            <div class="user-card-badges-row">
              <span class="user-card-pill">{{ platform }}</span>
              <span v-if="currentAlias" class="user-card-pill user-card-pill-accent">
                Alias: {{ currentAlias }}
              </span>
            </div>
          </div>
        </div>

        <div class="user-card-section">
          <label class="dialog-label" for="user-alias-input">Display alias</label>
          <p class="dialog-description">
            Replaces the displayed name in chat. Leave empty to remove alias.
          </p>
          <div class="user-card-alias-row">
            <input
              id="user-alias-input"
              ref="aliasInput"
              v-model="aliasValue"
              class="dialog-input"
              :placeholder="displayName"
              maxlength="50"
              @keydown.enter.prevent="handleSaveAlias"
              @keydown.escape.prevent="open = false"
            />
            <button class="dialog-btn-save" @click="handleSaveAlias">Save</button>
          </div>
          <div class="dialog-actions dialog-actions-inline">
            <button class="dialog-btn-cancel" @click="open = false">Close</button>
            <button v-if="currentAlias" class="dialog-btn-danger" @click="handleRemoveAlias">
              Remove alias
            </button>
          </div>
        </div>

        <div class="user-card-section">
          <h4 class="user-card-metadata-title">Moderation</h4>
          <p class="dialog-description">Actions apply to this user in the message channel.</p>
          <p v-if="moderationDisabledReason" class="user-card-moderation-state">
            {{ moderationDisabledReason }}
          </p>
          <p
            v-if="moderationFeedback"
            class="user-card-moderation-state"
            :class="`user-card-moderation-state-${moderationFeedback.kind}`"
          >
            {{ moderationFeedback.text }}
          </p>
          <div class="user-card-moderation-actions">
            <button
              class="dialog-btn-timeout"
              :disabled="Boolean(moderationDisabledReason) || moderationAction !== null"
              @click="void moderateUser('timeout')"
            >
              {{ moderationAction === 'timeout' ? 'Timing out…' : 'Timeout 10m' }}
            </button>
            <button
              class="dialog-btn-danger"
              :disabled="Boolean(moderationDisabledReason) || moderationAction !== null"
              @click="void moderateUser('ban')"
            >
              {{ moderationAction === 'ban' ? 'Banning…' : 'Ban' }}
            </button>
          </div>
        </div>

        <div class="user-card-section">
          <div class="user-card-metadata-header">
            <div>
              <h4 class="user-card-metadata-title">Account metadata</h4>
              <p class="dialog-description">Fetched through the backend for this platform.</p>
            </div>

            <button
              v-if="supportedByCard"
              class="user-card-metadata-refresh"
              :disabled="loading"
              @click="void reload()"
            >
              Refresh
            </button>
          </div>

          <div v-if="!supportedByCard" class="user-card-metadata-state">
            Metadata is not supported for this platform yet.
          </div>
          <div v-else-if="loading" class="user-card-metadata-state">Loading metadata…</div>
          <div
            v-else-if="metadataError"
            class="user-card-metadata-state user-card-metadata-state-error"
          >
            <span>{{ metadataError }}</span>
            <button class="user-card-metadata-inline-btn" @click="void reload()">Retry</button>
          </div>
          <dl v-else-if="metadata" class="user-card-metadata-list">
            <div class="user-card-metadata-item">
              <dt>Account age</dt>
              <dd>{{ accountAgeText }}</dd>
            </div>
            <div class="user-card-metadata-item">
              <dt>Follow age</dt>
              <dd>{{ followAgeText }}</dd>
            </div>
            <div class="user-card-metadata-item">
              <dt>Subscription duration</dt>
              <dd>{{ subscriptionDurationText }}</dd>
            </div>
            <div class="user-card-metadata-item">
              <dt>Sub age</dt>
              <dd>{{ subAgeText }}</dd>
            </div>
          </dl>
        </div>

        <UserChatHistoryPanel
          :open="open"
          :platform="platform"
          :platform-user-id="platformUserId"
        />
      </DialogContent>
    </DialogPortal>
  </DialogRoot>
</template>

<style scoped>
.dialog-overlay {
  background: rgba(0, 0, 0, 0.6);
  position: fixed;
  inset: 0;
  z-index: 2000;
}

.dialog-content {
  background: var(--c-bg-2, #2a2a35);
  border: 1px solid var(--c-border, #3a3a45);
  border-radius: 8px;
  box-shadow: 0 8px 24px rgba(0, 0, 0, 0.5);
  position: fixed;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  width: 90vw;
  max-width: 760px;
  padding: 20px;
  z-index: 2001;
  max-height: min(85vh, 820px);
  overflow: auto;
}

.dialog-title {
  margin: 0;
  font-size: 1.35em;
  color: var(--c-text, #e2e2e8);
}

.dialog-description {
  margin: 0;
  font-size: 0.9em;
  color: var(--c-text-2, #8b8b99);
}

.user-card-subtitle {
  margin: 0;
  font-size: 0.9em;
  color: rgba(255, 255, 255, 0.75);
}

.dialog-label {
  display: block;
  margin-bottom: 6px;
  font-size: 0.8em;
  font-weight: 700;
  color: var(--c-text, #e2e2e8);
  text-transform: uppercase;
  letter-spacing: 0.04em;
}

.user-card-header {
  display: flex;
  gap: 16px;
  margin: -20px -20px 18px;
  padding: 20px;
  background: linear-gradient(
    135deg,
    color-mix(in srgb, var(--platform-color) 72%, #101012) 0%,
    #1a1a22 100%
  );
  border-bottom: 1px solid rgba(255, 255, 255, 0.08);
}

.user-card-avatar-wrap {
  flex-shrink: 0;
}

.user-card-avatar {
  width: 72px;
  height: 72px;
  border-radius: 18px;
  object-fit: cover;
  background: rgba(255, 255, 255, 0.08);
}

.user-card-avatar-fallback {
  display: flex;
  align-items: center;
  justify-content: center;
  font-weight: 800;
  font-size: 24px;
  color: white;
}

.user-card-header-main {
  min-width: 0;
  display: flex;
  flex-direction: column;
  gap: 8px;
}

.user-card-title-row {
  display: flex;
  align-items: center;
  gap: 10px;
}

.user-card-platform-icon {
  width: 18px;
  height: 18px;
  color: rgba(255, 255, 255, 0.95);
}

.user-card-badges-row {
  display: flex;
  flex-wrap: wrap;
  gap: 8px;
}

.user-card-pill {
  display: inline-flex;
  align-items: center;
  gap: 6px;
  min-height: 24px;
  padding: 0 10px;
  border-radius: 999px;
  background: rgba(0, 0, 0, 0.25);
  color: white;
  font-size: 12px;
  font-weight: 700;
  text-transform: uppercase;
}

.user-card-pill-accent {
  background: rgba(255, 255, 255, 0.16);
}

.user-card-section {
  margin-bottom: 18px;
}

.user-card-alias-row {
  display: flex;
  gap: 10px;
  align-items: center;
  margin-top: 12px;
}

.user-card-metadata-header {
  display: flex;
  align-items: flex-start;
  justify-content: space-between;
  gap: 12px;
  margin-bottom: 12px;
}

.user-card-metadata-title {
  margin: 0;
  font-size: 14px;
  font-weight: 700;
  color: var(--c-text, #e2e2e8);
}

.user-card-moderation-state {
  color: var(--c-text-2, #8b8b99);
  font-size: 12px;
  margin: 10px 0 0;
}

.user-card-moderation-state-error {
  color: #fca5a5;
}

.user-card-moderation-state-success {
  color: #86efac;
}

.user-card-moderation-actions {
  display: flex;
  gap: 10px;
  margin-top: 12px;
}

.user-card-metadata-refresh,
.user-card-metadata-inline-btn {
  border: none;
  border-radius: 6px;
  background: rgba(255, 255, 255, 0.08);
  color: var(--c-text, #e2e2e8);
  cursor: pointer;
  font: inherit;
}

.user-card-metadata-refresh {
  padding: 7px 10px;
  font-size: 12px;
}

.user-card-metadata-inline-btn {
  padding: 6px 10px;
  font-size: 12px;
}

.user-card-metadata-refresh:disabled,
.user-card-metadata-inline-btn:disabled {
  opacity: 0.6;
  cursor: default;
}

.user-card-metadata-state {
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 10px;
  min-height: 96px;
  padding: 16px;
  text-align: center;
  font-size: 13px;
  color: var(--c-text-2, #8b8b99);
  border: 1px solid rgba(255, 255, 255, 0.06);
  border-radius: 10px;
  background: rgba(0, 0, 0, 0.16);
}

.user-card-metadata-state-error {
  color: #fca5a5;
  flex-direction: column;
}

.user-card-metadata-list {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
  gap: 10px;
  margin: 0;
}

.user-card-metadata-item {
  min-width: 0;
  padding: 12px;
  border: 1px solid rgba(255, 255, 255, 0.06);
  border-radius: 10px;
  background: rgba(0, 0, 0, 0.16);
}

.user-card-metadata-item dt {
  margin: 0 0 6px;
  font-size: 11px;
  font-weight: 700;
  color: var(--c-text-2, #8b8b99);
  text-transform: uppercase;
  letter-spacing: 0.04em;
}

.user-card-metadata-item dd {
  margin: 0;
  font-size: 13px;
  color: var(--c-text, #e2e2e8);
  line-height: 1.45;
  overflow-wrap: anywhere;
}

.dialog-input {
  width: 100%;
  box-sizing: border-box;
  padding: 8px 12px;
  background: var(--c-bg, #1e1e24);
  border: 1px solid var(--c-border, #3a3a45);
  color: var(--c-text, #e2e2e8);
  border-radius: 4px;
  font-size: 0.95em;
}

.dialog-input:focus {
  outline: none;
  border-color: var(--c-accent, #9147ff);
}

.dialog-actions {
  display: flex;
  justify-content: flex-end;
  gap: 10px;
}

.dialog-actions-inline {
  margin-top: 12px;
  justify-content: space-between;
}

.dialog-btn-cancel,
.dialog-btn-save,
.dialog-btn-danger,
.dialog-btn-timeout {
  padding: 6px 14px;
  border-radius: 4px;
  cursor: pointer;
  border: none;
  font-weight: 500;
  font-size: 0.9em;
}

.dialog-btn-cancel {
  background: transparent;
  color: var(--c-text, #e2e2e8);
}

.dialog-btn-cancel:hover {
  background: rgba(255, 255, 255, 0.08);
}

.dialog-btn-save {
  background: var(--c-accent, #9147ff);
  color: #fff;
  flex-shrink: 0;
}

.dialog-btn-save:hover {
  opacity: 0.9;
}

.dialog-btn-danger {
  background: rgba(255, 80, 80, 0.14);
  color: #ff9b9b;
}

.dialog-btn-danger:hover {
  background: rgba(255, 80, 80, 0.2);
}

.dialog-btn-timeout {
  background: rgba(251, 191, 36, 0.16);
  color: #fde68a;
}

.dialog-btn-timeout:hover:not(:disabled) {
  background: rgba(251, 191, 36, 0.24);
}

.dialog-btn-danger:disabled,
.dialog-btn-timeout:disabled {
  cursor: default;
  opacity: 0.48;
}
</style>

// packages/desktop/src/gpuix/components/UserCardDialog.tsx
/**
 * User card dialog — port of UserCardDialog.vue onto GPUIX.
 *
 * Header gradient, alias editing, moderation actions (timeout/ban), account
 * metadata cards and the stored chat history panel.
 *
 * GPUIX deviations:
 * - CSS color-mix() in the header gradient is precomputed via hexMix().
 * - Dialog width is a fixed 760px (Vue used 90vw capped at 760px).
 * - The "Alias: X" pill keeps its case (the Vue CSS uppercased it via
 *   text-transform, which GPUIX does not support).
 * - The alias input has no 50-char maxlength (GPUIX inputs don't expose one).
 * - Esc closes via a focusable wrapper + input key handlers; reka-ui's global
 *   dialog Escape handling does not exist here.
 */

import { useCallback, useEffect, useRef, useState } from 'react'
import type { UserCardMetadataResponse } from '@twirchat/shared/protocol'
import type { UserCardTarget } from '../../views/main/utils/chatCommands'
import { publicChannelURL } from '../../views/main/utils/public-channel-url'
import { platformColor } from '../theme'
import { useTheme } from '../theme-context'
import { useBackend } from '../backend/context'
import type { ModerationPlatform } from '../backend/api'
import { aliasesStore, applyModerationOutcome, showNotice } from '../state/app'
import { Text } from './ui/Text'
import { RemoteImage } from './ui/RemoteImage'
import { Modal } from './ui/Modal'
import { PlatformIcon } from './ui/Icon'
import { UserChatHistoryPanel } from './user-card/UserChatHistoryPanel'
import {
  accountAgeText,
  errorText,
  followAgeText,
  hexMix,
  subAgeText,
  subscriptionDurationText,
} from './user-card/format'

type UserModerationAction = 'timeout' | 'ban'

function initials(name: string): string {
  return name.slice(0, 2).toUpperCase()
}

export function UserCardDialog({
  target,
  currentAlias,
  onClose,
}: {
  target: UserCardTarget
  currentAlias?: string
  onClose: () => void
}) {
  const theme = useTheme()
  const backend = useBackend()

  const effectiveAlias = currentAlias ?? target.currentAlias
  const titleHandle = target.username ?? target.platformUserId
  const channelUrl = target.username
    ? publicChannelURL(target.platform, target.username)
    : undefined

  // ── Alias ───────────────────────────────────────────────────────────────

  const [aliasValue, setAliasValue] = useState(effectiveAlias ?? '')
  useEffect(() => {
    setAliasValue(effectiveAlias ?? '')
  }, [effectiveAlias, target.platform, target.platformUserId])

  async function refreshAliases(): Promise<void> {
    aliasesStore.set(await backend.api.getUserAliases())
  }

  async function handleSaveAlias(): Promise<void> {
    const value = aliasValue.trim()
    try {
      if (!value) {
        await backend.api.removeUserAlias({
          platform: target.platform,
          platformUserId: target.platformUserId,
        })
      } else {
        await backend.api.setUserAlias({
          platform: target.platform,
          platformUserId: target.platformUserId,
          alias: value,
        })
      }
      await refreshAliases()
    } catch (cause) {
      showNotice('error', errorText(cause))
      return
    }
    onClose()
  }

  async function handleRemoveAlias(): Promise<void> {
    try {
      await backend.api.removeUserAlias({
        platform: target.platform,
        platformUserId: target.platformUserId,
      })
      await refreshAliases()
    } catch (cause) {
      showNotice('error', errorText(cause))
      return
    }
    setAliasValue('')
    onClose()
  }

  // ── Open public channel ─────────────────────────────────────────────────

  const [openingPublicChannel, setOpeningPublicChannel] = useState(false)
  const [publicChannelError, setPublicChannelError] = useState<string | null>(null)

  async function openPublicChannel(): Promise<void> {
    if (!channelUrl) return
    setOpeningPublicChannel(true)
    setPublicChannelError(null)
    try {
      await backend.api.openExternalUrl({ url: channelUrl })
    } catch (cause) {
      setPublicChannelError(errorText(cause))
    } finally {
      setOpeningPublicChannel(false)
    }
  }

  // ── Moderation ──────────────────────────────────────────────────────────

  const moderationPlatform: ModerationPlatform | undefined =
    target.platform === 'twitch' || target.platform === 'kick' ? target.platform : undefined

  const [moderationChecking, setModerationChecking] = useState(false)
  const [moderationAllowed, setModerationAllowed] = useState<boolean | null>(null)
  const [capabilitiesError, setCapabilitiesError] = useState<string | null>(null)
  const [moderationAction, setModerationAction] = useState<UserModerationAction | null>(null)
  const [moderationFeedback, setModerationFeedback] = useState<{
    kind: 'error' | 'success'
    text: string
  } | null>(null)

  const moderationInputError = ((): string | undefined => {
    if (!moderationPlatform) return 'Moderation is available for Twitch and Kick only.'
    if (!target.channelSlug) return 'No channel context is available for this user.'
    if (!target.messageId) return 'Open this card from a chat message to moderate this user.'
    return undefined
  })()

  const moderationDisabledReason =
    moderationInputError ??
    (moderationChecking ? 'Checking moderation permissions…' : undefined) ??
    capabilitiesError ??
    (moderationAllowed === false
      ? 'You do not have moderation permission in this channel.'
      : undefined)

  useEffect(() => {
    setModerationAllowed(null)
    setCapabilitiesError(null)
    setModerationFeedback(null)

    const platform = moderationPlatform
    const channelSlug = target.channelSlug
    if (!platform || !channelSlug || !target.messageId) return

    let cancelled = false
    setModerationChecking(true)
    backend.api
      .getModerationCapabilities({ channelSlug, platform })
      .then((capabilities) => {
        if (!cancelled) setModerationAllowed(capabilities.canModerate)
      })
      .catch((cause: unknown) => {
        if (cancelled) return
        setModerationAllowed(false)
        setCapabilitiesError(errorText(cause))
      })
      .finally(() => {
        if (!cancelled) setModerationChecking(false)
      })
    return () => {
      cancelled = true
    }
  }, [backend, moderationPlatform, target.channelSlug, target.messageId])

  async function moderateUser(action: UserModerationAction): Promise<void> {
    const platform = moderationPlatform
    const channelSlug = target.channelSlug
    const messageId = target.messageId
    if (!platform || !channelSlug || !messageId || moderationDisabledReason) return

    setModerationAction(action)
    setModerationFeedback(null)
    try {
      await backend.api.moderateMessage({
        action,
        channelSlug,
        messageId,
        platform,
        targetUserId: target.platformUserId,
        ...(action === 'timeout' ? { durationSeconds: 600 } : {}),
      })
      applyModerationOutcome({
        action,
        channelId: target.channelId ?? channelSlug,
        platform,
        targetUserId: target.platformUserId,
        ...(action === 'timeout' ? { durationSeconds: 600 } : {}),
      })
      const text = action === 'timeout' ? 'Timed out for 10 minutes.' : 'User banned.'
      setModerationFeedback({ kind: 'success', text })
      showNotice('success', text)
    } catch (cause) {
      const text = errorText(cause)
      setModerationFeedback({ kind: 'error', text })
      showNotice('error', text)
    } finally {
      setModerationAction(null)
    }
  }

  // ── Account metadata (port of useUserCardMetadata) ──────────────────────

  const supportedByCard = moderationPlatform !== undefined
  const [metadata, setMetadata] = useState<UserCardMetadataResponse | null>(null)
  const [metadataLoading, setMetadataLoading] = useState(false)
  const [metadataError, setMetadataError] = useState<string | null>(null)
  const metadataGenerationRef = useRef(0)

  const reloadMetadata = useCallback(async (): Promise<void> => {
    const platform = moderationPlatform
    if (!platform) {
      setMetadata(null)
      setMetadataError(null)
      setMetadataLoading(false)
      return
    }

    const generation = metadataGenerationRef.current + 1
    metadataGenerationRef.current = generation
    setMetadataLoading(true)
    setMetadataError(null)

    try {
      const response = await backend.api.getUserCardMetadata({
        platform,
        platformUserId: target.platformUserId,
        username: target.username,
        channelId: target.channelId,
        channelSlug: target.channelSlug,
      })
      if (generation !== metadataGenerationRef.current) return
      setMetadata(response)
    } catch (loadError) {
      if (generation !== metadataGenerationRef.current) return
      setMetadata(null)
      setMetadataError(errorText(loadError))
    } finally {
      if (generation === metadataGenerationRef.current) {
        setMetadataLoading(false)
      }
    }
  }, [
    backend,
    moderationPlatform,
    target.platformUserId,
    target.username,
    target.channelId,
    target.channelSlug,
  ])

  // Reset + load on mount / when the target changes (reloadMetadata identity
  // tracks exactly those fields).
  useEffect(() => {
    metadataGenerationRef.current += 1
    setMetadata(null)
    setMetadataError(null)
    setMetadataLoading(false)
    if (supportedByCard) void reloadMetadata()
  }, [reloadMetadata, supportedByCard])

  // ── Render ──────────────────────────────────────────────────────────────

  const moderationButtonsDisabled = Boolean(moderationDisabledReason) || moderationAction !== null

  const metadataItems: Array<{ label: string; value: string | null }> = metadata
    ? [
        { label: 'Account age', value: accountAgeText(metadata) },
        { label: 'Follow age', value: followAgeText(metadata) },
        { label: 'Subscription duration', value: subscriptionDurationText(metadata) },
        { label: 'Sub age', value: subAgeText(metadata) },
      ]
    : []

  return (
    <Modal width={760} onClose={onClose}>
      <div
        tabIndex={-1}
        onKeyDown={(event) => {
          if (event.key === 'escape') onClose()
        }}
        style={{
          display: 'flex',
          flexDirection: 'column',
          flexGrow: 1,
          minHeight: 0,
          overflowY: 'scroll',
        }}
      >
        {/* Header (full-bleed: the Vue version used negative margins) */}
        <div
          style={{
            display: 'flex',
            flexDirection: 'row',
            gap: 16,
            padding: 20,
            marginBottom: 18,
            background: {
              type: 'linear-gradient',
              angle: 135,
              stops: [
                { color: hexMix(platformColor(target.platform), '#101012', 0.72), position: 0 },
                { color: '#1a1a22', position: 1 },
              ],
            },
            borderBottomWidth: 1,
            borderColor: 'rgba(255, 255, 255, 0.08)',
          }}
        >
          <div style={{ flexShrink: 0 }}>
            {target.avatarUrl ? (
              <RemoteImage
                url={target.avatarUrl}
                objectFit="cover"
                style={{
                  width: 72,
                  height: 72,
                  borderRadius: 18,
                  backgroundColor: 'rgba(255, 255, 255, 0.08)',
                }}
              />
            ) : (
              <div
                style={{
                  width: 72,
                  height: 72,
                  borderRadius: 18,
                  backgroundColor: 'rgba(255, 255, 255, 0.08)',
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                }}
              >
                <Text style={{ fontWeight: 800, fontSize: 24, color: '#ffffff' }}>
                  {initials(target.displayName)}
                </Text>
              </div>
            )}
          </div>

          <div
            style={{
              minWidth: 0,
              display: 'flex',
              flexDirection: 'column',
              gap: 8,
            }}
          >
            <div
              style={{
                display: 'flex',
                flexDirection: 'row',
                alignItems: 'center',
                gap: 10,
              }}
            >
              <Text style={{ fontSize: 18, fontWeight: 700, color: theme.text }}>
                {target.displayName}
              </Text>
              <PlatformIcon
                platform={target.platform}
                size={18}
                color="rgba(255, 255, 255, 0.95)"
              />
            </div>
            <Text style={{ fontSize: 13, color: 'rgba(255, 255, 255, 0.75)' }}>{titleHandle}</Text>
            <div style={{ display: 'flex', flexDirection: 'row', flexWrap: 'wrap', gap: 8 }}>
              <HeaderPill>{target.platform.toUpperCase()}</HeaderPill>
              {effectiveAlias ? <HeaderPill accent>{`Alias: ${effectiveAlias}`}</HeaderPill> : null}
            </div>
          </div>
        </div>

        <div
          style={{
            paddingLeft: 20,
            paddingRight: 20,
            paddingBottom: 20,
            display: 'flex',
            flexDirection: 'column',
          }}
        >
          {/* Alias section */}
          <div style={{ marginBottom: 18 }}>
            <Text
              style={{
                fontSize: 11,
                fontWeight: 700,
                color: theme.text,
                marginBottom: 6,
              }}
            >
              {'Display alias'.toUpperCase()}
            </Text>
            <Text style={{ fontSize: 13, color: theme.text2 }}>
              Replaces the displayed name in chat. Leave empty to remove alias.
            </Text>
            <div
              style={{
                display: 'flex',
                flexDirection: 'row',
                gap: 10,
                alignItems: 'center',
                marginTop: 12,
              }}
            >
              <input
                autoFocus
                value={aliasValue}
                placeholder={target.displayName}
                onChange={(event) => setAliasValue(event.value ?? '')}
                onSubmit={() => void handleSaveAlias()}
                onKeyDown={(event) => {
                  if (event.key === 'escape') onClose()
                }}
                theme={{ caret: '#a78bfa' }}
                style={{
                  flexGrow: 1,
                  minWidth: 0,
                  paddingTop: 8,
                  paddingBottom: 8,
                  paddingLeft: 12,
                  paddingRight: 12,
                  backgroundColor: '#1e1e24',
                  borderWidth: 1,
                  borderColor: '#3a3a45',
                  borderRadius: 4,
                  fontSize: 13,
                  color: theme.text,
                }}
              />
              <div
                onClick={() => void handleSaveAlias()}
                style={{
                  flexShrink: 0,
                  backgroundColor: '#9147ff',
                  borderRadius: 4,
                  paddingTop: 6,
                  paddingBottom: 6,
                  paddingLeft: 14,
                  paddingRight: 14,
                  cursor: 'pointer',
                  hover: { opacity: 0.9 },
                }}
              >
                <Text style={{ fontSize: 13, fontWeight: 500, color: '#ffffff' }}>Save</Text>
              </div>
            </div>
            <div
              style={{
                display: 'flex',
                flexDirection: 'row',
                justifyContent: 'space-between',
                gap: 10,
                marginTop: 12,
              }}
            >
              {channelUrl ? (
                <GhostButton
                  disabled={openingPublicChannel}
                  onClick={() => void openPublicChannel()}
                >
                  {openingPublicChannel ? 'Opening…' : 'Open channel'}
                </GhostButton>
              ) : null}
              <GhostButton onClick={onClose}>Close</GhostButton>
              {effectiveAlias ? (
                <DangerButton onClick={() => void handleRemoveAlias()}>Remove alias</DangerButton>
              ) : null}
            </div>
            {publicChannelError ? (
              <div
                style={{
                  display: 'flex',
                  flexDirection: 'row',
                  alignItems: 'center',
                  gap: 8,
                  marginTop: 10,
                }}
              >
                <Text style={{ fontSize: 12, color: '#fca5a5' }}>{publicChannelError}</Text>
                <InlineButton onClick={() => void openPublicChannel()}>Retry</InlineButton>
              </div>
            ) : null}
          </div>

          {/* Moderation section */}
          <div style={{ marginBottom: 18 }}>
            <Text style={{ fontSize: 14, fontWeight: 700, color: theme.text }}>Moderation</Text>
            <Text style={{ fontSize: 13, color: theme.text2 }}>
              Actions apply to this user in the message channel.
            </Text>
            {moderationDisabledReason ? (
              <Text style={{ fontSize: 12, color: theme.text2, marginTop: 10 }}>
                {moderationDisabledReason}
              </Text>
            ) : null}
            {moderationFeedback ? (
              <Text
                style={{
                  fontSize: 12,
                  color: moderationFeedback.kind === 'error' ? '#fca5a5' : '#86efac',
                  marginTop: 10,
                }}
              >
                {moderationFeedback.text}
              </Text>
            ) : null}
            <div
              style={{
                display: 'flex',
                flexDirection: 'row',
                gap: 10,
                marginTop: 12,
              }}
            >
              <div
                onClick={moderationButtonsDisabled ? undefined : () => void moderateUser('timeout')}
                style={{
                  backgroundColor: 'rgba(251, 191, 36, 0.16)',
                  borderRadius: 4,
                  paddingTop: 6,
                  paddingBottom: 6,
                  paddingLeft: 14,
                  paddingRight: 14,
                  cursor: moderationButtonsDisabled ? 'default' : 'pointer',
                  opacity: moderationButtonsDisabled ? 0.48 : 1,
                  hover: moderationButtonsDisabled
                    ? {}
                    : { backgroundColor: 'rgba(251, 191, 36, 0.24)' },
                }}
              >
                <Text style={{ fontSize: 13, fontWeight: 500, color: '#fde68a' }}>
                  {moderationAction === 'timeout' ? 'Timing out…' : 'Timeout 10m'}
                </Text>
              </div>
              <DangerButton
                disabled={moderationButtonsDisabled}
                onClick={() => void moderateUser('ban')}
              >
                {moderationAction === 'ban' ? 'Banning…' : 'Ban'}
              </DangerButton>
            </div>
          </div>

          {/* Account metadata section */}
          <div style={{ marginBottom: 18 }}>
            <div
              style={{
                display: 'flex',
                flexDirection: 'row',
                alignItems: 'flex-start',
                justifyContent: 'space-between',
                gap: 12,
                marginBottom: 12,
              }}
            >
              <div style={{ display: 'flex', flexDirection: 'column' }}>
                <Text style={{ fontSize: 14, fontWeight: 700, color: theme.text }}>
                  Account metadata
                </Text>
                <Text style={{ fontSize: 13, color: theme.text2 }}>
                  Fetched through the backend for this platform.
                </Text>
              </div>

              {supportedByCard ? (
                <InlineButton disabled={metadataLoading} onClick={() => void reloadMetadata()}>
                  Refresh
                </InlineButton>
              ) : null}
            </div>

            {!supportedByCard ? (
              <MetadataState>
                <Text style={{ fontSize: 13, color: theme.text2 }}>
                  Metadata is not supported for this platform yet.
                </Text>
              </MetadataState>
            ) : metadataLoading ? (
              <MetadataState>
                <Text style={{ fontSize: 13, color: theme.text2 }}>Loading metadata…</Text>
              </MetadataState>
            ) : metadataError ? (
              <MetadataState error>
                <Text style={{ fontSize: 13, color: '#fca5a5' }}>{metadataError}</Text>
                <InlineButton onClick={() => void reloadMetadata()}>Retry</InlineButton>
              </MetadataState>
            ) : metadata ? (
              <div
                style={{
                  display: 'flex',
                  flexDirection: 'row',
                  flexWrap: 'wrap',
                  gap: 10,
                }}
              >
                {metadataItems.map((item) => (
                  <div
                    key={item.label}
                    style={{
                      flexGrow: 1,
                      flexBasis: 150,
                      minWidth: 0,
                      padding: 12,
                      borderWidth: 1,
                      borderColor: 'rgba(255, 255, 255, 0.06)',
                      borderRadius: 10,
                      backgroundColor: 'rgba(0, 0, 0, 0.16)',
                    }}
                  >
                    <Text
                      style={{
                        fontSize: 11,
                        fontWeight: 700,
                        color: theme.text2,
                        marginBottom: 6,
                      }}
                    >
                      {item.label.toUpperCase()}
                    </Text>
                    <Text style={{ fontSize: 13, color: theme.text, lineHeight: 19 }}>
                      {item.value ?? ''}
                    </Text>
                  </div>
                ))}
              </div>
            ) : null}
          </div>

          <UserChatHistoryPanel platform={target.platform} platformUserId={target.platformUserId} />
        </div>
      </div>
    </Modal>
  )
}

// ── Local styled bits ───────────────────────────────────────────────────────

function HeaderPill({ accent, children }: { accent?: boolean; children: string }) {
  return (
    <div
      style={{
        display: 'flex',
        alignItems: 'center',
        minHeight: 24,
        paddingLeft: 10,
        paddingRight: 10,
        borderRadius: 999,
        backgroundColor: accent ? 'rgba(255, 255, 255, 0.16)' : 'rgba(0, 0, 0, 0.25)',
      }}
    >
      <Text style={{ fontSize: 12, fontWeight: 700, color: '#ffffff' }}>{children}</Text>
    </div>
  )
}

function GhostButton({
  disabled,
  onClick,
  children,
}: {
  disabled?: boolean
  onClick: () => void
  children: string
}) {
  const theme = useTheme()
  return (
    <div
      onClick={disabled ? undefined : onClick}
      style={{
        backgroundColor: 'transparent',
        borderRadius: 4,
        paddingTop: 6,
        paddingBottom: 6,
        paddingLeft: 14,
        paddingRight: 14,
        cursor: disabled ? 'default' : 'pointer',
        opacity: disabled ? 0.6 : 1,
        hover: disabled ? {} : { backgroundColor: 'rgba(255, 255, 255, 0.08)' },
      }}
    >
      <Text style={{ fontSize: 13, fontWeight: 500, color: theme.text }}>{children}</Text>
    </div>
  )
}

function DangerButton({
  disabled,
  onClick,
  children,
}: {
  disabled?: boolean
  onClick: () => void
  children: string
}) {
  return (
    <div
      onClick={disabled ? undefined : onClick}
      style={{
        backgroundColor: 'rgba(255, 80, 80, 0.14)',
        borderRadius: 4,
        paddingTop: 6,
        paddingBottom: 6,
        paddingLeft: 14,
        paddingRight: 14,
        cursor: disabled ? 'default' : 'pointer',
        opacity: disabled ? 0.48 : 1,
        hover: disabled ? {} : { backgroundColor: 'rgba(255, 80, 80, 0.2)' },
      }}
    >
      <Text style={{ fontSize: 13, fontWeight: 500, color: '#ff9b9b' }}>{children}</Text>
    </div>
  )
}

function InlineButton({
  disabled,
  onClick,
  children,
}: {
  disabled?: boolean
  onClick: () => void
  children: string
}) {
  const theme = useTheme()
  return (
    <div
      onClick={disabled ? undefined : onClick}
      style={{
        borderRadius: 6,
        backgroundColor: 'rgba(255, 255, 255, 0.08)',
        paddingTop: 6,
        paddingBottom: 6,
        paddingLeft: 10,
        paddingRight: 10,
        cursor: disabled ? 'default' : 'pointer',
        opacity: disabled ? 0.6 : 1,
        flexShrink: 0,
        hover: disabled ? {} : { backgroundColor: 'rgba(255, 255, 255, 0.14)' },
      }}
    >
      <Text style={{ fontSize: 12, color: theme.text }}>{children}</Text>
    </div>
  )
}

function MetadataState({ error, children }: { error?: boolean; children: React.ReactNode }) {
  return (
    <div
      style={{
        display: 'flex',
        flexDirection: error ? 'column' : 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 10,
        minHeight: 96,
        padding: 16,
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.06)',
        borderRadius: 10,
        backgroundColor: 'rgba(0, 0, 0, 0.16)',
      }}
    >
      {children}
    </div>
  )
}
